2022-06-08 17:54:40.595 | ERROR    | monitor.searchSpiders.tieba:get_request_from_keyword:34 - E 贴吧错误HTTPSConnectionPool(host='wappass.baidu.com', port=443): Max retries exceeded with url: /static/captcha/tuxing.html?ak=2ef521ec36290baed33d66de9b16f625&backurl=http%3A%2F%2Ftieba.baidu.com%2Ff%2Fsearch%2Fres%3Fisnew%3D1%26kw%3D%26qw%3D%25E5%25A4%2596%25E4%25BA%25A4%25E9%2583%25A8%25EF%25BC%259A%25E5%259C%25A8%25E5%2590%2584%25E6%2596%25B9%25E8%25BE%25BE%25E6%2588%2590%25E5%2585%25B1%25E8%25AF%2586%25E4%25B9%258B%25E5%2589%258D%25E7%25BE%258E%25E8%258B%25B1%25E6%25BE%25B3%25E4%25B8%258D%25E5%25BA%2594%25E5%25BC%2580%25E5%25B1%2595%25E6%25A0%25B8%25E6%25BD%259C%25E8%2589%2587%25E5%2590%2588%25E4%25BD%259C%26rn%3D10%26un%3D%26only_thread%3D0%26sm%3D1%26sd%3D%26ed%3D%26pn%3D3&timestamp=1654682080&signature=226957534cdee2321ca1e4c994fda626 (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1131)')))
Traceback (most recent call last):

  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
                       │    └ <function HTTPConnectionPool._make_request at 0x7fe06b3fed30>
                       └ <urllib3.connectionpool.HTTPSConnectionPool object at 0x7fdd3d86fdc0>
  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
    │    │              └ <urllib3.connection.HTTPSConnection object at 0x7fdce241aeb0>
    │    └ <function HTTPSConnectionPool._validate_conn at 0x7fe06b3ff280>
    └ <urllib3.connectionpool.HTTPSConnectionPool object at 0x7fdd3d86fdc0>
  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
    │    └ <function HTTPSConnection.connect at 0x7fe06b46d940>
    └ <urllib3.connection.HTTPSConnection object at 0x7fdce241aeb0>
  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/connection.py", line 416, in connect
    self.sock = ssl_wrap_socket(
    │    │      └ <function ssl_wrap_socket at 0x7fe06b468670>
    │    └ None
    └ <urllib3.connection.HTTPSConnection object at 0x7fdce241aeb0>
  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
               └ <function _ssl_wrap_socket_impl at 0x7fe06b468820>
  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
           │           │           │                     └ 'wappass.baidu.com'
           │           │           └ <socket.socket [closed] fd=-1, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6>
           │           └ <function SSLContext.wrap_socket at 0x7fe08118de50>
           └ <ssl.SSLContext object at 0x7fe0601db0c0>
  File "/usr/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
           │    │               └ <classmethod object at 0x7fe08c8cfaf0>
           │    └ <class 'ssl.SSLSocket'>
           └ <ssl.SSLContext object at 0x7fe0601db0c0>
  File "/usr/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
    │    └ <function SSLSocket.do_handshake at 0x7fe08c8d2d30>
    └ <ssl.SSLSocket [closed] fd=-1, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6>
  File "/usr/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
    │    └ None
    └ <ssl.SSLSocket [closed] fd=-1, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6>

ssl.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1131)


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/home/chase/.local/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
           │    └ <function HTTPConnectionPool.urlopen at 0x7fe06b3fef70>
           └ <urllib3.connectionpool.HTTPSConnectionPool object at 0x7fdd3d86fdc0>
  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
              │       └ <function Retry.increment at 0x7fe06b443280>
              └ Retry(total=0, connect=None, read=False, redirect=None, status=None)
  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
          │             │      │    │        │             └ 'unknown'
          │             │      │    │        └ <class 'urllib3.exceptions.ResponseError'>
          │             │      │    └ SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1131)'))
          │             │      └ '/static/captcha/tuxing.html?ak=2ef521ec36290baed33d66de9b16f625&backurl=http%3A%2F%2Ftieba.baidu.com%2Ff%2Fsearch%2Fres%3Fis...
          │             └ <urllib3.connectionpool.HTTPSConnectionPool object at 0x7fdd3d86fdc0>
          └ <class 'urllib3.exceptions.MaxRetryError'>

urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='wappass.baidu.com', port=443): Max retries exceeded with url: /static/captcha/tuxing.html?ak=2ef521ec36290baed33d66de9b16f625&backurl=http%3A%2F%2Ftieba.baidu.com%2Ff%2Fsearch%2Fres%3Fisnew%3D1%26kw%3D%26qw%3D%25E5%25A4%2596%25E4%25BA%25A4%25E9%2583%25A8%25EF%25BC%259A%25E5%259C%25A8%25E5%2590%2584%25E6%2596%25B9%25E8%25BE%25BE%25E6%2588%2590%25E5%2585%25B1%25E8%25AF%2586%25E4%25B9%258B%25E5%2589%258D%25E7%25BE%258E%25E8%258B%25B1%25E6%25BE%25B3%25E4%25B8%258D%25E5%25BA%2594%25E5%25BC%2580%25E5%25B1%2595%25E6%25A0%25B8%25E6%25BD%259C%25E8%2589%2587%25E5%2590%2588%25E4%25BD%259C%26rn%3D10%26un%3D%26only_thread%3D0%26sm%3D1%26sd%3D%26ed%3D%26pn%3D3&timestamp=1654682080&signature=226957534cdee2321ca1e4c994fda626 (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1131)')))


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/usr/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7fe08f92ea60>
    └ <Thread(Thread-31770, started daemon 140587080496896)>
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7fe08f92e790>
    └ <Thread(Thread-31770, started daemon 140587080496896)>
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-31770, started daemon 140587080496896)>
    │    │        │    └ ('ProjectManager.run_func_by_thread',)
    │    │        └ <Thread(Thread-31770, started daemon 140587080496896)>
    │    └ <bound method ProjectManager.get_request_from_keywords_hot of <monitor.projectManager.ProjectManager object at 0x7fe063c65790>>
    └ <Thread(Thread-31770, started daemon 140587080496896)>

  File "/home/users/Scy/yuqing/spider/monitor/projectManager.py", line 833, in get_request_from_keywords_hot
    self.search_spider_manager.crawl_by_keyword(
    │    │                     └ <function SearchSpidersManager.crawl_by_keyword at 0x7fe063c71160>
    │    └ <monitor.spiderManager.SearchSpidersManager object at 0x7fe0638938b0>
    └ <monitor.projectManager.ProjectManager object at 0x7fe063c65790>

  File "/home/users/Scy/yuqing/spider/monitor/spiderManager.py", line 118, in crawl_by_keyword
    self.crawl_by_keyword_signal_platform(project_names, platform, keyword, crawl_time, project_times)
    │    │                                │              │         │        │           └ {'default': <monitor.TimeSection object at 0x7fe0639a2b80>}
    │    │                                │              │         │        └ <monitor.TimeSection object at 0x7fde705381c0>
    │    │                                │              │         └ '外交部：在各方达成共识之前美英澳不应开展核潜艇合作'
    │    │                                │              └ '贴吧'
    │    │                                └ ['default']
    │    └ <function SearchSpidersManager.crawl_by_keyword_signal_platform at 0x7fe063c71280>
    └ <monitor.spiderManager.SearchSpidersManager object at 0x7fe0638938b0>

  File "/home/users/Scy/yuqing/spider/monitor/spiderManager.py", line 150, in crawl_by_keyword_signal_platform
    requests = self.get_request_from_keyword(platform, keyword_only, **crawl_time.to_dict())
               │    │                        │         │               │          └ <function TimeSection.to_dict at 0x7fe06b8931f0>
               │    │                        │         │               └ <monitor.TimeSection object at 0x7fde705381c0>
               │    │                        │         └ '外交部：在各方达成共识之前美英澳不应开展核潜艇合作'
               │    │                        └ '贴吧'
               │    └ <function SearchSpidersManager.get_request_from_keyword at 0x7fe063c713a0>
               └ <monitor.spiderManager.SearchSpidersManager object at 0x7fe0638938b0>

  File "/home/users/Scy/yuqing/spider/monitor/spiderManager.py", line 214, in get_request_from_keyword
    for request in self.spiders[platform].get_request_from_keyword(headers, search_url, keyword, content_url,
                   │    │       │                                  │        │           │        └ None
                   │    │       │                                  │        │           └ '外交部：在各方达成共识之前美英澳不应开展核潜艇合作'
                   │    │       │                                  │        └ <string.Template object at 0x7fdd4ac413a0>
                   │    │       │                                  └ {'Connection': 'keep-alive', 'sec-ch-ua': "'Chromium';v='92',' Not A;Brand';v='99', 'Google Chrome';v='92'", 'sec-ch-ua-mobil...
                   │    │       └ '贴吧'
                   │    └ {'凤凰网': <monitor.searchSpiders.ifeng.Ifeng object at 0x7fe063893370>, '头条': <monitor.searchSpiders.toutiao.Toutiao object at ...
                   └ <monitor.spiderManager.SearchSpidersManager object at 0x7fe0638938b0>

> File "/home/users/Scy/yuqing/spider/monitor/searchSpiders/tieba.py", line 22, in get_request_from_keyword
    response = requests.get(url, headers=headers, timeout=50)
               │        │   │            └ {'Connection': 'keep-alive', 'sec-ch-ua': "'Chromium';v='92',' Not A;Brand';v='99', 'Google Chrome';v='92'", 'sec-ch-ua-mobil...
               │        │   └ 'https://tieba.baidu.com/f/search/res?isnew=1&kw=&qw=外交部：在各方达成共识之前美英澳不应开展核潜艇合作&rn=10&un=&only_thread=0&sm=1&sd=&ed=&pn=3'
               │        └ <function get at 0x7fe06b2724c0>
               └ <module 'requests' from '/home/chase/.local/lib/python3.8/site-packages/requests/__init__.py'>

  File "/home/chase/.local/lib/python3.8/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
           │              │           │         └ {'headers': {'Connection': 'keep-alive', 'sec-ch-ua': "'Chromium';v='92',' Not A;Brand';v='99', 'Google Chrome';v='92'", 'sec...
           │              │           └ None
           │              └ 'https://tieba.baidu.com/f/search/res?isnew=1&kw=&qw=外交部：在各方达成共识之前美英澳不应开展核潜艇合作&rn=10&un=&only_thread=0&sm=1&sd=&ed=&pn=3'
           └ <function request at 0x7fe06b268310>
  File "/home/chase/.local/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
           │       │              │           │      └ {'params': None, 'headers': {'Connection': 'keep-alive', 'sec-ch-ua': "'Chromium';v='92',' Not A;Brand';v='99', 'Google Chrom...
           │       │              │           └ 'https://tieba.baidu.com/f/search/res?isnew=1&kw=&qw=外交部：在各方达成共识之前美英澳不应开展核潜艇合作&rn=10&un=&only_thread=0&sm=1&sd=&ed=&pn=3'
           │       │              └ 'get'
           │       └ <function Session.request at 0x7fe06b27bc10>
           └ <requests.sessions.Session object at 0x7fdf7411c640>
  File "/home/chase/.local/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
           │    │    │       └ {'timeout': 50, 'allow_redirects': True, 'verify': True, 'proxies': OrderedDict(), 'stream': False, 'cert': None}
           │    │    └ <PreparedRequest [GET]>
           │    └ <function Session.send at 0x7fe06b2720d0>
           └ <requests.sessions.Session object at 0x7fdf7411c640>
  File "/home/chase/.local/lib/python3.8/site-packages/requests/sessions.py", line 677, in send
    history = [resp for resp in gen]
                                └ <generator object SessionRedirectMixin.resolve_redirects at 0x7fdcd0e3fc10>
  File "/home/chase/.local/lib/python3.8/site-packages/requests/sessions.py", line 677, in <listcomp>
    history = [resp for resp in gen]
  File "/home/chase/.local/lib/python3.8/site-packages/requests/sessions.py", line 237, in resolve_redirects
    resp = self.send(
           │    └ <function Session.send at 0x7fe06b2720d0>
           └ <requests.sessions.Session object at 0x7fdf7411c640>
  File "/home/chase/.local/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
        │       │    │          └ {'stream': False, 'timeout': 50, 'verify': True, 'cert': None, 'proxies': OrderedDict()}
        │       │    └ <PreparedRequest [GET]>
        │       └ <function HTTPAdapter.send at 0x7fe06b27b550>
        └ <requests.adapters.HTTPAdapter object at 0x7fdf102d5dc0>
  File "/home/chase/.local/lib/python3.8/site-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
          │                   └ <PreparedRequest [GET]>
          └ <class 'requests.exceptions.SSLError'>

requests.exceptions.SSLError: HTTPSConnectionPool(host='wappass.baidu.com', port=443): Max retries exceeded with url: /static/captcha/tuxing.html?ak=2ef521ec36290baed33d66de9b16f625&backurl=http%3A%2F%2Ftieba.baidu.com%2Ff%2Fsearch%2Fres%3Fisnew%3D1%26kw%3D%26qw%3D%25E5%25A4%2596%25E4%25BA%25A4%25E9%2583%25A8%25EF%25BC%259A%25E5%259C%25A8%25E5%2590%2584%25E6%2596%25B9%25E8%25BE%25BE%25E6%2588%2590%25E5%2585%25B1%25E8%25AF%2586%25E4%25B9%258B%25E5%2589%258D%25E7%25BE%258E%25E8%258B%25B1%25E6%25BE%25B3%25E4%25B8%258D%25E5%25BA%2594%25E5%25BC%2580%25E5%25B1%2595%25E6%25A0%25B8%25E6%25BD%259C%25E8%2589%2587%25E5%2590%2588%25E4%25BD%259C%26rn%3D10%26un%3D%26only_thread%3D0%26sm%3D1%26sd%3D%26ed%3D%26pn%3D3&timestamp=1654682080&signature=226957534cdee2321ca1e4c994fda626 (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1131)')))
2022-06-08 17:54:50.505 | ERROR    | monitor.searchSpiders.tieba:get_request_from_keyword:34 - E 贴吧错误HTTPSConnectionPool(host='wappass.baidu.com', port=443): Max retries exceeded with url: /static/captcha/tuxing.html?ak=2ef521ec36290baed33d66de9b16f625&backurl=http%3A%2F%2Ftieba.baidu.com%2Ff%2Fsearch%2Fres%3Fisnew%3D1%26kw%3D%26qw%3D%25E9%259D%259E%25E6%25B4%25B2%25E6%259E%2581%25E7%25AB%25AF%25E7%25BB%2584%25E7%25BB%2587%25E6%25AD%25A6%25E5%2599%25A8%25E6%259D%25A5%25E6%25BA%2590%25E5%25BC%2595%25E5%2585%25B3%25E6%25B3%25A8%26rn%3D10%26un%3D%26only_thread%3D0%26sm%3D1%26sd%3D%26ed%3D%26pn%3D2&timestamp=1654682090&signature=5899b00b4dedfcb53461a05d52aafc54 (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1131)')))
Traceback (most recent call last):

  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
                       │    └ <function HTTPConnectionPool._make_request at 0x7fe06b3fed30>
                       └ <urllib3.connectionpool.HTTPSConnectionPool object at 0x7fddd04b7c40>
  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
    │    │              └ <urllib3.connection.HTTPSConnection object at 0x7fdd2eb1e040>
    │    └ <function HTTPSConnectionPool._validate_conn at 0x7fe06b3ff280>
    └ <urllib3.connectionpool.HTTPSConnectionPool object at 0x7fddd04b7c40>
  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
    │    └ <function HTTPSConnection.connect at 0x7fe06b46d940>
    └ <urllib3.connection.HTTPSConnection object at 0x7fdd2eb1e040>
  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/connection.py", line 416, in connect
    self.sock = ssl_wrap_socket(
    │    │      └ <function ssl_wrap_socket at 0x7fe06b468670>
    │    └ None
    └ <urllib3.connection.HTTPSConnection object at 0x7fdd2eb1e040>
  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
               └ <function _ssl_wrap_socket_impl at 0x7fe06b468820>
  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
           │           │           │                     └ 'wappass.baidu.com'
           │           │           └ <socket.socket [closed] fd=-1, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6>
           │           └ <function SSLContext.wrap_socket at 0x7fe08118de50>
           └ <ssl.SSLContext object at 0x7fdf541f36c0>
  File "/usr/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
           │    │               └ <classmethod object at 0x7fe08c8cfaf0>
           │    └ <class 'ssl.SSLSocket'>
           └ <ssl.SSLContext object at 0x7fdf541f36c0>
  File "/usr/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
    │    └ <function SSLSocket.do_handshake at 0x7fe08c8d2d30>
    └ <ssl.SSLSocket [closed] fd=-1, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6>
  File "/usr/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
    │    └ None
    └ <ssl.SSLSocket [closed] fd=-1, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6>

ssl.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1131)


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/home/chase/.local/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
           │    └ <function HTTPConnectionPool.urlopen at 0x7fe06b3fef70>
           └ <urllib3.connectionpool.HTTPSConnectionPool object at 0x7fddd04b7c40>
  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
              │       └ <function Retry.increment at 0x7fe06b443280>
              └ Retry(total=0, connect=None, read=False, redirect=None, status=None)
  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
          │             │      │    │        │             └ 'unknown'
          │             │      │    │        └ <class 'urllib3.exceptions.ResponseError'>
          │             │      │    └ SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1131)'))
          │             │      └ '/static/captcha/tuxing.html?ak=2ef521ec36290baed33d66de9b16f625&backurl=http%3A%2F%2Ftieba.baidu.com%2Ff%2Fsearch%2Fres%3Fis...
          │             └ <urllib3.connectionpool.HTTPSConnectionPool object at 0x7fddd04b7c40>
          └ <class 'urllib3.exceptions.MaxRetryError'>

urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='wappass.baidu.com', port=443): Max retries exceeded with url: /static/captcha/tuxing.html?ak=2ef521ec36290baed33d66de9b16f625&backurl=http%3A%2F%2Ftieba.baidu.com%2Ff%2Fsearch%2Fres%3Fisnew%3D1%26kw%3D%26qw%3D%25E9%259D%259E%25E6%25B4%25B2%25E6%259E%2581%25E7%25AB%25AF%25E7%25BB%2584%25E7%25BB%2587%25E6%25AD%25A6%25E5%2599%25A8%25E6%259D%25A5%25E6%25BA%2590%25E5%25BC%2595%25E5%2585%25B3%25E6%25B3%25A8%26rn%3D10%26un%3D%26only_thread%3D0%26sm%3D1%26sd%3D%26ed%3D%26pn%3D2&timestamp=1654682090&signature=5899b00b4dedfcb53461a05d52aafc54 (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1131)')))


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/usr/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7fe08f92ea60>
    └ <Thread(Thread-31230, started daemon 140590385100544)>
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7fe08f92e790>
    └ <Thread(Thread-31230, started daemon 140590385100544)>
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-31230, started daemon 140590385100544)>
    │    │        │    └ ('ProjectManager.run_func_by_thread',)
    │    │        └ <Thread(Thread-31230, started daemon 140590385100544)>
    │    └ <bound method ProjectManager.get_request_from_keywords_hot of <monitor.projectManager.ProjectManager object at 0x7fe063c65790>>
    └ <Thread(Thread-31230, started daemon 140590385100544)>

  File "/home/users/Scy/yuqing/spider/monitor/projectManager.py", line 833, in get_request_from_keywords_hot
    self.search_spider_manager.crawl_by_keyword(
    │    │                     └ <function SearchSpidersManager.crawl_by_keyword at 0x7fe063c71160>
    │    └ <monitor.spiderManager.SearchSpidersManager object at 0x7fe0638938b0>
    └ <monitor.projectManager.ProjectManager object at 0x7fe063c65790>

  File "/home/users/Scy/yuqing/spider/monitor/spiderManager.py", line 118, in crawl_by_keyword
    self.crawl_by_keyword_signal_platform(project_names, platform, keyword, crawl_time, project_times)
    │    │                                │              │         │        │           └ {'default': <monitor.TimeSection object at 0x7fe0639a2b80>}
    │    │                                │              │         │        └ <monitor.TimeSection object at 0x7fdd0e70e070>
    │    │                                │              │         └ '非洲极端组织武器来源引关注'
    │    │                                │              └ '贴吧'
    │    │                                └ ['default']
    │    └ <function SearchSpidersManager.crawl_by_keyword_signal_platform at 0x7fe063c71280>
    └ <monitor.spiderManager.SearchSpidersManager object at 0x7fe0638938b0>

  File "/home/users/Scy/yuqing/spider/monitor/spiderManager.py", line 150, in crawl_by_keyword_signal_platform
    requests = self.get_request_from_keyword(platform, keyword_only, **crawl_time.to_dict())
               │    │                        │         │               │          └ <function TimeSection.to_dict at 0x7fe06b8931f0>
               │    │                        │         │               └ <monitor.TimeSection object at 0x7fdd0e70e070>
               │    │                        │         └ '非洲极端组织武器来源引关注'
               │    │                        └ '贴吧'
               │    └ <function SearchSpidersManager.get_request_from_keyword at 0x7fe063c713a0>
               └ <monitor.spiderManager.SearchSpidersManager object at 0x7fe0638938b0>

  File "/home/users/Scy/yuqing/spider/monitor/spiderManager.py", line 214, in get_request_from_keyword
    for request in self.spiders[platform].get_request_from_keyword(headers, search_url, keyword, content_url,
                   │    │       │                                  │        │           │        └ None
                   │    │       │                                  │        │           └ '非洲极端组织武器来源引关注'
                   │    │       │                                  │        └ <string.Template object at 0x7fe0605f4910>
                   │    │       │                                  └ {'Connection': 'keep-alive', 'sec-ch-ua': "'Chromium';v='92',' Not A;Brand';v='99', 'Google Chrome';v='92'", 'sec-ch-ua-mobil...
                   │    │       └ '贴吧'
                   │    └ {'凤凰网': <monitor.searchSpiders.ifeng.Ifeng object at 0x7fe063893370>, '头条': <monitor.searchSpiders.toutiao.Toutiao object at ...
                   └ <monitor.spiderManager.SearchSpidersManager object at 0x7fe0638938b0>

> File "/home/users/Scy/yuqing/spider/monitor/searchSpiders/tieba.py", line 22, in get_request_from_keyword
    response = requests.get(url, headers=headers, timeout=50)
               │        │   │            └ {'Connection': 'keep-alive', 'sec-ch-ua': "'Chromium';v='92',' Not A;Brand';v='99', 'Google Chrome';v='92'", 'sec-ch-ua-mobil...
               │        │   └ 'https://tieba.baidu.com/f/search/res?isnew=1&kw=&qw=非洲极端组织武器来源引关注&rn=10&un=&only_thread=0&sm=1&sd=&ed=&pn=2'
               │        └ <function get at 0x7fe06b2724c0>
               └ <module 'requests' from '/home/chase/.local/lib/python3.8/site-packages/requests/__init__.py'>

  File "/home/chase/.local/lib/python3.8/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
           │              │           │         └ {'headers': {'Connection': 'keep-alive', 'sec-ch-ua': "'Chromium';v='92',' Not A;Brand';v='99', 'Google Chrome';v='92'", 'sec...
           │              │           └ None
           │              └ 'https://tieba.baidu.com/f/search/res?isnew=1&kw=&qw=非洲极端组织武器来源引关注&rn=10&un=&only_thread=0&sm=1&sd=&ed=&pn=2'
           └ <function request at 0x7fe06b268310>
  File "/home/chase/.local/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
           │       │              │           │      └ {'params': None, 'headers': {'Connection': 'keep-alive', 'sec-ch-ua': "'Chromium';v='92',' Not A;Brand';v='99', 'Google Chrom...
           │       │              │           └ 'https://tieba.baidu.com/f/search/res?isnew=1&kw=&qw=非洲极端组织武器来源引关注&rn=10&un=&only_thread=0&sm=1&sd=&ed=&pn=2'
           │       │              └ 'get'
           │       └ <function Session.request at 0x7fe06b27bc10>
           └ <requests.sessions.Session object at 0x7fdda2528eb0>
  File "/home/chase/.local/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
           │    │    │       └ {'timeout': 50, 'allow_redirects': True, 'verify': True, 'proxies': OrderedDict(), 'stream': False, 'cert': None}
           │    │    └ <PreparedRequest [GET]>
           │    └ <function Session.send at 0x7fe06b2720d0>
           └ <requests.sessions.Session object at 0x7fdda2528eb0>
  File "/home/chase/.local/lib/python3.8/site-packages/requests/sessions.py", line 677, in send
    history = [resp for resp in gen]
                                └ <generator object SessionRedirectMixin.resolve_redirects at 0x7fdf10620820>
  File "/home/chase/.local/lib/python3.8/site-packages/requests/sessions.py", line 677, in <listcomp>
    history = [resp for resp in gen]
  File "/home/chase/.local/lib/python3.8/site-packages/requests/sessions.py", line 237, in resolve_redirects
    resp = self.send(
           │    └ <function Session.send at 0x7fe06b2720d0>
           └ <requests.sessions.Session object at 0x7fdda2528eb0>
  File "/home/chase/.local/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
        │       │    │          └ {'stream': False, 'timeout': 50, 'verify': True, 'cert': None, 'proxies': OrderedDict()}
        │       │    └ <PreparedRequest [GET]>
        │       └ <function HTTPAdapter.send at 0x7fe06b27b550>
        └ <requests.adapters.HTTPAdapter object at 0x7fded016e760>
  File "/home/chase/.local/lib/python3.8/site-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
          │                   └ <PreparedRequest [GET]>
          └ <class 'requests.exceptions.SSLError'>

requests.exceptions.SSLError: HTTPSConnectionPool(host='wappass.baidu.com', port=443): Max retries exceeded with url: /static/captcha/tuxing.html?ak=2ef521ec36290baed33d66de9b16f625&backurl=http%3A%2F%2Ftieba.baidu.com%2Ff%2Fsearch%2Fres%3Fisnew%3D1%26kw%3D%26qw%3D%25E9%259D%259E%25E6%25B4%25B2%25E6%259E%2581%25E7%25AB%25AF%25E7%25BB%2584%25E7%25BB%2587%25E6%25AD%25A6%25E5%2599%25A8%25E6%259D%25A5%25E6%25BA%2590%25E5%25BC%2595%25E5%2585%25B3%25E6%25B3%25A8%26rn%3D10%26un%3D%26only_thread%3D0%26sm%3D1%26sd%3D%26ed%3D%26pn%3D2&timestamp=1654682090&signature=5899b00b4dedfcb53461a05d52aafc54 (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1131)')))
2022-06-08 17:55:30.799 | ERROR    | monitor.searchSpiders.tieba:get_request_from_keyword:34 - E 贴吧错误HTTPSConnectionPool(host='wappass.baidu.com', port=443): Max retries exceeded with url: /static/captcha/tuxing.html?ak=2ef521ec36290baed33d66de9b16f625&backurl=http%3A%2F%2Ftieba.baidu.com%2Ff%2Fsearch%2Fres%3Fisnew%3D1%26kw%3D%26qw%3D%25E5%25AE%2589%25E5%25BE%25BD%25E7%259C%2581%25E5%2586%259B%25E5%258C%25BA%25E5%258A%25A0%25E5%25BC%25BA%25E4%25BB%25A5%25E9%259D%2592%25E5%25B9%25B4%25E4%25B8%25BA%25E4%25B8%25BB%25E7%259A%2584%25E6%25B0%2591%25E5%2585%25B5%25E6%2596%25B0%25E8%25B4%25A8%25E5%258A%259B%25E9%2587%258F%25E5%25BB%25BA%25E8%25AE%25BE%26rn%3D10%26un%3D%26only_thread%3D0%26sm%3D1%26sd%3D%26ed%3D%26pn%3D8&timestamp=1654682130&signature=5d783b54ec2e07ed09ee10ddb6de2357 (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1131)')))
Traceback (most recent call last):

  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
                       │    └ <function HTTPConnectionPool._make_request at 0x7fe06b3fed30>
                       └ <urllib3.connectionpool.HTTPSConnectionPool object at 0x7fdcc8992eb0>
  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
    │    │              └ <urllib3.connection.HTTPSConnection object at 0x7fdef06254c0>
    │    └ <function HTTPSConnectionPool._validate_conn at 0x7fe06b3ff280>
    └ <urllib3.connectionpool.HTTPSConnectionPool object at 0x7fdcc8992eb0>
  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
    │    └ <function HTTPSConnection.connect at 0x7fe06b46d940>
    └ <urllib3.connection.HTTPSConnection object at 0x7fdef06254c0>
  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/connection.py", line 416, in connect
    self.sock = ssl_wrap_socket(
    │    │      └ <function ssl_wrap_socket at 0x7fe06b468670>
    │    └ None
    └ <urllib3.connection.HTTPSConnection object at 0x7fdef06254c0>
  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
               └ <function _ssl_wrap_socket_impl at 0x7fe06b468820>
  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
           │           │           │                     └ 'wappass.baidu.com'
           │           │           └ <socket.socket [closed] fd=-1, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6>
           │           └ <function SSLContext.wrap_socket at 0x7fe08118de50>
           └ <ssl.SSLContext object at 0x7fdf54292b40>
  File "/usr/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
           │    │               └ <classmethod object at 0x7fe08c8cfaf0>
           │    └ <class 'ssl.SSLSocket'>
           └ <ssl.SSLContext object at 0x7fdf54292b40>
  File "/usr/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
    │    └ <function SSLSocket.do_handshake at 0x7fe08c8d2d30>
    └ <ssl.SSLSocket [closed] fd=-1, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6>
  File "/usr/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
    │    └ None
    └ <ssl.SSLSocket [closed] fd=-1, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6>

ssl.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1131)


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/home/chase/.local/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
           │    └ <function HTTPConnectionPool.urlopen at 0x7fe06b3fef70>
           └ <urllib3.connectionpool.HTTPSConnectionPool object at 0x7fdcc8992eb0>
  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
              │       └ <function Retry.increment at 0x7fe06b443280>
              └ Retry(total=0, connect=None, read=False, redirect=None, status=None)
  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
          │             │      │    │        │             └ 'unknown'
          │             │      │    │        └ <class 'urllib3.exceptions.ResponseError'>
          │             │      │    └ SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1131)'))
          │             │      └ '/static/captcha/tuxing.html?ak=2ef521ec36290baed33d66de9b16f625&backurl=http%3A%2F%2Ftieba.baidu.com%2Ff%2Fsearch%2Fres%3Fis...
          │             └ <urllib3.connectionpool.HTTPSConnectionPool object at 0x7fdcc8992eb0>
          └ <class 'urllib3.exceptions.MaxRetryError'>

urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='wappass.baidu.com', port=443): Max retries exceeded with url: /static/captcha/tuxing.html?ak=2ef521ec36290baed33d66de9b16f625&backurl=http%3A%2F%2Ftieba.baidu.com%2Ff%2Fsearch%2Fres%3Fisnew%3D1%26kw%3D%26qw%3D%25E5%25AE%2589%25E5%25BE%25BD%25E7%259C%2581%25E5%2586%259B%25E5%258C%25BA%25E5%258A%25A0%25E5%25BC%25BA%25E4%25BB%25A5%25E9%259D%2592%25E5%25B9%25B4%25E4%25B8%25BA%25E4%25B8%25BB%25E7%259A%2584%25E6%25B0%2591%25E5%2585%25B5%25E6%2596%25B0%25E8%25B4%25A8%25E5%258A%259B%25E9%2587%258F%25E5%25BB%25BA%25E8%25AE%25BE%26rn%3D10%26un%3D%26only_thread%3D0%26sm%3D1%26sd%3D%26ed%3D%26pn%3D8&timestamp=1654682130&signature=5d783b54ec2e07ed09ee10ddb6de2357 (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1131)')))


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/usr/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7fe08f92ea60>
    └ <Thread(Thread-32700, started daemon 140586288445184)>
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7fe08f92e790>
    └ <Thread(Thread-32700, started daemon 140586288445184)>
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-32700, started daemon 140586288445184)>
    │    │        │    └ ('ProjectManager.run_func_by_thread',)
    │    │        └ <Thread(Thread-32700, started daemon 140586288445184)>
    │    └ <bound method ProjectManager.get_request_from_keywords_hot of <monitor.projectManager.ProjectManager object at 0x7fe063c65790>>
    └ <Thread(Thread-32700, started daemon 140586288445184)>

  File "/home/users/Scy/yuqing/spider/monitor/projectManager.py", line 833, in get_request_from_keywords_hot
    self.search_spider_manager.crawl_by_keyword(
    │    │                     └ <function SearchSpidersManager.crawl_by_keyword at 0x7fe063c71160>
    │    └ <monitor.spiderManager.SearchSpidersManager object at 0x7fe0638938b0>
    └ <monitor.projectManager.ProjectManager object at 0x7fe063c65790>

  File "/home/users/Scy/yuqing/spider/monitor/spiderManager.py", line 118, in crawl_by_keyword
    self.crawl_by_keyword_signal_platform(project_names, platform, keyword, crawl_time, project_times)
    │    │                                │              │         │        │           └ {'default': <monitor.TimeSection object at 0x7fe0639a2b80>}
    │    │                                │              │         │        └ <monitor.TimeSection object at 0x7fde5039db20>
    │    │                                │              │         └ '安徽省军区加强以青年为主的民兵新质力量建设'
    │    │                                │              └ '贴吧'
    │    │                                └ ['default']
    │    └ <function SearchSpidersManager.crawl_by_keyword_signal_platform at 0x7fe063c71280>
    └ <monitor.spiderManager.SearchSpidersManager object at 0x7fe0638938b0>

  File "/home/users/Scy/yuqing/spider/monitor/spiderManager.py", line 150, in crawl_by_keyword_signal_platform
    requests = self.get_request_from_keyword(platform, keyword_only, **crawl_time.to_dict())
               │    │                        │         │               │          └ <function TimeSection.to_dict at 0x7fe06b8931f0>
               │    │                        │         │               └ <monitor.TimeSection object at 0x7fde5039db20>
               │    │                        │         └ '安徽省军区加强以青年为主的民兵新质力量建设'
               │    │                        └ '贴吧'
               │    └ <function SearchSpidersManager.get_request_from_keyword at 0x7fe063c713a0>
               └ <monitor.spiderManager.SearchSpidersManager object at 0x7fe0638938b0>

  File "/home/users/Scy/yuqing/spider/monitor/spiderManager.py", line 214, in get_request_from_keyword
    for request in self.spiders[platform].get_request_from_keyword(headers, search_url, keyword, content_url,
                   │    │       │                                  │        │           │        └ None
                   │    │       │                                  │        │           └ '安徽省军区加强以青年为主的民兵新质力量建设'
                   │    │       │                                  │        └ <string.Template object at 0x7fdf546be190>
                   │    │       │                                  └ {'Connection': 'keep-alive', 'sec-ch-ua': "'Chromium';v='92',' Not A;Brand';v='99', 'Google Chrome';v='92'", 'sec-ch-ua-mobil...
                   │    │       └ '贴吧'
                   │    └ {'凤凰网': <monitor.searchSpiders.ifeng.Ifeng object at 0x7fe063893370>, '头条': <monitor.searchSpiders.toutiao.Toutiao object at ...
                   └ <monitor.spiderManager.SearchSpidersManager object at 0x7fe0638938b0>

> File "/home/users/Scy/yuqing/spider/monitor/searchSpiders/tieba.py", line 22, in get_request_from_keyword
    response = requests.get(url, headers=headers, timeout=50)
               │        │   │            └ {'Connection': 'keep-alive', 'sec-ch-ua': "'Chromium';v='92',' Not A;Brand';v='99', 'Google Chrome';v='92'", 'sec-ch-ua-mobil...
               │        │   └ 'https://tieba.baidu.com/f/search/res?isnew=1&kw=&qw=安徽省军区加强以青年为主的民兵新质力量建设&rn=10&un=&only_thread=0&sm=1&sd=&ed=&pn=8'
               │        └ <function get at 0x7fe06b2724c0>
               └ <module 'requests' from '/home/chase/.local/lib/python3.8/site-packages/requests/__init__.py'>

  File "/home/chase/.local/lib/python3.8/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
           │              │           │         └ {'headers': {'Connection': 'keep-alive', 'sec-ch-ua': "'Chromium';v='92',' Not A;Brand';v='99', 'Google Chrome';v='92'", 'sec...
           │              │           └ None
           │              └ 'https://tieba.baidu.com/f/search/res?isnew=1&kw=&qw=安徽省军区加强以青年为主的民兵新质力量建设&rn=10&un=&only_thread=0&sm=1&sd=&ed=&pn=8'
           └ <function request at 0x7fe06b268310>
  File "/home/chase/.local/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
           │       │              │           │      └ {'params': None, 'headers': {'Connection': 'keep-alive', 'sec-ch-ua': "'Chromium';v='92',' Not A;Brand';v='99', 'Google Chrom...
           │       │              │           └ 'https://tieba.baidu.com/f/search/res?isnew=1&kw=&qw=安徽省军区加强以青年为主的民兵新质力量建设&rn=10&un=&only_thread=0&sm=1&sd=&ed=&pn=8'
           │       │              └ 'get'
           │       └ <function Session.request at 0x7fe06b27bc10>
           └ <requests.sessions.Session object at 0x7fdd2b063970>
  File "/home/chase/.local/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
           │    │    │       └ {'timeout': 50, 'allow_redirects': True, 'verify': True, 'proxies': OrderedDict(), 'stream': False, 'cert': None}
           │    │    └ <PreparedRequest [GET]>
           │    └ <function Session.send at 0x7fe06b2720d0>
           └ <requests.sessions.Session object at 0x7fdd2b063970>
  File "/home/chase/.local/lib/python3.8/site-packages/requests/sessions.py", line 677, in send
    history = [resp for resp in gen]
                                └ <generator object SessionRedirectMixin.resolve_redirects at 0x7fddd00ecba0>
  File "/home/chase/.local/lib/python3.8/site-packages/requests/sessions.py", line 677, in <listcomp>
    history = [resp for resp in gen]
  File "/home/chase/.local/lib/python3.8/site-packages/requests/sessions.py", line 237, in resolve_redirects
    resp = self.send(
           │    └ <function Session.send at 0x7fe06b2720d0>
           └ <requests.sessions.Session object at 0x7fdd2b063970>
  File "/home/chase/.local/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
        │       │    │          └ {'stream': False, 'timeout': 50, 'verify': True, 'cert': None, 'proxies': OrderedDict()}
        │       │    └ <PreparedRequest [GET]>
        │       └ <function HTTPAdapter.send at 0x7fe06b27b550>
        └ <requests.adapters.HTTPAdapter object at 0x7fdd1eb0bf70>
  File "/home/chase/.local/lib/python3.8/site-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
          │                   └ <PreparedRequest [GET]>
          └ <class 'requests.exceptions.SSLError'>

requests.exceptions.SSLError: HTTPSConnectionPool(host='wappass.baidu.com', port=443): Max retries exceeded with url: /static/captcha/tuxing.html?ak=2ef521ec36290baed33d66de9b16f625&backurl=http%3A%2F%2Ftieba.baidu.com%2Ff%2Fsearch%2Fres%3Fisnew%3D1%26kw%3D%26qw%3D%25E5%25AE%2589%25E5%25BE%25BD%25E7%259C%2581%25E5%2586%259B%25E5%258C%25BA%25E5%258A%25A0%25E5%25BC%25BA%25E4%25BB%25A5%25E9%259D%2592%25E5%25B9%25B4%25E4%25B8%25BA%25E4%25B8%25BB%25E7%259A%2584%25E6%25B0%2591%25E5%2585%25B5%25E6%2596%25B0%25E8%25B4%25A8%25E5%258A%259B%25E9%2587%258F%25E5%25BB%25BA%25E8%25AE%25BE%26rn%3D10%26un%3D%26only_thread%3D0%26sm%3D1%26sd%3D%26ed%3D%26pn%3D8&timestamp=1654682130&signature=5d783b54ec2e07ed09ee10ddb6de2357 (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1131)')))
2022-06-08 17:56:50.598 | ERROR    | monitor.searchSpiders.tieba:get_request_from_keyword:34 - E 贴吧错误HTTPSConnectionPool(host='wappass.baidu.com', port=443): Max retries exceeded with url: /static/captcha/tuxing.html?ak=2ef521ec36290baed33d66de9b16f625&backurl=http%3A%2F%2Ftieba.baidu.com%2Ff%2Fsearch%2Fres%3Fisnew%3D1%26kw%3D%26qw%3D%25E6%2597%25A5%25E6%259C%25AC%25E5%2585%25B3%25E4%25B8%259C%25E7%2594%25B2%25E4%25BF%25A1%25E5%259C%25B0%25E5%258C%25BA%25E8%25BF%259B%25E5%2585%25A5%25E6%25A2%2585%25E9%259B%25A8%25E5%25AD%25A3%25E8%258A%2582%2520%25E6%25AF%2594%25E5%258E%25BB%25E5%25B9%25B4%25E6%258F%2590%25E5%2589%258D8%25E5%25A4%25A9%26rn%3D10%26un%3D%26only_thread%3D0%26sm%3D1%26sd%3D%26ed%3D%26pn%3D12&timestamp=1654682210&signature=ae7192137d4928ba055e8cecb0ad0f33 (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1131)')))
Traceback (most recent call last):

  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
                       │    └ <function HTTPConnectionPool._make_request at 0x7fe06b3fed30>
                       └ <urllib3.connectionpool.HTTPSConnectionPool object at 0x7fdf1037d490>
  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
    │    │              └ <urllib3.connection.HTTPSConnection object at 0x7fdf3052a250>
    │    └ <function HTTPSConnectionPool._validate_conn at 0x7fe06b3ff280>
    └ <urllib3.connectionpool.HTTPSConnectionPool object at 0x7fdf1037d490>
  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
    │    └ <function HTTPSConnection.connect at 0x7fe06b46d940>
    └ <urllib3.connection.HTTPSConnection object at 0x7fdf3052a250>
  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/connection.py", line 416, in connect
    self.sock = ssl_wrap_socket(
    │    │      └ <function ssl_wrap_socket at 0x7fe06b468670>
    │    └ None
    └ <urllib3.connection.HTTPSConnection object at 0x7fdf3052a250>
  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
               └ <function _ssl_wrap_socket_impl at 0x7fe06b468820>
  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
           │           │           │                     └ 'wappass.baidu.com'
           │           │           └ <socket.socket [closed] fd=-1, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6>
           │           └ <function SSLContext.wrap_socket at 0x7fe08118de50>
           └ <ssl.SSLContext object at 0x7fdda20a8740>
  File "/usr/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
           │    │               └ <classmethod object at 0x7fe08c8cfaf0>
           │    └ <class 'ssl.SSLSocket'>
           └ <ssl.SSLContext object at 0x7fdda20a8740>
  File "/usr/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
    │    └ <function SSLSocket.do_handshake at 0x7fe08c8d2d30>
    └ <ssl.SSLSocket [closed] fd=-1, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6>
  File "/usr/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
    │    └ None
    └ <ssl.SSLSocket [closed] fd=-1, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6>

ssl.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1131)


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/home/chase/.local/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
           │    └ <function HTTPConnectionPool.urlopen at 0x7fe06b3fef70>
           └ <urllib3.connectionpool.HTTPSConnectionPool object at 0x7fdf1037d490>
  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
              │       └ <function Retry.increment at 0x7fe06b443280>
              └ Retry(total=0, connect=None, read=False, redirect=None, status=None)
  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
          │             │      │    │        │             └ 'unknown'
          │             │      │    │        └ <class 'urllib3.exceptions.ResponseError'>
          │             │      │    └ SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1131)'))
          │             │      └ '/static/captcha/tuxing.html?ak=2ef521ec36290baed33d66de9b16f625&backurl=http%3A%2F%2Ftieba.baidu.com%2Ff%2Fsearch%2Fres%3Fis...
          │             └ <urllib3.connectionpool.HTTPSConnectionPool object at 0x7fdf1037d490>
          └ <class 'urllib3.exceptions.MaxRetryError'>

urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='wappass.baidu.com', port=443): Max retries exceeded with url: /static/captcha/tuxing.html?ak=2ef521ec36290baed33d66de9b16f625&backurl=http%3A%2F%2Ftieba.baidu.com%2Ff%2Fsearch%2Fres%3Fisnew%3D1%26kw%3D%26qw%3D%25E6%2597%25A5%25E6%259C%25AC%25E5%2585%25B3%25E4%25B8%259C%25E7%2594%25B2%25E4%25BF%25A1%25E5%259C%25B0%25E5%258C%25BA%25E8%25BF%259B%25E5%2585%25A5%25E6%25A2%2585%25E9%259B%25A8%25E5%25AD%25A3%25E8%258A%2582%2520%25E6%25AF%2594%25E5%258E%25BB%25E5%25B9%25B4%25E6%258F%2590%25E5%2589%258D8%25E5%25A4%25A9%26rn%3D10%26un%3D%26only_thread%3D0%26sm%3D1%26sd%3D%26ed%3D%26pn%3D12&timestamp=1654682210&signature=ae7192137d4928ba055e8cecb0ad0f33 (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1131)')))


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/usr/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7fe08f92ea60>
    └ <Thread(Thread-31896, started daemon 140590142236416)>
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7fe08f92e790>
    └ <Thread(Thread-31896, started daemon 140590142236416)>
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-31896, started daemon 140590142236416)>
    │    │        │    └ ('ProjectManager.run_func_by_thread',)
    │    │        └ <Thread(Thread-31896, started daemon 140590142236416)>
    │    └ <bound method ProjectManager.get_request_from_keywords_hot of <monitor.projectManager.ProjectManager object at 0x7fe063c65790>>
    └ <Thread(Thread-31896, started daemon 140590142236416)>

  File "/home/users/Scy/yuqing/spider/monitor/projectManager.py", line 833, in get_request_from_keywords_hot
    self.search_spider_manager.crawl_by_keyword(
    │    │                     └ <function SearchSpidersManager.crawl_by_keyword at 0x7fe063c71160>
    │    └ <monitor.spiderManager.SearchSpidersManager object at 0x7fe0638938b0>
    └ <monitor.projectManager.ProjectManager object at 0x7fe063c65790>

  File "/home/users/Scy/yuqing/spider/monitor/spiderManager.py", line 118, in crawl_by_keyword
    self.crawl_by_keyword_signal_platform(project_names, platform, keyword, crawl_time, project_times)
    │    │                                │              │         │        │           └ {'default': <monitor.TimeSection object at 0x7fe0639a2b80>}
    │    │                                │              │         │        └ <monitor.TimeSection object at 0x7fde50dc0df0>
    │    │                                │              │         └ '日本关东甲信地区进入梅雨季节 比去年提前8天'
    │    │                                │              └ '贴吧'
    │    │                                └ ['default']
    │    └ <function SearchSpidersManager.crawl_by_keyword_signal_platform at 0x7fe063c71280>
    └ <monitor.spiderManager.SearchSpidersManager object at 0x7fe0638938b0>

  File "/home/users/Scy/yuqing/spider/monitor/spiderManager.py", line 150, in crawl_by_keyword_signal_platform
    requests = self.get_request_from_keyword(platform, keyword_only, **crawl_time.to_dict())
               │    │                        │         │               │          └ <function TimeSection.to_dict at 0x7fe06b8931f0>
               │    │                        │         │               └ <monitor.TimeSection object at 0x7fde50dc0df0>
               │    │                        │         └ '日本关东甲信地区进入梅雨季节 比去年提前8天'
               │    │                        └ '贴吧'
               │    └ <function SearchSpidersManager.get_request_from_keyword at 0x7fe063c713a0>
               └ <monitor.spiderManager.SearchSpidersManager object at 0x7fe0638938b0>

  File "/home/users/Scy/yuqing/spider/monitor/spiderManager.py", line 214, in get_request_from_keyword
    for request in self.spiders[platform].get_request_from_keyword(headers, search_url, keyword, content_url,
                   │    │       │                                  │        │           │        └ None
                   │    │       │                                  │        │           └ '日本关东甲信地区进入梅雨季节 比去年提前8天'
                   │    │       │                                  │        └ <string.Template object at 0x7fddd034cf40>
                   │    │       │                                  └ {'Connection': 'keep-alive', 'sec-ch-ua': "'Chromium';v='92',' Not A;Brand';v='99', 'Google Chrome';v='92'", 'sec-ch-ua-mobil...
                   │    │       └ '贴吧'
                   │    └ {'凤凰网': <monitor.searchSpiders.ifeng.Ifeng object at 0x7fe063893370>, '头条': <monitor.searchSpiders.toutiao.Toutiao object at ...
                   └ <monitor.spiderManager.SearchSpidersManager object at 0x7fe0638938b0>

> File "/home/users/Scy/yuqing/spider/monitor/searchSpiders/tieba.py", line 22, in get_request_from_keyword
    response = requests.get(url, headers=headers, timeout=50)
               │        │   │            └ {'Connection': 'keep-alive', 'sec-ch-ua': "'Chromium';v='92',' Not A;Brand';v='99', 'Google Chrome';v='92'", 'sec-ch-ua-mobil...
               │        │   └ 'https://tieba.baidu.com/f/search/res?isnew=1&kw=&qw=日本关东甲信地区进入梅雨季节 比去年提前8天&rn=10&un=&only_thread=0&sm=1&sd=&ed=&pn=12'
               │        └ <function get at 0x7fe06b2724c0>
               └ <module 'requests' from '/home/chase/.local/lib/python3.8/site-packages/requests/__init__.py'>

  File "/home/chase/.local/lib/python3.8/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
           │              │           │         └ {'headers': {'Connection': 'keep-alive', 'sec-ch-ua': "'Chromium';v='92',' Not A;Brand';v='99', 'Google Chrome';v='92'", 'sec...
           │              │           └ None
           │              └ 'https://tieba.baidu.com/f/search/res?isnew=1&kw=&qw=日本关东甲信地区进入梅雨季节 比去年提前8天&rn=10&un=&only_thread=0&sm=1&sd=&ed=&pn=12'
           └ <function request at 0x7fe06b268310>
  File "/home/chase/.local/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
           │       │              │           │      └ {'params': None, 'headers': {'Connection': 'keep-alive', 'sec-ch-ua': "'Chromium';v='92',' Not A;Brand';v='99', 'Google Chrom...
           │       │              │           └ 'https://tieba.baidu.com/f/search/res?isnew=1&kw=&qw=日本关东甲信地区进入梅雨季节 比去年提前8天&rn=10&un=&only_thread=0&sm=1&sd=&ed=&pn=12'
           │       │              └ 'get'
           │       └ <function Session.request at 0x7fe06b27bc10>
           └ <requests.sessions.Session object at 0x7fddd038adf0>
  File "/home/chase/.local/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
           │    │    │       └ {'timeout': 50, 'allow_redirects': True, 'verify': True, 'proxies': OrderedDict(), 'stream': False, 'cert': None}
           │    │    └ <PreparedRequest [GET]>
           │    └ <function Session.send at 0x7fe06b2720d0>
           └ <requests.sessions.Session object at 0x7fddd038adf0>
  File "/home/chase/.local/lib/python3.8/site-packages/requests/sessions.py", line 677, in send
    history = [resp for resp in gen]
                                └ <generator object SessionRedirectMixin.resolve_redirects at 0x7fdd3e8bbe40>
  File "/home/chase/.local/lib/python3.8/site-packages/requests/sessions.py", line 677, in <listcomp>
    history = [resp for resp in gen]
  File "/home/chase/.local/lib/python3.8/site-packages/requests/sessions.py", line 237, in resolve_redirects
    resp = self.send(
           │    └ <function Session.send at 0x7fe06b2720d0>
           └ <requests.sessions.Session object at 0x7fddd038adf0>
  File "/home/chase/.local/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
        │       │    │          └ {'stream': False, 'timeout': 50, 'verify': True, 'cert': None, 'proxies': OrderedDict()}
        │       │    └ <PreparedRequest [GET]>
        │       └ <function HTTPAdapter.send at 0x7fe06b27b550>
        └ <requests.adapters.HTTPAdapter object at 0x7fdef071e280>
  File "/home/chase/.local/lib/python3.8/site-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
          │                   └ <PreparedRequest [GET]>
          └ <class 'requests.exceptions.SSLError'>

requests.exceptions.SSLError: HTTPSConnectionPool(host='wappass.baidu.com', port=443): Max retries exceeded with url: /static/captcha/tuxing.html?ak=2ef521ec36290baed33d66de9b16f625&backurl=http%3A%2F%2Ftieba.baidu.com%2Ff%2Fsearch%2Fres%3Fisnew%3D1%26kw%3D%26qw%3D%25E6%2597%25A5%25E6%259C%25AC%25E5%2585%25B3%25E4%25B8%259C%25E7%2594%25B2%25E4%25BF%25A1%25E5%259C%25B0%25E5%258C%25BA%25E8%25BF%259B%25E5%2585%25A5%25E6%25A2%2585%25E9%259B%25A8%25E5%25AD%25A3%25E8%258A%2582%2520%25E6%25AF%2594%25E5%258E%25BB%25E5%25B9%25B4%25E6%258F%2590%25E5%2589%258D8%25E5%25A4%25A9%26rn%3D10%26un%3D%26only_thread%3D0%26sm%3D1%26sd%3D%26ed%3D%26pn%3D12&timestamp=1654682210&signature=ae7192137d4928ba055e8cecb0ad0f33 (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1131)')))
2022-06-08 18:01:30.472 | ERROR    | monitor.searchSpiders.tieba:get_request_from_keyword:34 - E 贴吧错误HTTPSConnectionPool(host='wappass.baidu.com', port=443): Max retries exceeded with url: /static/captcha/tuxing.html?ak=2ef521ec36290baed33d66de9b16f625&backurl=http%3A%2F%2Ftieba.baidu.com%2Ff%2Fsearch%2Fres%3Fisnew%3D1%26kw%3D%26qw%3D%25E6%2585%2595%25E5%25B0%25BC%25E9%25BB%2591%25E7%258E%25AF%25E5%258D%259A%25E4%25BC%259A%25E8%2581%259A%25E7%2584%25A6%25E7%258E%25AF%25E4%25BF%259D%25E6%2596%25B0%25E6%258A%2580%25E6%259C%25AF%26rn%3D10%26un%3D%26only_thread%3D0%26sm%3D1%26sd%3D%26ed%3D%26pn%3D19&timestamp=1654682490&signature=daba72fb9577d22d823e15f424d19ead (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1131)')))
Traceback (most recent call last):

  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
                       │    └ <function HTTPConnectionPool._make_request at 0x7fe06b3fed30>
                       └ <urllib3.connectionpool.HTTPSConnectionPool object at 0x7fded05c09a0>
  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
    │    │              └ <urllib3.connection.HTTPSConnection object at 0x7fdf540ac280>
    │    └ <function HTTPSConnectionPool._validate_conn at 0x7fe06b3ff280>
    └ <urllib3.connectionpool.HTTPSConnectionPool object at 0x7fded05c09a0>
  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
    │    └ <function HTTPSConnection.connect at 0x7fe06b46d940>
    └ <urllib3.connection.HTTPSConnection object at 0x7fdf540ac280>
  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/connection.py", line 416, in connect
    self.sock = ssl_wrap_socket(
    │    │      └ <function ssl_wrap_socket at 0x7fe06b468670>
    │    └ None
    └ <urllib3.connection.HTTPSConnection object at 0x7fdf540ac280>
  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
               └ <function _ssl_wrap_socket_impl at 0x7fe06b468820>
  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
           │           │           │                     └ 'wappass.baidu.com'
           │           │           └ <socket.socket [closed] fd=-1, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6>
           │           └ <function SSLContext.wrap_socket at 0x7fe08118de50>
           └ <ssl.SSLContext object at 0x7fdef01fa9c0>
  File "/usr/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
           │    │               └ <classmethod object at 0x7fe08c8cfaf0>
           │    └ <class 'ssl.SSLSocket'>
           └ <ssl.SSLContext object at 0x7fdef01fa9c0>
  File "/usr/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
    │    └ <function SSLSocket.do_handshake at 0x7fe08c8d2d30>
    └ <ssl.SSLSocket [closed] fd=-1, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6>
  File "/usr/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
    │    └ None
    └ <ssl.SSLSocket [closed] fd=-1, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6>

ssl.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1131)


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/home/chase/.local/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
           │    └ <function HTTPConnectionPool.urlopen at 0x7fe06b3fef70>
           └ <urllib3.connectionpool.HTTPSConnectionPool object at 0x7fded05c09a0>
  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
              │       └ <function Retry.increment at 0x7fe06b443280>
              └ Retry(total=0, connect=None, read=False, redirect=None, status=None)
  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
          │             │      │    │        │             └ 'unknown'
          │             │      │    │        └ <class 'urllib3.exceptions.ResponseError'>
          │             │      │    └ SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1131)'))
          │             │      └ '/static/captcha/tuxing.html?ak=2ef521ec36290baed33d66de9b16f625&backurl=http%3A%2F%2Ftieba.baidu.com%2Ff%2Fsearch%2Fres%3Fis...
          │             └ <urllib3.connectionpool.HTTPSConnectionPool object at 0x7fded05c09a0>
          └ <class 'urllib3.exceptions.MaxRetryError'>

urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='wappass.baidu.com', port=443): Max retries exceeded with url: /static/captcha/tuxing.html?ak=2ef521ec36290baed33d66de9b16f625&backurl=http%3A%2F%2Ftieba.baidu.com%2Ff%2Fsearch%2Fres%3Fisnew%3D1%26kw%3D%26qw%3D%25E6%2585%2595%25E5%25B0%25BC%25E9%25BB%2591%25E7%258E%25AF%25E5%258D%259A%25E4%25BC%259A%25E8%2581%259A%25E7%2584%25A6%25E7%258E%25AF%25E4%25BF%259D%25E6%2596%25B0%25E6%258A%2580%25E6%259C%25AF%26rn%3D10%26un%3D%26only_thread%3D0%26sm%3D1%26sd%3D%26ed%3D%26pn%3D19&timestamp=1654682490&signature=daba72fb9577d22d823e15f424d19ead (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1131)')))


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/usr/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7fe08f92ea60>
    └ <Thread(Thread-32967, started daemon 140588480481024)>
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7fe08f92e790>
    └ <Thread(Thread-32967, started daemon 140588480481024)>
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-32967, started daemon 140588480481024)>
    │    │        │    └ ('ProjectManager.run_func_by_thread',)
    │    │        └ <Thread(Thread-32967, started daemon 140588480481024)>
    │    └ <bound method ProjectManager.get_request_from_keywords_hot of <monitor.projectManager.ProjectManager object at 0x7fe063c65790>>
    └ <Thread(Thread-32967, started daemon 140588480481024)>

  File "/home/users/Scy/yuqing/spider/monitor/projectManager.py", line 833, in get_request_from_keywords_hot
    self.search_spider_manager.crawl_by_keyword(
    │    │                     └ <function SearchSpidersManager.crawl_by_keyword at 0x7fe063c71160>
    │    └ <monitor.spiderManager.SearchSpidersManager object at 0x7fe0638938b0>
    └ <monitor.projectManager.ProjectManager object at 0x7fe063c65790>

  File "/home/users/Scy/yuqing/spider/monitor/spiderManager.py", line 118, in crawl_by_keyword
    self.crawl_by_keyword_signal_platform(project_names, platform, keyword, crawl_time, project_times)
    │    │                                │              │         │        │           └ {'default': <monitor.TimeSection object at 0x7fe0639a2b80>}
    │    │                                │              │         │        └ <monitor.TimeSection object at 0x7fdf54101190>
    │    │                                │              │         └ '慕尼黑环博会聚焦环保新技术'
    │    │                                │              └ '贴吧'
    │    │                                └ ['default']
    │    └ <function SearchSpidersManager.crawl_by_keyword_signal_platform at 0x7fe063c71280>
    └ <monitor.spiderManager.SearchSpidersManager object at 0x7fe0638938b0>

  File "/home/users/Scy/yuqing/spider/monitor/spiderManager.py", line 150, in crawl_by_keyword_signal_platform
    requests = self.get_request_from_keyword(platform, keyword_only, **crawl_time.to_dict())
               │    │                        │         │               │          └ <function TimeSection.to_dict at 0x7fe06b8931f0>
               │    │                        │         │               └ <monitor.TimeSection object at 0x7fdf54101190>
               │    │                        │         └ '慕尼黑环博会聚焦环保新技术'
               │    │                        └ '贴吧'
               │    └ <function SearchSpidersManager.get_request_from_keyword at 0x7fe063c713a0>
               └ <monitor.spiderManager.SearchSpidersManager object at 0x7fe0638938b0>

  File "/home/users/Scy/yuqing/spider/monitor/spiderManager.py", line 214, in get_request_from_keyword
    for request in self.spiders[platform].get_request_from_keyword(headers, search_url, keyword, content_url,
                   │    │       │                                  │        │           │        └ None
                   │    │       │                                  │        │           └ '慕尼黑环博会聚焦环保新技术'
                   │    │       │                                  │        └ <string.Template object at 0x7fde50b476a0>
                   │    │       │                                  └ {'Connection': 'keep-alive', 'sec-ch-ua': "'Chromium';v='92',' Not A;Brand';v='99', 'Google Chrome';v='92'", 'sec-ch-ua-mobil...
                   │    │       └ '贴吧'
                   │    └ {'凤凰网': <monitor.searchSpiders.ifeng.Ifeng object at 0x7fe063893370>, '头条': <monitor.searchSpiders.toutiao.Toutiao object at ...
                   └ <monitor.spiderManager.SearchSpidersManager object at 0x7fe0638938b0>

> File "/home/users/Scy/yuqing/spider/monitor/searchSpiders/tieba.py", line 22, in get_request_from_keyword
    response = requests.get(url, headers=headers, timeout=50)
               │        │   │            └ {'Connection': 'keep-alive', 'sec-ch-ua': "'Chromium';v='92',' Not A;Brand';v='99', 'Google Chrome';v='92'", 'sec-ch-ua-mobil...
               │        │   └ 'https://tieba.baidu.com/f/search/res?isnew=1&kw=&qw=慕尼黑环博会聚焦环保新技术&rn=10&un=&only_thread=0&sm=1&sd=&ed=&pn=19'
               │        └ <function get at 0x7fe06b2724c0>
               └ <module 'requests' from '/home/chase/.local/lib/python3.8/site-packages/requests/__init__.py'>

  File "/home/chase/.local/lib/python3.8/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
           │              │           │         └ {'headers': {'Connection': 'keep-alive', 'sec-ch-ua': "'Chromium';v='92',' Not A;Brand';v='99', 'Google Chrome';v='92'", 'sec...
           │              │           └ None
           │              └ 'https://tieba.baidu.com/f/search/res?isnew=1&kw=&qw=慕尼黑环博会聚焦环保新技术&rn=10&un=&only_thread=0&sm=1&sd=&ed=&pn=19'
           └ <function request at 0x7fe06b268310>
  File "/home/chase/.local/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
           │       │              │           │      └ {'params': None, 'headers': {'Connection': 'keep-alive', 'sec-ch-ua': "'Chromium';v='92',' Not A;Brand';v='99', 'Google Chrom...
           │       │              │           └ 'https://tieba.baidu.com/f/search/res?isnew=1&kw=&qw=慕尼黑环博会聚焦环保新技术&rn=10&un=&only_thread=0&sm=1&sd=&ed=&pn=19'
           │       │              └ 'get'
           │       └ <function Session.request at 0x7fe06b27bc10>
           └ <requests.sessions.Session object at 0x7fddd0292520>
  File "/home/chase/.local/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
           │    │    │       └ {'timeout': 50, 'allow_redirects': True, 'verify': True, 'proxies': OrderedDict(), 'stream': False, 'cert': None}
           │    │    └ <PreparedRequest [GET]>
           │    └ <function Session.send at 0x7fe06b2720d0>
           └ <requests.sessions.Session object at 0x7fddd0292520>
  File "/home/chase/.local/lib/python3.8/site-packages/requests/sessions.py", line 677, in send
    history = [resp for resp in gen]
                                └ <generator object SessionRedirectMixin.resolve_redirects at 0x7fdd3bb8acf0>
  File "/home/chase/.local/lib/python3.8/site-packages/requests/sessions.py", line 677, in <listcomp>
    history = [resp for resp in gen]
  File "/home/chase/.local/lib/python3.8/site-packages/requests/sessions.py", line 237, in resolve_redirects
    resp = self.send(
           │    └ <function Session.send at 0x7fe06b2720d0>
           └ <requests.sessions.Session object at 0x7fddd0292520>
  File "/home/chase/.local/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
        │       │    │          └ {'stream': False, 'timeout': 50, 'verify': True, 'cert': None, 'proxies': OrderedDict()}
        │       │    └ <PreparedRequest [GET]>
        │       └ <function HTTPAdapter.send at 0x7fe06b27b550>
        └ <requests.adapters.HTTPAdapter object at 0x7fde105b6eb0>
  File "/home/chase/.local/lib/python3.8/site-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
          │                   └ <PreparedRequest [GET]>
          └ <class 'requests.exceptions.SSLError'>

requests.exceptions.SSLError: HTTPSConnectionPool(host='wappass.baidu.com', port=443): Max retries exceeded with url: /static/captcha/tuxing.html?ak=2ef521ec36290baed33d66de9b16f625&backurl=http%3A%2F%2Ftieba.baidu.com%2Ff%2Fsearch%2Fres%3Fisnew%3D1%26kw%3D%26qw%3D%25E6%2585%2595%25E5%25B0%25BC%25E9%25BB%2591%25E7%258E%25AF%25E5%258D%259A%25E4%25BC%259A%25E8%2581%259A%25E7%2584%25A6%25E7%258E%25AF%25E4%25BF%259D%25E6%2596%25B0%25E6%258A%2580%25E6%259C%25AF%26rn%3D10%26un%3D%26only_thread%3D0%26sm%3D1%26sd%3D%26ed%3D%26pn%3D19&timestamp=1654682490&signature=daba72fb9577d22d823e15f424d19ead (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1131)')))
2022-06-08 18:07:50.611 | ERROR    | monitor.searchSpiders.tieba:get_request_from_keyword:34 - E 贴吧错误HTTPSConnectionPool(host='wappass.baidu.com', port=443): Max retries exceeded with url: /static/captcha/tuxing.html?ak=2ef521ec36290baed33d66de9b16f625&backurl=http%3A%2F%2Ftieba.baidu.com%2Ff%2Fsearch%2Fres%3Fisnew%3D1%26kw%3D%26qw%3D%25E4%25B8%25AD%25E4%25BC%2581%25E5%258A%25A9%25E5%258A%259B%25E6%25B3%25B0%25E5%259B%25BD%25E6%2591%25A9%25E6%2589%2598%25E8%25BD%25A6%25E7%2594%25B5%25E6%25B0%2594%25E5%258C%2596%25E8%25BD%25AC%25E5%259E%258B%26rn%3D10%26un%3D%26only_thread%3D0%26sm%3D1%26sd%3D%26ed%3D%26pn%3D25&timestamp=1654682870&signature=7243e8e3678a50a6d2c751db121145cc (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1131)')))
Traceback (most recent call last):

  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
                       │    └ <function HTTPConnectionPool._make_request at 0x7fe06b3fed30>
                       └ <urllib3.connectionpool.HTTPSConnectionPool object at 0x7fdf541376a0>
  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
    │    │              └ <urllib3.connection.HTTPSConnection object at 0x7fe060689160>
    │    └ <function HTTPSConnectionPool._validate_conn at 0x7fe06b3ff280>
    └ <urllib3.connectionpool.HTTPSConnectionPool object at 0x7fdf541376a0>
  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
    │    └ <function HTTPSConnection.connect at 0x7fe06b46d940>
    └ <urllib3.connection.HTTPSConnection object at 0x7fe060689160>
  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/connection.py", line 416, in connect
    self.sock = ssl_wrap_socket(
    │    │      └ <function ssl_wrap_socket at 0x7fe06b468670>
    │    └ None
    └ <urllib3.connection.HTTPSConnection object at 0x7fe060689160>
  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
               └ <function _ssl_wrap_socket_impl at 0x7fe06b468820>
  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
           │           │           │                     └ 'wappass.baidu.com'
           │           │           └ <socket.socket [closed] fd=-1, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6>
           │           └ <function SSLContext.wrap_socket at 0x7fe08118de50>
           └ <ssl.SSLContext object at 0x7fded05c8dc0>
  File "/usr/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
           │    │               └ <classmethod object at 0x7fe08c8cfaf0>
           │    └ <class 'ssl.SSLSocket'>
           └ <ssl.SSLContext object at 0x7fded05c8dc0>
  File "/usr/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
    │    └ <function SSLSocket.do_handshake at 0x7fe08c8d2d30>
    └ <ssl.SSLSocket [closed] fd=-1, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6>
  File "/usr/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
    │    └ None
    └ <ssl.SSLSocket [closed] fd=-1, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6>

ssl.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1131)


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/home/chase/.local/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
           │    └ <function HTTPConnectionPool.urlopen at 0x7fe06b3fef70>
           └ <urllib3.connectionpool.HTTPSConnectionPool object at 0x7fdf541376a0>
  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
              │       └ <function Retry.increment at 0x7fe06b443280>
              └ Retry(total=0, connect=None, read=False, redirect=None, status=None)
  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
          │             │      │    │        │             └ 'unknown'
          │             │      │    │        └ <class 'urllib3.exceptions.ResponseError'>
          │             │      │    └ SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1131)'))
          │             │      └ '/static/captcha/tuxing.html?ak=2ef521ec36290baed33d66de9b16f625&backurl=http%3A%2F%2Ftieba.baidu.com%2Ff%2Fsearch%2Fres%3Fis...
          │             └ <urllib3.connectionpool.HTTPSConnectionPool object at 0x7fdf541376a0>
          └ <class 'urllib3.exceptions.MaxRetryError'>

urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='wappass.baidu.com', port=443): Max retries exceeded with url: /static/captcha/tuxing.html?ak=2ef521ec36290baed33d66de9b16f625&backurl=http%3A%2F%2Ftieba.baidu.com%2Ff%2Fsearch%2Fres%3Fisnew%3D1%26kw%3D%26qw%3D%25E4%25B8%25AD%25E4%25BC%2581%25E5%258A%25A9%25E5%258A%259B%25E6%25B3%25B0%25E5%259B%25BD%25E6%2591%25A9%25E6%2589%2598%25E8%25BD%25A6%25E7%2594%25B5%25E6%25B0%2594%25E5%258C%2596%25E8%25BD%25AC%25E5%259E%258B%26rn%3D10%26un%3D%26only_thread%3D0%26sm%3D1%26sd%3D%26ed%3D%26pn%3D25&timestamp=1654682870&signature=7243e8e3678a50a6d2c751db121145cc (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1131)')))


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/usr/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7fe08f92ea60>
    └ <Thread(Thread-32748, started daemon 140589160290048)>
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7fe08f92e790>
    └ <Thread(Thread-32748, started daemon 140589160290048)>
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-32748, started daemon 140589160290048)>
    │    │        │    └ ('ProjectManager.run_func_by_thread',)
    │    │        └ <Thread(Thread-32748, started daemon 140589160290048)>
    │    └ <bound method ProjectManager.get_request_from_keywords_hot of <monitor.projectManager.ProjectManager object at 0x7fe063c65790>>
    └ <Thread(Thread-32748, started daemon 140589160290048)>

  File "/home/users/Scy/yuqing/spider/monitor/projectManager.py", line 833, in get_request_from_keywords_hot
    self.search_spider_manager.crawl_by_keyword(
    │    │                     └ <function SearchSpidersManager.crawl_by_keyword at 0x7fe063c71160>
    │    └ <monitor.spiderManager.SearchSpidersManager object at 0x7fe0638938b0>
    └ <monitor.projectManager.ProjectManager object at 0x7fe063c65790>

  File "/home/users/Scy/yuqing/spider/monitor/spiderManager.py", line 118, in crawl_by_keyword
    self.crawl_by_keyword_signal_platform(project_names, platform, keyword, crawl_time, project_times)
    │    │                                │              │         │        │           └ {'default': <monitor.TimeSection object at 0x7fe0639a2b80>}
    │    │                                │              │         │        └ <monitor.TimeSection object at 0x7fde50dcb070>
    │    │                                │              │         └ '中企助力泰国摩托车电气化转型'
    │    │                                │              └ '贴吧'
    │    │                                └ ['default']
    │    └ <function SearchSpidersManager.crawl_by_keyword_signal_platform at 0x7fe063c71280>
    └ <monitor.spiderManager.SearchSpidersManager object at 0x7fe0638938b0>

  File "/home/users/Scy/yuqing/spider/monitor/spiderManager.py", line 150, in crawl_by_keyword_signal_platform
    requests = self.get_request_from_keyword(platform, keyword_only, **crawl_time.to_dict())
               │    │                        │         │               │          └ <function TimeSection.to_dict at 0x7fe06b8931f0>
               │    │                        │         │               └ <monitor.TimeSection object at 0x7fde50dcb070>
               │    │                        │         └ '中企助力泰国摩托车电气化转型'
               │    │                        └ '贴吧'
               │    └ <function SearchSpidersManager.get_request_from_keyword at 0x7fe063c713a0>
               └ <monitor.spiderManager.SearchSpidersManager object at 0x7fe0638938b0>

  File "/home/users/Scy/yuqing/spider/monitor/spiderManager.py", line 214, in get_request_from_keyword
    for request in self.spiders[platform].get_request_from_keyword(headers, search_url, keyword, content_url,
                   │    │       │                                  │        │           │        └ None
                   │    │       │                                  │        │           └ '中企助力泰国摩托车电气化转型'
                   │    │       │                                  │        └ <string.Template object at 0x7fddd02c9f70>
                   │    │       │                                  └ {'Connection': 'keep-alive', 'sec-ch-ua': "'Chromium';v='92',' Not A;Brand';v='99', 'Google Chrome';v='92'", 'sec-ch-ua-mobil...
                   │    │       └ '贴吧'
                   │    └ {'凤凰网': <monitor.searchSpiders.ifeng.Ifeng object at 0x7fe063893370>, '头条': <monitor.searchSpiders.toutiao.Toutiao object at ...
                   └ <monitor.spiderManager.SearchSpidersManager object at 0x7fe0638938b0>

> File "/home/users/Scy/yuqing/spider/monitor/searchSpiders/tieba.py", line 22, in get_request_from_keyword
    response = requests.get(url, headers=headers, timeout=50)
               │        │   │            └ {'Connection': 'keep-alive', 'sec-ch-ua': "'Chromium';v='92',' Not A;Brand';v='99', 'Google Chrome';v='92'", 'sec-ch-ua-mobil...
               │        │   └ 'https://tieba.baidu.com/f/search/res?isnew=1&kw=&qw=中企助力泰国摩托车电气化转型&rn=10&un=&only_thread=0&sm=1&sd=&ed=&pn=25'
               │        └ <function get at 0x7fe06b2724c0>
               └ <module 'requests' from '/home/chase/.local/lib/python3.8/site-packages/requests/__init__.py'>

  File "/home/chase/.local/lib/python3.8/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
           │              │           │         └ {'headers': {'Connection': 'keep-alive', 'sec-ch-ua': "'Chromium';v='92',' Not A;Brand';v='99', 'Google Chrome';v='92'", 'sec...
           │              │           └ None
           │              └ 'https://tieba.baidu.com/f/search/res?isnew=1&kw=&qw=中企助力泰国摩托车电气化转型&rn=10&un=&only_thread=0&sm=1&sd=&ed=&pn=25'
           └ <function request at 0x7fe06b268310>
  File "/home/chase/.local/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
           │       │              │           │      └ {'params': None, 'headers': {'Connection': 'keep-alive', 'sec-ch-ua': "'Chromium';v='92',' Not A;Brand';v='99', 'Google Chrom...
           │       │              │           └ 'https://tieba.baidu.com/f/search/res?isnew=1&kw=&qw=中企助力泰国摩托车电气化转型&rn=10&un=&only_thread=0&sm=1&sd=&ed=&pn=25'
           │       │              └ 'get'
           │       └ <function Session.request at 0x7fe06b27bc10>
           └ <requests.sessions.Session object at 0x7fdcd3189790>
  File "/home/chase/.local/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
           │    │    │       └ {'timeout': 50, 'allow_redirects': True, 'verify': True, 'proxies': OrderedDict(), 'stream': False, 'cert': None}
           │    │    └ <PreparedRequest [GET]>
           │    └ <function Session.send at 0x7fe06b2720d0>
           └ <requests.sessions.Session object at 0x7fdcd3189790>
  File "/home/chase/.local/lib/python3.8/site-packages/requests/sessions.py", line 677, in send
    history = [resp for resp in gen]
                                └ <generator object SessionRedirectMixin.resolve_redirects at 0x7fdcf089d190>
  File "/home/chase/.local/lib/python3.8/site-packages/requests/sessions.py", line 677, in <listcomp>
    history = [resp for resp in gen]
  File "/home/chase/.local/lib/python3.8/site-packages/requests/sessions.py", line 237, in resolve_redirects
    resp = self.send(
           │    └ <function Session.send at 0x7fe06b2720d0>
           └ <requests.sessions.Session object at 0x7fdcd3189790>
  File "/home/chase/.local/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
        │       │    │          └ {'stream': False, 'timeout': 50, 'verify': True, 'cert': None, 'proxies': OrderedDict()}
        │       │    └ <PreparedRequest [GET]>
        │       └ <function HTTPAdapter.send at 0x7fe06b27b550>
        └ <requests.adapters.HTTPAdapter object at 0x7fdeb03d0be0>
  File "/home/chase/.local/lib/python3.8/site-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
          │                   └ <PreparedRequest [GET]>
          └ <class 'requests.exceptions.SSLError'>

requests.exceptions.SSLError: HTTPSConnectionPool(host='wappass.baidu.com', port=443): Max retries exceeded with url: /static/captcha/tuxing.html?ak=2ef521ec36290baed33d66de9b16f625&backurl=http%3A%2F%2Ftieba.baidu.com%2Ff%2Fsearch%2Fres%3Fisnew%3D1%26kw%3D%26qw%3D%25E4%25B8%25AD%25E4%25BC%2581%25E5%258A%25A9%25E5%258A%259B%25E6%25B3%25B0%25E5%259B%25BD%25E6%2591%25A9%25E6%2589%2598%25E8%25BD%25A6%25E7%2594%25B5%25E6%25B0%2594%25E5%258C%2596%25E8%25BD%25AC%25E5%259E%258B%26rn%3D10%26un%3D%26only_thread%3D0%26sm%3D1%26sd%3D%26ed%3D%26pn%3D25&timestamp=1654682870&signature=7243e8e3678a50a6d2c751db121145cc (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1131)')))
2022-06-08 18:12:31.178 | ERROR    | monitor.searchSpiders.tieba:get_request_from_keyword:34 - E 贴吧错误HTTPSConnectionPool(host='wappass.baidu.com', port=443): Max retries exceeded with url: /static/captcha/tuxing.html?ak=2ef521ec36290baed33d66de9b16f625&backurl=http%3A%2F%2Ftieba.baidu.com%2Ff%2Fsearch%2Fres%3Fisnew%3D1%26kw%3D%26qw%3D%25E5%25A4%2596%25E4%25BA%25A4%25E9%2583%25A8%25EF%25BC%259A%25E5%2588%25B6%25E8%25A3%2581%25E6%258D%25A2%25E4%25B8%258D%25E6%259D%25A5%25E5%2592%258C%25E5%25B9%25B3%25EF%25BC%258C%25E5%258F%25AA%25E8%2583%25BD%25E7%25BB%2599%25E4%25B8%2596%25E7%2595%258C%25E7%25BB%258F%25E6%25B5%258E%25E9%259B%25AA%25E4%25B8%258A%25E5%258A%25A0%25E9%259C%259C%26rn%3D10%26un%3D%26only_thread%3D0%26sm%3D1%26sd%3D%26ed%3D%26pn%3D26&timestamp=1654683151&signature=3443bd535826ff9f6d514fc05949caf4 (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1131)')))
Traceback (most recent call last):

  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
                       │    └ <function HTTPConnectionPool._make_request at 0x7fe06b3fed30>
                       └ <urllib3.connectionpool.HTTPSConnectionPool object at 0x7fded024b430>
  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
    │    │              └ <urllib3.connection.HTTPSConnection object at 0x7fdef04fc130>
    │    └ <function HTTPSConnectionPool._validate_conn at 0x7fe06b3ff280>
    └ <urllib3.connectionpool.HTTPSConnectionPool object at 0x7fded024b430>
  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
    │    └ <function HTTPSConnection.connect at 0x7fe06b46d940>
    └ <urllib3.connection.HTTPSConnection object at 0x7fdef04fc130>
  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/connection.py", line 416, in connect
    self.sock = ssl_wrap_socket(
    │    │      └ <function ssl_wrap_socket at 0x7fe06b468670>
    │    └ None
    └ <urllib3.connection.HTTPSConnection object at 0x7fdef04fc130>
  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
               └ <function _ssl_wrap_socket_impl at 0x7fe06b468820>
  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
           │           │           │                     └ 'wappass.baidu.com'
           │           │           └ <socket.socket [closed] fd=-1, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6>
           │           └ <function SSLContext.wrap_socket at 0x7fe08118de50>
           └ <ssl.SSLContext object at 0x7fdd15c24540>
  File "/usr/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
           │    │               └ <classmethod object at 0x7fe08c8cfaf0>
           │    └ <class 'ssl.SSLSocket'>
           └ <ssl.SSLContext object at 0x7fdd15c24540>
  File "/usr/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
    │    └ <function SSLSocket.do_handshake at 0x7fe08c8d2d30>
    └ <ssl.SSLSocket [closed] fd=-1, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6>
  File "/usr/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
    │    └ None
    └ <ssl.SSLSocket [closed] fd=-1, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6>

ssl.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1131)


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/home/chase/.local/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
           │    └ <function HTTPConnectionPool.urlopen at 0x7fe06b3fef70>
           └ <urllib3.connectionpool.HTTPSConnectionPool object at 0x7fded024b430>
  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
              │       └ <function Retry.increment at 0x7fe06b443280>
              └ Retry(total=0, connect=None, read=False, redirect=None, status=None)
  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
          │             │      │    │        │             └ 'unknown'
          │             │      │    │        └ <class 'urllib3.exceptions.ResponseError'>
          │             │      │    └ SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1131)'))
          │             │      └ '/static/captcha/tuxing.html?ak=2ef521ec36290baed33d66de9b16f625&backurl=http%3A%2F%2Ftieba.baidu.com%2Ff%2Fsearch%2Fres%3Fis...
          │             └ <urllib3.connectionpool.HTTPSConnectionPool object at 0x7fded024b430>
          └ <class 'urllib3.exceptions.MaxRetryError'>

urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='wappass.baidu.com', port=443): Max retries exceeded with url: /static/captcha/tuxing.html?ak=2ef521ec36290baed33d66de9b16f625&backurl=http%3A%2F%2Ftieba.baidu.com%2Ff%2Fsearch%2Fres%3Fisnew%3D1%26kw%3D%26qw%3D%25E5%25A4%2596%25E4%25BA%25A4%25E9%2583%25A8%25EF%25BC%259A%25E5%2588%25B6%25E8%25A3%2581%25E6%258D%25A2%25E4%25B8%258D%25E6%259D%25A5%25E5%2592%258C%25E5%25B9%25B3%25EF%25BC%258C%25E5%258F%25AA%25E8%2583%25BD%25E7%25BB%2599%25E4%25B8%2596%25E7%2595%258C%25E7%25BB%258F%25E6%25B5%258E%25E9%259B%25AA%25E4%25B8%258A%25E5%258A%25A0%25E9%259C%259C%26rn%3D10%26un%3D%26only_thread%3D0%26sm%3D1%26sd%3D%26ed%3D%26pn%3D26&timestamp=1654683151&signature=3443bd535826ff9f6d514fc05949caf4 (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1131)')))


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/usr/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7fe08f92ea60>
    └ <Thread(Thread-30318, started daemon 140590226163456)>
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7fe08f92e790>
    └ <Thread(Thread-30318, started daemon 140590226163456)>
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-30318, started daemon 140590226163456)>
    │    │        │    └ ('ProjectManager.run_func_by_thread',)
    │    │        └ <Thread(Thread-30318, started daemon 140590226163456)>
    │    └ <bound method ProjectManager.get_request_from_keywords_hot of <monitor.projectManager.ProjectManager object at 0x7fe063c65790>>
    └ <Thread(Thread-30318, started daemon 140590226163456)>

  File "/home/users/Scy/yuqing/spider/monitor/projectManager.py", line 833, in get_request_from_keywords_hot
    self.search_spider_manager.crawl_by_keyword(
    │    │                     └ <function SearchSpidersManager.crawl_by_keyword at 0x7fe063c71160>
    │    └ <monitor.spiderManager.SearchSpidersManager object at 0x7fe0638938b0>
    └ <monitor.projectManager.ProjectManager object at 0x7fe063c65790>

  File "/home/users/Scy/yuqing/spider/monitor/spiderManager.py", line 118, in crawl_by_keyword
    self.crawl_by_keyword_signal_platform(project_names, platform, keyword, crawl_time, project_times)
    │    │                                │              │         │        │           └ {'default': <monitor.TimeSection object at 0x7fe0639a2b80>}
    │    │                                │              │         │        └ <monitor.TimeSection object at 0x7fdd1e9b2280>
    │    │                                │              │         └ '外交部：制裁换不来和平，只能给世界经济雪上加霜'
    │    │                                │              └ '贴吧'
    │    │                                └ ['default']
    │    └ <function SearchSpidersManager.crawl_by_keyword_signal_platform at 0x7fe063c71280>
    └ <monitor.spiderManager.SearchSpidersManager object at 0x7fe0638938b0>

  File "/home/users/Scy/yuqing/spider/monitor/spiderManager.py", line 150, in crawl_by_keyword_signal_platform
    requests = self.get_request_from_keyword(platform, keyword_only, **crawl_time.to_dict())
               │    │                        │         │               │          └ <function TimeSection.to_dict at 0x7fe06b8931f0>
               │    │                        │         │               └ <monitor.TimeSection object at 0x7fdd1e9b2280>
               │    │                        │         └ '外交部：制裁换不来和平，只能给世界经济雪上加霜'
               │    │                        └ '贴吧'
               │    └ <function SearchSpidersManager.get_request_from_keyword at 0x7fe063c713a0>
               └ <monitor.spiderManager.SearchSpidersManager object at 0x7fe0638938b0>

  File "/home/users/Scy/yuqing/spider/monitor/spiderManager.py", line 214, in get_request_from_keyword
    for request in self.spiders[platform].get_request_from_keyword(headers, search_url, keyword, content_url,
                   │    │       │                                  │        │           │        └ None
                   │    │       │                                  │        │           └ '外交部：制裁换不来和平，只能给世界经济雪上加霜'
                   │    │       │                                  │        └ <string.Template object at 0x7fdd21cf0220>
                   │    │       │                                  └ {'Connection': 'keep-alive', 'sec-ch-ua': "'Chromium';v='92',' Not A;Brand';v='99', 'Google Chrome';v='92'", 'sec-ch-ua-mobil...
                   │    │       └ '贴吧'
                   │    └ {'凤凰网': <monitor.searchSpiders.ifeng.Ifeng object at 0x7fe063893370>, '头条': <monitor.searchSpiders.toutiao.Toutiao object at ...
                   └ <monitor.spiderManager.SearchSpidersManager object at 0x7fe0638938b0>

> File "/home/users/Scy/yuqing/spider/monitor/searchSpiders/tieba.py", line 22, in get_request_from_keyword
    response = requests.get(url, headers=headers, timeout=50)
               │        │   │            └ {'Connection': 'keep-alive', 'sec-ch-ua': "'Chromium';v='92',' Not A;Brand';v='99', 'Google Chrome';v='92'", 'sec-ch-ua-mobil...
               │        │   └ 'https://tieba.baidu.com/f/search/res?isnew=1&kw=&qw=外交部：制裁换不来和平，只能给世界经济雪上加霜&rn=10&un=&only_thread=0&sm=1&sd=&ed=&pn=26'
               │        └ <function get at 0x7fe06b2724c0>
               └ <module 'requests' from '/home/chase/.local/lib/python3.8/site-packages/requests/__init__.py'>

  File "/home/chase/.local/lib/python3.8/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
           │              │           │         └ {'headers': {'Connection': 'keep-alive', 'sec-ch-ua': "'Chromium';v='92',' Not A;Brand';v='99', 'Google Chrome';v='92'", 'sec...
           │              │           └ None
           │              └ 'https://tieba.baidu.com/f/search/res?isnew=1&kw=&qw=外交部：制裁换不来和平，只能给世界经济雪上加霜&rn=10&un=&only_thread=0&sm=1&sd=&ed=&pn=26'
           └ <function request at 0x7fe06b268310>
  File "/home/chase/.local/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
           │       │              │           │      └ {'params': None, 'headers': {'Connection': 'keep-alive', 'sec-ch-ua': "'Chromium';v='92',' Not A;Brand';v='99', 'Google Chrom...
           │       │              │           └ 'https://tieba.baidu.com/f/search/res?isnew=1&kw=&qw=外交部：制裁换不来和平，只能给世界经济雪上加霜&rn=10&un=&only_thread=0&sm=1&sd=&ed=&pn=26'
           │       │              └ 'get'
           │       └ <function Session.request at 0x7fe06b27bc10>
           └ <requests.sessions.Session object at 0x7fe060423100>
  File "/home/chase/.local/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
           │    │    │       └ {'timeout': 50, 'allow_redirects': True, 'verify': True, 'proxies': OrderedDict(), 'stream': False, 'cert': None}
           │    │    └ <PreparedRequest [GET]>
           │    └ <function Session.send at 0x7fe06b2720d0>
           └ <requests.sessions.Session object at 0x7fe060423100>
  File "/home/chase/.local/lib/python3.8/site-packages/requests/sessions.py", line 677, in send
    history = [resp for resp in gen]
                                └ <generator object SessionRedirectMixin.resolve_redirects at 0x7fddf078c740>
  File "/home/chase/.local/lib/python3.8/site-packages/requests/sessions.py", line 677, in <listcomp>
    history = [resp for resp in gen]
  File "/home/chase/.local/lib/python3.8/site-packages/requests/sessions.py", line 237, in resolve_redirects
    resp = self.send(
           │    └ <function Session.send at 0x7fe06b2720d0>
           └ <requests.sessions.Session object at 0x7fe060423100>
  File "/home/chase/.local/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
        │       │    │          └ {'stream': False, 'timeout': 50, 'verify': True, 'cert': None, 'proxies': OrderedDict()}
        │       │    └ <PreparedRequest [GET]>
        │       └ <function HTTPAdapter.send at 0x7fe06b27b550>
        └ <requests.adapters.HTTPAdapter object at 0x7fe0601ed940>
  File "/home/chase/.local/lib/python3.8/site-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
          │                   └ <PreparedRequest [GET]>
          └ <class 'requests.exceptions.SSLError'>

requests.exceptions.SSLError: HTTPSConnectionPool(host='wappass.baidu.com', port=443): Max retries exceeded with url: /static/captcha/tuxing.html?ak=2ef521ec36290baed33d66de9b16f625&backurl=http%3A%2F%2Ftieba.baidu.com%2Ff%2Fsearch%2Fres%3Fisnew%3D1%26kw%3D%26qw%3D%25E5%25A4%2596%25E4%25BA%25A4%25E9%2583%25A8%25EF%25BC%259A%25E5%2588%25B6%25E8%25A3%2581%25E6%258D%25A2%25E4%25B8%258D%25E6%259D%25A5%25E5%2592%258C%25E5%25B9%25B3%25EF%25BC%258C%25E5%258F%25AA%25E8%2583%25BD%25E7%25BB%2599%25E4%25B8%2596%25E7%2595%258C%25E7%25BB%258F%25E6%25B5%258E%25E9%259B%25AA%25E4%25B8%258A%25E5%258A%25A0%25E9%259C%259C%26rn%3D10%26un%3D%26only_thread%3D0%26sm%3D1%26sd%3D%26ed%3D%26pn%3D26&timestamp=1654683151&signature=3443bd535826ff9f6d514fc05949caf4 (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1131)')))
2022-06-08 18:18:00.784 | ERROR    | monitor.searchSpiders.tieba:get_request_from_keyword:34 - E 贴吧错误HTTPSConnectionPool(host='wappass.baidu.com', port=443): Max retries exceeded with url: /static/captcha/tuxing.html?ak=2ef521ec36290baed33d66de9b16f625&backurl=http%3A%2F%2Ftieba.baidu.com%2Ff%2Fsearch%2Fres%3Fisnew%3D1%26kw%3D%26qw%3D%25E8%2590%25A5%25E9%2580%25A0%25E4%25B9%25A6%25E9%25A6%2599%25E7%25A4%25BE%25E4%25BC%259A%2520%25E5%258A%25A9%25E5%258A%259B%25E6%2596%2587%25E5%258C%2596%25E5%25BC%25BA%25E5%259B%25BD%26rn%3D10%26un%3D%26only_thread%3D0%26sm%3D1%26sd%3D%26ed%3D%26pn%3D2&timestamp=1654683480&signature=0eac07e66c16b822b39c6ee52babd82d (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1131)')))
Traceback (most recent call last):

  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
                       │    └ <function HTTPConnectionPool._make_request at 0x7fe06b3fed30>
                       └ <urllib3.connectionpool.HTTPSConnectionPool object at 0x7fdda2163070>
  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
    │    │              └ <urllib3.connection.HTTPSConnection object at 0x7fddf058b5b0>
    │    └ <function HTTPSConnectionPool._validate_conn at 0x7fe06b3ff280>
    └ <urllib3.connectionpool.HTTPSConnectionPool object at 0x7fdda2163070>
  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
    │    └ <function HTTPSConnection.connect at 0x7fe06b46d940>
    └ <urllib3.connection.HTTPSConnection object at 0x7fddf058b5b0>
  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/connection.py", line 416, in connect
    self.sock = ssl_wrap_socket(
    │    │      └ <function ssl_wrap_socket at 0x7fe06b468670>
    │    └ None
    └ <urllib3.connection.HTTPSConnection object at 0x7fddf058b5b0>
  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
               └ <function _ssl_wrap_socket_impl at 0x7fe06b468820>
  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
           │           │           │                     └ 'wappass.baidu.com'
           │           │           └ <socket.socket [closed] fd=-1, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6>
           │           └ <function SSLContext.wrap_socket at 0x7fe08118de50>
           └ <ssl.SSLContext object at 0x7fdd451eed40>
  File "/usr/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
           │    │               └ <classmethod object at 0x7fe08c8cfaf0>
           │    └ <class 'ssl.SSLSocket'>
           └ <ssl.SSLContext object at 0x7fdd451eed40>
  File "/usr/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
    │    └ <function SSLSocket.do_handshake at 0x7fe08c8d2d30>
    └ <ssl.SSLSocket [closed] fd=-1, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6>
  File "/usr/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
    │    └ None
    └ <ssl.SSLSocket [closed] fd=-1, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6>

ssl.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1131)


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/home/chase/.local/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
           │    └ <function HTTPConnectionPool.urlopen at 0x7fe06b3fef70>
           └ <urllib3.connectionpool.HTTPSConnectionPool object at 0x7fdda2163070>
  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
              │       └ <function Retry.increment at 0x7fe06b443280>
              └ Retry(total=0, connect=None, read=False, redirect=None, status=None)
  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
          │             │      │    │        │             └ 'unknown'
          │             │      │    │        └ <class 'urllib3.exceptions.ResponseError'>
          │             │      │    └ SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1131)'))
          │             │      └ '/static/captcha/tuxing.html?ak=2ef521ec36290baed33d66de9b16f625&backurl=http%3A%2F%2Ftieba.baidu.com%2Ff%2Fsearch%2Fres%3Fis...
          │             └ <urllib3.connectionpool.HTTPSConnectionPool object at 0x7fdda2163070>
          └ <class 'urllib3.exceptions.MaxRetryError'>

urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='wappass.baidu.com', port=443): Max retries exceeded with url: /static/captcha/tuxing.html?ak=2ef521ec36290baed33d66de9b16f625&backurl=http%3A%2F%2Ftieba.baidu.com%2Ff%2Fsearch%2Fres%3Fisnew%3D1%26kw%3D%26qw%3D%25E8%2590%25A5%25E9%2580%25A0%25E4%25B9%25A6%25E9%25A6%2599%25E7%25A4%25BE%25E4%25BC%259A%2520%25E5%258A%25A9%25E5%258A%259B%25E6%2596%2587%25E5%258C%2596%25E5%25BC%25BA%25E5%259B%25BD%26rn%3D10%26un%3D%26only_thread%3D0%26sm%3D1%26sd%3D%26ed%3D%26pn%3D2&timestamp=1654683480&signature=0eac07e66c16b822b39c6ee52babd82d (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1131)')))


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/usr/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7fe08f92ea60>
    └ <Thread(Thread-30756, started daemon 140586827671296)>
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7fe08f92e790>
    └ <Thread(Thread-30756, started daemon 140586827671296)>
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-30756, started daemon 140586827671296)>
    │    │        │    └ ('ProjectManager.run_func_by_thread',)
    │    │        └ <Thread(Thread-30756, started daemon 140586827671296)>
    │    └ <bound method ProjectManager.get_request_from_keywords_hot of <monitor.projectManager.ProjectManager object at 0x7fe063c65790>>
    └ <Thread(Thread-30756, started daemon 140586827671296)>

  File "/home/users/Scy/yuqing/spider/monitor/projectManager.py", line 833, in get_request_from_keywords_hot
    self.search_spider_manager.crawl_by_keyword(
    │    │                     └ <function SearchSpidersManager.crawl_by_keyword at 0x7fe063c71160>
    │    └ <monitor.spiderManager.SearchSpidersManager object at 0x7fe0638938b0>
    └ <monitor.projectManager.ProjectManager object at 0x7fe063c65790>

  File "/home/users/Scy/yuqing/spider/monitor/spiderManager.py", line 118, in crawl_by_keyword
    self.crawl_by_keyword_signal_platform(project_names, platform, keyword, crawl_time, project_times)
    │    │                                │              │         │        │           └ {'default': <monitor.TimeSection object at 0x7fe0639a2b80>}
    │    │                                │              │         │        └ <monitor.TimeSection object at 0x7fddd0202850>
    │    │                                │              │         └ '营造书香社会 助力文化强国'
    │    │                                │              └ '贴吧'
    │    │                                └ ['default']
    │    └ <function SearchSpidersManager.crawl_by_keyword_signal_platform at 0x7fe063c71280>
    └ <monitor.spiderManager.SearchSpidersManager object at 0x7fe0638938b0>

  File "/home/users/Scy/yuqing/spider/monitor/spiderManager.py", line 150, in crawl_by_keyword_signal_platform
    requests = self.get_request_from_keyword(platform, keyword_only, **crawl_time.to_dict())
               │    │                        │         │               │          └ <function TimeSection.to_dict at 0x7fe06b8931f0>
               │    │                        │         │               └ <monitor.TimeSection object at 0x7fddd0202850>
               │    │                        │         └ '营造书香社会 助力文化强国'
               │    │                        └ '贴吧'
               │    └ <function SearchSpidersManager.get_request_from_keyword at 0x7fe063c713a0>
               └ <monitor.spiderManager.SearchSpidersManager object at 0x7fe0638938b0>

  File "/home/users/Scy/yuqing/spider/monitor/spiderManager.py", line 214, in get_request_from_keyword
    for request in self.spiders[platform].get_request_from_keyword(headers, search_url, keyword, content_url,
                   │    │       │                                  │        │           │        └ None
                   │    │       │                                  │        │           └ '营造书香社会 助力文化强国'
                   │    │       │                                  │        └ <string.Template object at 0x7fde50c55430>
                   │    │       │                                  └ {'Connection': 'keep-alive', 'sec-ch-ua': "'Chromium';v='92',' Not A;Brand';v='99', 'Google Chrome';v='92'", 'sec-ch-ua-mobil...
                   │    │       └ '贴吧'
                   │    └ {'凤凰网': <monitor.searchSpiders.ifeng.Ifeng object at 0x7fe063893370>, '头条': <monitor.searchSpiders.toutiao.Toutiao object at ...
                   └ <monitor.spiderManager.SearchSpidersManager object at 0x7fe0638938b0>

> File "/home/users/Scy/yuqing/spider/monitor/searchSpiders/tieba.py", line 22, in get_request_from_keyword
    response = requests.get(url, headers=headers, timeout=50)
               │        │   │            └ {'Connection': 'keep-alive', 'sec-ch-ua': "'Chromium';v='92',' Not A;Brand';v='99', 'Google Chrome';v='92'", 'sec-ch-ua-mobil...
               │        │   └ 'https://tieba.baidu.com/f/search/res?isnew=1&kw=&qw=营造书香社会 助力文化强国&rn=10&un=&only_thread=0&sm=1&sd=&ed=&pn=2'
               │        └ <function get at 0x7fe06b2724c0>
               └ <module 'requests' from '/home/chase/.local/lib/python3.8/site-packages/requests/__init__.py'>

  File "/home/chase/.local/lib/python3.8/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
           │              │           │         └ {'headers': {'Connection': 'keep-alive', 'sec-ch-ua': "'Chromium';v='92',' Not A;Brand';v='99', 'Google Chrome';v='92'", 'sec...
           │              │           └ None
           │              └ 'https://tieba.baidu.com/f/search/res?isnew=1&kw=&qw=营造书香社会 助力文化强国&rn=10&un=&only_thread=0&sm=1&sd=&ed=&pn=2'
           └ <function request at 0x7fe06b268310>
  File "/home/chase/.local/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
           │       │              │           │      └ {'params': None, 'headers': {'Connection': 'keep-alive', 'sec-ch-ua': "'Chromium';v='92',' Not A;Brand';v='99', 'Google Chrom...
           │       │              │           └ 'https://tieba.baidu.com/f/search/res?isnew=1&kw=&qw=营造书香社会 助力文化强国&rn=10&un=&only_thread=0&sm=1&sd=&ed=&pn=2'
           │       │              └ 'get'
           │       └ <function Session.request at 0x7fe06b27bc10>
           └ <requests.sessions.Session object at 0x7fdef02afa30>
  File "/home/chase/.local/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
           │    │    │       └ {'timeout': 50, 'allow_redirects': True, 'verify': True, 'proxies': OrderedDict(), 'stream': False, 'cert': None}
           │    │    └ <PreparedRequest [GET]>
           │    └ <function Session.send at 0x7fe06b2720d0>
           └ <requests.sessions.Session object at 0x7fdef02afa30>
  File "/home/chase/.local/lib/python3.8/site-packages/requests/sessions.py", line 677, in send
    history = [resp for resp in gen]
                                └ <generator object SessionRedirectMixin.resolve_redirects at 0x7fde3064ab30>
  File "/home/chase/.local/lib/python3.8/site-packages/requests/sessions.py", line 677, in <listcomp>
    history = [resp for resp in gen]
  File "/home/chase/.local/lib/python3.8/site-packages/requests/sessions.py", line 237, in resolve_redirects
    resp = self.send(
           │    └ <function Session.send at 0x7fe06b2720d0>
           └ <requests.sessions.Session object at 0x7fdef02afa30>
  File "/home/chase/.local/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
        │       │    │          └ {'stream': False, 'timeout': 50, 'verify': True, 'cert': None, 'proxies': OrderedDict()}
        │       │    └ <PreparedRequest [GET]>
        │       └ <function HTTPAdapter.send at 0x7fe06b27b550>
        └ <requests.adapters.HTTPAdapter object at 0x7fde3073e4f0>
  File "/home/chase/.local/lib/python3.8/site-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
          │                   └ <PreparedRequest [GET]>
          └ <class 'requests.exceptions.SSLError'>

requests.exceptions.SSLError: HTTPSConnectionPool(host='wappass.baidu.com', port=443): Max retries exceeded with url: /static/captcha/tuxing.html?ak=2ef521ec36290baed33d66de9b16f625&backurl=http%3A%2F%2Ftieba.baidu.com%2Ff%2Fsearch%2Fres%3Fisnew%3D1%26kw%3D%26qw%3D%25E8%2590%25A5%25E9%2580%25A0%25E4%25B9%25A6%25E9%25A6%2599%25E7%25A4%25BE%25E4%25BC%259A%2520%25E5%258A%25A9%25E5%258A%259B%25E6%2596%2587%25E5%258C%2596%25E5%25BC%25BA%25E5%259B%25BD%26rn%3D10%26un%3D%26only_thread%3D0%26sm%3D1%26sd%3D%26ed%3D%26pn%3D2&timestamp=1654683480&signature=0eac07e66c16b822b39c6ee52babd82d (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1131)')))
2022-06-08 18:18:40.717 | ERROR    | monitor.searchSpiders.tieba:get_request_from_keyword:34 - E 贴吧错误HTTPSConnectionPool(host='wappass.baidu.com', port=443): Max retries exceeded with url: /static/captcha/tuxing.html?ak=2ef521ec36290baed33d66de9b16f625&backurl=http%3A%2F%2Ftieba.baidu.com%2Ff%2Fsearch%2Fres%3Fisnew%3D1%26kw%3D%26qw%3D%25E5%25BE%25B7%25E5%259B%25BD%25E5%2592%258C%25E4%25B9%258C%25E5%2585%258B%25E5%2585%25B0%25E4%25B8%25A4%25E5%259B%25BD%25E6%2580%25BB%25E7%25BB%259F%25E9%2580%259A%25E7%2594%25B5%25E8%25AF%259D%26rn%3D10%26un%3D%26only_thread%3D0%26sm%3D1%26sd%3D%26ed%3D%26pn%3D2&timestamp=1654683520&signature=3a1d77f364f57c0f8ed927e6cef09439 (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1131)')))
Traceback (most recent call last):

  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
                       │    └ <function HTTPConnectionPool._make_request at 0x7fe06b3fed30>
                       └ <urllib3.connectionpool.HTTPSConnectionPool object at 0x7fdda2242e20>
  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
    │    │              └ <urllib3.connection.HTTPSConnection object at 0x7fdeb0490d90>
    │    └ <function HTTPSConnectionPool._validate_conn at 0x7fe06b3ff280>
    └ <urllib3.connectionpool.HTTPSConnectionPool object at 0x7fdda2242e20>
  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
    │    └ <function HTTPSConnection.connect at 0x7fe06b46d940>
    └ <urllib3.connection.HTTPSConnection object at 0x7fdeb0490d90>
  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/connection.py", line 416, in connect
    self.sock = ssl_wrap_socket(
    │    │      └ <function ssl_wrap_socket at 0x7fe06b468670>
    │    └ None
    └ <urllib3.connection.HTTPSConnection object at 0x7fdeb0490d90>
  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
               └ <function _ssl_wrap_socket_impl at 0x7fe06b468820>
  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
           │           │           │                     └ 'wappass.baidu.com'
           │           │           └ <socket.socket [closed] fd=-1, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6>
           │           └ <function SSLContext.wrap_socket at 0x7fe08118de50>
           └ <ssl.SSLContext object at 0x7fddd0111940>
  File "/usr/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
           │    │               └ <classmethod object at 0x7fe08c8cfaf0>
           │    └ <class 'ssl.SSLSocket'>
           └ <ssl.SSLContext object at 0x7fddd0111940>
  File "/usr/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
    │    └ <function SSLSocket.do_handshake at 0x7fe08c8d2d30>
    └ <ssl.SSLSocket [closed] fd=-1, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6>
  File "/usr/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
    │    └ None
    └ <ssl.SSLSocket [closed] fd=-1, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6>

ssl.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1131)


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/home/chase/.local/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
           │    └ <function HTTPConnectionPool.urlopen at 0x7fe06b3fef70>
           └ <urllib3.connectionpool.HTTPSConnectionPool object at 0x7fdda2242e20>
  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
              │       └ <function Retry.increment at 0x7fe06b443280>
              └ Retry(total=0, connect=None, read=False, redirect=None, status=None)
  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
          │             │      │    │        │             └ 'unknown'
          │             │      │    │        └ <class 'urllib3.exceptions.ResponseError'>
          │             │      │    └ SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1131)'))
          │             │      └ '/static/captcha/tuxing.html?ak=2ef521ec36290baed33d66de9b16f625&backurl=http%3A%2F%2Ftieba.baidu.com%2Ff%2Fsearch%2Fres%3Fis...
          │             └ <urllib3.connectionpool.HTTPSConnectionPool object at 0x7fdda2242e20>
          └ <class 'urllib3.exceptions.MaxRetryError'>

urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='wappass.baidu.com', port=443): Max retries exceeded with url: /static/captcha/tuxing.html?ak=2ef521ec36290baed33d66de9b16f625&backurl=http%3A%2F%2Ftieba.baidu.com%2Ff%2Fsearch%2Fres%3Fisnew%3D1%26kw%3D%26qw%3D%25E5%25BE%25B7%25E5%259B%25BD%25E5%2592%258C%25E4%25B9%258C%25E5%2585%258B%25E5%2585%25B0%25E4%25B8%25A4%25E5%259B%25BD%25E6%2580%25BB%25E7%25BB%259F%25E9%2580%259A%25E7%2594%25B5%25E8%25AF%259D%26rn%3D10%26un%3D%26only_thread%3D0%26sm%3D1%26sd%3D%26ed%3D%26pn%3D2&timestamp=1654683520&signature=3a1d77f364f57c0f8ed927e6cef09439 (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1131)')))


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/usr/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7fe08f92ea60>
    └ <Thread(Thread-32742, started daemon 140586226288384)>
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7fe08f92e790>
    └ <Thread(Thread-32742, started daemon 140586226288384)>
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-32742, started daemon 140586226288384)>
    │    │        │    └ ('ProjectManager.run_func_by_thread',)
    │    │        └ <Thread(Thread-32742, started daemon 140586226288384)>
    │    └ <bound method ProjectManager.get_request_from_keywords_hot of <monitor.projectManager.ProjectManager object at 0x7fe063c65790>>
    └ <Thread(Thread-32742, started daemon 140586226288384)>

  File "/home/users/Scy/yuqing/spider/monitor/projectManager.py", line 833, in get_request_from_keywords_hot
    self.search_spider_manager.crawl_by_keyword(
    │    │                     └ <function SearchSpidersManager.crawl_by_keyword at 0x7fe063c71160>
    │    └ <monitor.spiderManager.SearchSpidersManager object at 0x7fe0638938b0>
    └ <monitor.projectManager.ProjectManager object at 0x7fe063c65790>

  File "/home/users/Scy/yuqing/spider/monitor/spiderManager.py", line 118, in crawl_by_keyword
    self.crawl_by_keyword_signal_platform(project_names, platform, keyword, crawl_time, project_times)
    │    │                                │              │         │        │           └ {'default': <monitor.TimeSection object at 0x7fe0639a2b80>}
    │    │                                │              │         │        └ <monitor.TimeSection object at 0x7fdd0109cf10>
    │    │                                │              │         └ '德国和乌克兰两国总统通电话'
    │    │                                │              └ '贴吧'
    │    │                                └ ['default']
    │    └ <function SearchSpidersManager.crawl_by_keyword_signal_platform at 0x7fe063c71280>
    └ <monitor.spiderManager.SearchSpidersManager object at 0x7fe0638938b0>

  File "/home/users/Scy/yuqing/spider/monitor/spiderManager.py", line 150, in crawl_by_keyword_signal_platform
    requests = self.get_request_from_keyword(platform, keyword_only, **crawl_time.to_dict())
               │    │                        │         │               │          └ <function TimeSection.to_dict at 0x7fe06b8931f0>
               │    │                        │         │               └ <monitor.TimeSection object at 0x7fdd0109cf10>
               │    │                        │         └ '德国和乌克兰两国总统通电话'
               │    │                        └ '贴吧'
               │    └ <function SearchSpidersManager.get_request_from_keyword at 0x7fe063c713a0>
               └ <monitor.spiderManager.SearchSpidersManager object at 0x7fe0638938b0>

  File "/home/users/Scy/yuqing/spider/monitor/spiderManager.py", line 214, in get_request_from_keyword
    for request in self.spiders[platform].get_request_from_keyword(headers, search_url, keyword, content_url,
                   │    │       │                                  │        │           │        └ None
                   │    │       │                                  │        │           └ '德国和乌克兰两国总统通电话'
                   │    │       │                                  │        └ <string.Template object at 0x7fde50e9cfa0>
                   │    │       │                                  └ {'Connection': 'keep-alive', 'sec-ch-ua': "'Chromium';v='92',' Not A;Brand';v='99', 'Google Chrome';v='92'", 'sec-ch-ua-mobil...
                   │    │       └ '贴吧'
                   │    └ {'凤凰网': <monitor.searchSpiders.ifeng.Ifeng object at 0x7fe063893370>, '头条': <monitor.searchSpiders.toutiao.Toutiao object at ...
                   └ <monitor.spiderManager.SearchSpidersManager object at 0x7fe0638938b0>

> File "/home/users/Scy/yuqing/spider/monitor/searchSpiders/tieba.py", line 22, in get_request_from_keyword
    response = requests.get(url, headers=headers, timeout=50)
               │        │   │            └ {'Connection': 'keep-alive', 'sec-ch-ua': "'Chromium';v='92',' Not A;Brand';v='99', 'Google Chrome';v='92'", 'sec-ch-ua-mobil...
               │        │   └ 'https://tieba.baidu.com/f/search/res?isnew=1&kw=&qw=德国和乌克兰两国总统通电话&rn=10&un=&only_thread=0&sm=1&sd=&ed=&pn=2'
               │        └ <function get at 0x7fe06b2724c0>
               └ <module 'requests' from '/home/chase/.local/lib/python3.8/site-packages/requests/__init__.py'>

  File "/home/chase/.local/lib/python3.8/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
           │              │           │         └ {'headers': {'Connection': 'keep-alive', 'sec-ch-ua': "'Chromium';v='92',' Not A;Brand';v='99', 'Google Chrome';v='92'", 'sec...
           │              │           └ None
           │              └ 'https://tieba.baidu.com/f/search/res?isnew=1&kw=&qw=德国和乌克兰两国总统通电话&rn=10&un=&only_thread=0&sm=1&sd=&ed=&pn=2'
           └ <function request at 0x7fe06b268310>
  File "/home/chase/.local/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
           │       │              │           │      └ {'params': None, 'headers': {'Connection': 'keep-alive', 'sec-ch-ua': "'Chromium';v='92',' Not A;Brand';v='99', 'Google Chrom...
           │       │              │           └ 'https://tieba.baidu.com/f/search/res?isnew=1&kw=&qw=德国和乌克兰两国总统通电话&rn=10&un=&only_thread=0&sm=1&sd=&ed=&pn=2'
           │       │              └ 'get'
           │       └ <function Session.request at 0x7fe06b27bc10>
           └ <requests.sessions.Session object at 0x7fddd0709940>
  File "/home/chase/.local/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
           │    │    │       └ {'timeout': 50, 'allow_redirects': True, 'verify': True, 'proxies': OrderedDict(), 'stream': False, 'cert': None}
           │    │    └ <PreparedRequest [GET]>
           │    └ <function Session.send at 0x7fe06b2720d0>
           └ <requests.sessions.Session object at 0x7fddd0709940>
  File "/home/chase/.local/lib/python3.8/site-packages/requests/sessions.py", line 677, in send
    history = [resp for resp in gen]
                                └ <generator object SessionRedirectMixin.resolve_redirects at 0x7fdda2775d60>
  File "/home/chase/.local/lib/python3.8/site-packages/requests/sessions.py", line 677, in <listcomp>
    history = [resp for resp in gen]
  File "/home/chase/.local/lib/python3.8/site-packages/requests/sessions.py", line 237, in resolve_redirects
    resp = self.send(
           │    └ <function Session.send at 0x7fe06b2720d0>
           └ <requests.sessions.Session object at 0x7fddd0709940>
  File "/home/chase/.local/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
        │       │    │          └ {'stream': False, 'timeout': 50, 'verify': True, 'cert': None, 'proxies': OrderedDict()}
        │       │    └ <PreparedRequest [GET]>
        │       └ <function HTTPAdapter.send at 0x7fe06b27b550>
        └ <requests.adapters.HTTPAdapter object at 0x7fdef05594c0>
  File "/home/chase/.local/lib/python3.8/site-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
          │                   └ <PreparedRequest [GET]>
          └ <class 'requests.exceptions.SSLError'>

requests.exceptions.SSLError: HTTPSConnectionPool(host='wappass.baidu.com', port=443): Max retries exceeded with url: /static/captcha/tuxing.html?ak=2ef521ec36290baed33d66de9b16f625&backurl=http%3A%2F%2Ftieba.baidu.com%2Ff%2Fsearch%2Fres%3Fisnew%3D1%26kw%3D%26qw%3D%25E5%25BE%25B7%25E5%259B%25BD%25E5%2592%258C%25E4%25B9%258C%25E5%2585%258B%25E5%2585%25B0%25E4%25B8%25A4%25E5%259B%25BD%25E6%2580%25BB%25E7%25BB%259F%25E9%2580%259A%25E7%2594%25B5%25E8%25AF%259D%26rn%3D10%26un%3D%26only_thread%3D0%26sm%3D1%26sd%3D%26ed%3D%26pn%3D2&timestamp=1654683520&signature=3a1d77f364f57c0f8ed927e6cef09439 (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1131)')))
2022-06-08 18:19:50.958 | ERROR    | monitor.searchSpiders.tieba:get_request_from_keyword:34 - E 贴吧错误HTTPSConnectionPool(host='wappass.baidu.com', port=443): Max retries exceeded with url: /static/captcha/tuxing.html?ak=2ef521ec36290baed33d66de9b16f625&backurl=http%3A%2F%2Ftieba.baidu.com%2Ff%2Fsearch%2Fres%3Fisnew%3D1%26kw%3D%26qw%3D%25E2%2580%259C%25E4%25BA%2592%25E5%2588%25A9%25E5%2590%2588%25E4%25BD%259C%25E6%259C%2589%25E5%258A%25A9%25E4%25BA%258E%25E7%25BB%25B4%25E6%258A%25A4%25E5%259C%25B0%25E5%258C%25BA%25E5%25AE%2589%25E5%2585%25A8%25E7%25A8%25B3%25E5%25AE%259A%25E2%2580%259D%26rn%3D10%26un%3D%26only_thread%3D0%26sm%3D1%26sd%3D%26ed%3D%26pn%3D13&timestamp=1654683590&signature=2542d94478f96cd2e5a02df78adbe5bd (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1131)')))
Traceback (most recent call last):

  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
                       │    └ <function HTTPConnectionPool._make_request at 0x7fe06b3fed30>
                       └ <urllib3.connectionpool.HTTPSConnectionPool object at 0x7fdcf097b8b0>
  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
    │    │              └ <urllib3.connection.HTTPSConnection object at 0x7fde9040b130>
    │    └ <function HTTPSConnectionPool._validate_conn at 0x7fe06b3ff280>
    └ <urllib3.connectionpool.HTTPSConnectionPool object at 0x7fdcf097b8b0>
  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
    │    └ <function HTTPSConnection.connect at 0x7fe06b46d940>
    └ <urllib3.connection.HTTPSConnection object at 0x7fde9040b130>
  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/connection.py", line 416, in connect
    self.sock = ssl_wrap_socket(
    │    │      └ <function ssl_wrap_socket at 0x7fe06b468670>
    │    └ None
    └ <urllib3.connection.HTTPSConnection object at 0x7fde9040b130>
  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
               └ <function _ssl_wrap_socket_impl at 0x7fe06b468820>
  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
           │           │           │                     └ 'wappass.baidu.com'
           │           │           └ <socket.socket [closed] fd=-1, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6>
           │           └ <function SSLContext.wrap_socket at 0x7fe08118de50>
           └ <ssl.SSLContext object at 0x7fe0606af240>
  File "/usr/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
           │    │               └ <classmethod object at 0x7fe08c8cfaf0>
           │    └ <class 'ssl.SSLSocket'>
           └ <ssl.SSLContext object at 0x7fe0606af240>
  File "/usr/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
    │    └ <function SSLSocket.do_handshake at 0x7fe08c8d2d30>
    └ <ssl.SSLSocket [closed] fd=-1, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6>
  File "/usr/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
    │    └ None
    └ <ssl.SSLSocket [closed] fd=-1, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6>

ssl.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1131)


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/home/chase/.local/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
           │    └ <function HTTPConnectionPool.urlopen at 0x7fe06b3fef70>
           └ <urllib3.connectionpool.HTTPSConnectionPool object at 0x7fdcf097b8b0>
  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
              │       └ <function Retry.increment at 0x7fe06b443280>
              └ Retry(total=0, connect=None, read=False, redirect=None, status=None)
  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
          │             │      │    │        │             └ 'unknown'
          │             │      │    │        └ <class 'urllib3.exceptions.ResponseError'>
          │             │      │    └ SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1131)'))
          │             │      └ '/static/captcha/tuxing.html?ak=2ef521ec36290baed33d66de9b16f625&backurl=http%3A%2F%2Ftieba.baidu.com%2Ff%2Fsearch%2Fres%3Fis...
          │             └ <urllib3.connectionpool.HTTPSConnectionPool object at 0x7fdcf097b8b0>
          └ <class 'urllib3.exceptions.MaxRetryError'>

urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='wappass.baidu.com', port=443): Max retries exceeded with url: /static/captcha/tuxing.html?ak=2ef521ec36290baed33d66de9b16f625&backurl=http%3A%2F%2Ftieba.baidu.com%2Ff%2Fsearch%2Fres%3Fisnew%3D1%26kw%3D%26qw%3D%25E2%2580%259C%25E4%25BA%2592%25E5%2588%25A9%25E5%2590%2588%25E4%25BD%259C%25E6%259C%2589%25E5%258A%25A9%25E4%25BA%258E%25E7%25BB%25B4%25E6%258A%25A4%25E5%259C%25B0%25E5%258C%25BA%25E5%25AE%2589%25E5%2585%25A8%25E7%25A8%25B3%25E5%25AE%259A%25E2%2580%259D%26rn%3D10%26un%3D%26only_thread%3D0%26sm%3D1%26sd%3D%26ed%3D%26pn%3D13&timestamp=1654683590&signature=2542d94478f96cd2e5a02df78adbe5bd (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1131)')))


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/usr/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7fe08f92ea60>
    └ <Thread(Thread-31887, started daemon 140588639942400)>
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7fe08f92e790>
    └ <Thread(Thread-31887, started daemon 140588639942400)>
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-31887, started daemon 140588639942400)>
    │    │        │    └ ('ProjectManager.run_func_by_thread',)
    │    │        └ <Thread(Thread-31887, started daemon 140588639942400)>
    │    └ <bound method ProjectManager.get_request_from_keywords_hot of <monitor.projectManager.ProjectManager object at 0x7fe063c65790>>
    └ <Thread(Thread-31887, started daemon 140588639942400)>

  File "/home/users/Scy/yuqing/spider/monitor/projectManager.py", line 833, in get_request_from_keywords_hot
    self.search_spider_manager.crawl_by_keyword(
    │    │                     └ <function SearchSpidersManager.crawl_by_keyword at 0x7fe063c71160>
    │    └ <monitor.spiderManager.SearchSpidersManager object at 0x7fe0638938b0>
    └ <monitor.projectManager.ProjectManager object at 0x7fe063c65790>

  File "/home/users/Scy/yuqing/spider/monitor/spiderManager.py", line 118, in crawl_by_keyword
    self.crawl_by_keyword_signal_platform(project_names, platform, keyword, crawl_time, project_times)
    │    │                                │              │         │        │           └ {'default': <monitor.TimeSection object at 0x7fe0639a2b80>}
    │    │                                │              │         │        └ <monitor.TimeSection object at 0x7fdd06298250>
    │    │                                │              │         └ '“互利合作有助于维护地区安全稳定”'
    │    │                                │              └ '贴吧'
    │    │                                └ ['default']
    │    └ <function SearchSpidersManager.crawl_by_keyword_signal_platform at 0x7fe063c71280>
    └ <monitor.spiderManager.SearchSpidersManager object at 0x7fe0638938b0>

  File "/home/users/Scy/yuqing/spider/monitor/spiderManager.py", line 150, in crawl_by_keyword_signal_platform
    requests = self.get_request_from_keyword(platform, keyword_only, **crawl_time.to_dict())
               │    │                        │         │               │          └ <function TimeSection.to_dict at 0x7fe06b8931f0>
               │    │                        │         │               └ <monitor.TimeSection object at 0x7fdd06298250>
               │    │                        │         └ '“互利合作有助于维护地区安全稳定”'
               │    │                        └ '贴吧'
               │    └ <function SearchSpidersManager.get_request_from_keyword at 0x7fe063c713a0>
               └ <monitor.spiderManager.SearchSpidersManager object at 0x7fe0638938b0>

  File "/home/users/Scy/yuqing/spider/monitor/spiderManager.py", line 214, in get_request_from_keyword
    for request in self.spiders[platform].get_request_from_keyword(headers, search_url, keyword, content_url,
                   │    │       │                                  │        │           │        └ None
                   │    │       │                                  │        │           └ '“互利合作有助于维护地区安全稳定”'
                   │    │       │                                  │        └ <string.Template object at 0x7fdccf5ba070>
                   │    │       │                                  └ {'Connection': 'keep-alive', 'sec-ch-ua': "'Chromium';v='92',' Not A;Brand';v='99', 'Google Chrome';v='92'", 'sec-ch-ua-mobil...
                   │    │       └ '贴吧'
                   │    └ {'凤凰网': <monitor.searchSpiders.ifeng.Ifeng object at 0x7fe063893370>, '头条': <monitor.searchSpiders.toutiao.Toutiao object at ...
                   └ <monitor.spiderManager.SearchSpidersManager object at 0x7fe0638938b0>

> File "/home/users/Scy/yuqing/spider/monitor/searchSpiders/tieba.py", line 22, in get_request_from_keyword
    response = requests.get(url, headers=headers, timeout=50)
               │        │   │            └ {'Connection': 'keep-alive', 'sec-ch-ua': "'Chromium';v='92',' Not A;Brand';v='99', 'Google Chrome';v='92'", 'sec-ch-ua-mobil...
               │        │   └ 'https://tieba.baidu.com/f/search/res?isnew=1&kw=&qw=“互利合作有助于维护地区安全稳定”&rn=10&un=&only_thread=0&sm=1&sd=&ed=&pn=13'
               │        └ <function get at 0x7fe06b2724c0>
               └ <module 'requests' from '/home/chase/.local/lib/python3.8/site-packages/requests/__init__.py'>

  File "/home/chase/.local/lib/python3.8/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
           │              │           │         └ {'headers': {'Connection': 'keep-alive', 'sec-ch-ua': "'Chromium';v='92',' Not A;Brand';v='99', 'Google Chrome';v='92'", 'sec...
           │              │           └ None
           │              └ 'https://tieba.baidu.com/f/search/res?isnew=1&kw=&qw=“互利合作有助于维护地区安全稳定”&rn=10&un=&only_thread=0&sm=1&sd=&ed=&pn=13'
           └ <function request at 0x7fe06b268310>
  File "/home/chase/.local/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
           │       │              │           │      └ {'params': None, 'headers': {'Connection': 'keep-alive', 'sec-ch-ua': "'Chromium';v='92',' Not A;Brand';v='99', 'Google Chrom...
           │       │              │           └ 'https://tieba.baidu.com/f/search/res?isnew=1&kw=&qw=“互利合作有助于维护地区安全稳定”&rn=10&un=&only_thread=0&sm=1&sd=&ed=&pn=13'
           │       │              └ 'get'
           │       └ <function Session.request at 0x7fe06b27bc10>
           └ <requests.sessions.Session object at 0x7fde5077a940>
  File "/home/chase/.local/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
           │    │    │       └ {'timeout': 50, 'allow_redirects': True, 'verify': True, 'proxies': OrderedDict(), 'stream': False, 'cert': None}
           │    │    └ <PreparedRequest [GET]>
           │    └ <function Session.send at 0x7fe06b2720d0>
           └ <requests.sessions.Session object at 0x7fde5077a940>
  File "/home/chase/.local/lib/python3.8/site-packages/requests/sessions.py", line 677, in send
    history = [resp for resp in gen]
                                └ <generator object SessionRedirectMixin.resolve_redirects at 0x7fdeb0577430>
  File "/home/chase/.local/lib/python3.8/site-packages/requests/sessions.py", line 677, in <listcomp>
    history = [resp for resp in gen]
  File "/home/chase/.local/lib/python3.8/site-packages/requests/sessions.py", line 237, in resolve_redirects
    resp = self.send(
           │    └ <function Session.send at 0x7fe06b2720d0>
           └ <requests.sessions.Session object at 0x7fde5077a940>
  File "/home/chase/.local/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
        │       │    │          └ {'stream': False, 'timeout': 50, 'verify': True, 'cert': None, 'proxies': OrderedDict()}
        │       │    └ <PreparedRequest [GET]>
        │       └ <function HTTPAdapter.send at 0x7fe06b27b550>
        └ <requests.adapters.HTTPAdapter object at 0x7fde304a6f70>
  File "/home/chase/.local/lib/python3.8/site-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
          │                   └ <PreparedRequest [GET]>
          └ <class 'requests.exceptions.SSLError'>

requests.exceptions.SSLError: HTTPSConnectionPool(host='wappass.baidu.com', port=443): Max retries exceeded with url: /static/captcha/tuxing.html?ak=2ef521ec36290baed33d66de9b16f625&backurl=http%3A%2F%2Ftieba.baidu.com%2Ff%2Fsearch%2Fres%3Fisnew%3D1%26kw%3D%26qw%3D%25E2%2580%259C%25E4%25BA%2592%25E5%2588%25A9%25E5%2590%2588%25E4%25BD%259C%25E6%259C%2589%25E5%258A%25A9%25E4%25BA%258E%25E7%25BB%25B4%25E6%258A%25A4%25E5%259C%25B0%25E5%258C%25BA%25E5%25AE%2589%25E5%2585%25A8%25E7%25A8%25B3%25E5%25AE%259A%25E2%2580%259D%26rn%3D10%26un%3D%26only_thread%3D0%26sm%3D1%26sd%3D%26ed%3D%26pn%3D13&timestamp=1654683590&signature=2542d94478f96cd2e5a02df78adbe5bd (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1131)')))
2022-06-08 18:21:40.570 | ERROR    | monitor.searchSpiders.tieba:get_request_from_keyword:34 - E 贴吧错误HTTPSConnectionPool(host='wappass.baidu.com', port=443): Max retries exceeded with url: /static/captcha/tuxing.html?ak=2ef521ec36290baed33d66de9b16f625&backurl=http%3A%2F%2Ftieba.baidu.com%2Ff%2Fsearch%2Fres%3Fisnew%3D1%26kw%3D%26qw%3D%25E7%25BB%25B4%25E4%25B9%259F%25E7%25BA%25B3%25E8%2581%2594%25E5%2590%2588%25E5%259B%25BD%25E4%25B8%25AD%25E6%2596%2587%25E6%2597%25A5%25E6%25B4%25BB%25E5%258A%25A8%25E6%258B%2589%25E5%25BC%2580%25E5%25B8%25B7%25E5%25B9%2595%26rn%3D10%26un%3D%26only_thread%3D0%26sm%3D1%26sd%3D%26ed%3D%26pn%3D5&timestamp=1654683700&signature=b368cf39642b1445bd5ed5cd3c9a7e88 (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1131)')))
Traceback (most recent call last):

  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
                       │    └ <function HTTPConnectionPool._make_request at 0x7fe06b3fed30>
                       └ <urllib3.connectionpool.HTTPSConnectionPool object at 0x7fde50448370>
  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
    │    │              └ <urllib3.connection.HTTPSConnection object at 0x7fde7019f760>
    │    └ <function HTTPSConnectionPool._validate_conn at 0x7fe06b3ff280>
    └ <urllib3.connectionpool.HTTPSConnectionPool object at 0x7fde50448370>
  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
    │    └ <function HTTPSConnection.connect at 0x7fe06b46d940>
    └ <urllib3.connection.HTTPSConnection object at 0x7fde7019f760>
  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/connection.py", line 416, in connect
    self.sock = ssl_wrap_socket(
    │    │      └ <function ssl_wrap_socket at 0x7fe06b468670>
    │    └ None
    └ <urllib3.connection.HTTPSConnection object at 0x7fde7019f760>
  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
               └ <function _ssl_wrap_socket_impl at 0x7fe06b468820>
  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
           │           │           │                     └ 'wappass.baidu.com'
           │           │           └ <socket.socket [closed] fd=-1, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6>
           │           └ <function SSLContext.wrap_socket at 0x7fe08118de50>
           └ <ssl.SSLContext object at 0x7fdd21e08740>
  File "/usr/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
           │    │               └ <classmethod object at 0x7fe08c8cfaf0>
           │    └ <class 'ssl.SSLSocket'>
           └ <ssl.SSLContext object at 0x7fdd21e08740>
  File "/usr/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
    │    └ <function SSLSocket.do_handshake at 0x7fe08c8d2d30>
    └ <ssl.SSLSocket [closed] fd=-1, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6>
  File "/usr/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
    │    └ None
    └ <ssl.SSLSocket [closed] fd=-1, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6>

ssl.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1131)


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/home/chase/.local/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
           │    └ <function HTTPConnectionPool.urlopen at 0x7fe06b3fef70>
           └ <urllib3.connectionpool.HTTPSConnectionPool object at 0x7fde50448370>
  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
              │       └ <function Retry.increment at 0x7fe06b443280>
              └ Retry(total=0, connect=None, read=False, redirect=None, status=None)
  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
          │             │      │    │        │             └ 'unknown'
          │             │      │    │        └ <class 'urllib3.exceptions.ResponseError'>
          │             │      │    └ SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1131)'))
          │             │      └ '/static/captcha/tuxing.html?ak=2ef521ec36290baed33d66de9b16f625&backurl=http%3A%2F%2Ftieba.baidu.com%2Ff%2Fsearch%2Fres%3Fis...
          │             └ <urllib3.connectionpool.HTTPSConnectionPool object at 0x7fde50448370>
          └ <class 'urllib3.exceptions.MaxRetryError'>

urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='wappass.baidu.com', port=443): Max retries exceeded with url: /static/captcha/tuxing.html?ak=2ef521ec36290baed33d66de9b16f625&backurl=http%3A%2F%2Ftieba.baidu.com%2Ff%2Fsearch%2Fres%3Fisnew%3D1%26kw%3D%26qw%3D%25E7%25BB%25B4%25E4%25B9%259F%25E7%25BA%25B3%25E8%2581%2594%25E5%2590%2588%25E5%259B%25BD%25E4%25B8%25AD%25E6%2596%2587%25E6%2597%25A5%25E6%25B4%25BB%25E5%258A%25A8%25E6%258B%2589%25E5%25BC%2580%25E5%25B8%25B7%25E5%25B9%2595%26rn%3D10%26un%3D%26only_thread%3D0%26sm%3D1%26sd%3D%26ed%3D%26pn%3D5&timestamp=1654683700&signature=b368cf39642b1445bd5ed5cd3c9a7e88 (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1131)')))


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/usr/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7fe08f92ea60>
    └ <Thread(Thread-31059, started daemon 140587503011584)>
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7fe08f92e790>
    └ <Thread(Thread-31059, started daemon 140587503011584)>
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-31059, started daemon 140587503011584)>
    │    │        │    └ ('ProjectManager.run_func_by_thread',)
    │    │        └ <Thread(Thread-31059, started daemon 140587503011584)>
    │    └ <bound method ProjectManager.get_request_from_keywords_hot of <monitor.projectManager.ProjectManager object at 0x7fe063c65790>>
    └ <Thread(Thread-31059, started daemon 140587503011584)>

  File "/home/users/Scy/yuqing/spider/monitor/projectManager.py", line 833, in get_request_from_keywords_hot
    self.search_spider_manager.crawl_by_keyword(
    │    │                     └ <function SearchSpidersManager.crawl_by_keyword at 0x7fe063c71160>
    │    └ <monitor.spiderManager.SearchSpidersManager object at 0x7fe0638938b0>
    └ <monitor.projectManager.ProjectManager object at 0x7fe063c65790>

  File "/home/users/Scy/yuqing/spider/monitor/spiderManager.py", line 118, in crawl_by_keyword
    self.crawl_by_keyword_signal_platform(project_names, platform, keyword, crawl_time, project_times)
    │    │                                │              │         │        │           └ {'default': <monitor.TimeSection object at 0x7fe0639a2b80>}
    │    │                                │              │         │        └ <monitor.TimeSection object at 0x7fddf1f7b4f0>
    │    │                                │              │         └ '维也纳联合国中文日活动拉开帷幕'
    │    │                                │              └ '贴吧'
    │    │                                └ ['default']
    │    └ <function SearchSpidersManager.crawl_by_keyword_signal_platform at 0x7fe063c71280>
    └ <monitor.spiderManager.SearchSpidersManager object at 0x7fe0638938b0>

  File "/home/users/Scy/yuqing/spider/monitor/spiderManager.py", line 150, in crawl_by_keyword_signal_platform
    requests = self.get_request_from_keyword(platform, keyword_only, **crawl_time.to_dict())
               │    │                        │         │               │          └ <function TimeSection.to_dict at 0x7fe06b8931f0>
               │    │                        │         │               └ <monitor.TimeSection object at 0x7fddf1f7b4f0>
               │    │                        │         └ '维也纳联合国中文日活动拉开帷幕'
               │    │                        └ '贴吧'
               │    └ <function SearchSpidersManager.get_request_from_keyword at 0x7fe063c713a0>
               └ <monitor.spiderManager.SearchSpidersManager object at 0x7fe0638938b0>

  File "/home/users/Scy/yuqing/spider/monitor/spiderManager.py", line 214, in get_request_from_keyword
    for request in self.spiders[platform].get_request_from_keyword(headers, search_url, keyword, content_url,
                   │    │       │                                  │        │           │        └ None
                   │    │       │                                  │        │           └ '维也纳联合国中文日活动拉开帷幕'
                   │    │       │                                  │        └ <string.Template object at 0x7fddf0560820>
                   │    │       │                                  └ {'Connection': 'keep-alive', 'sec-ch-ua': "'Chromium';v='92',' Not A;Brand';v='99', 'Google Chrome';v='92'", 'sec-ch-ua-mobil...
                   │    │       └ '贴吧'
                   │    └ {'凤凰网': <monitor.searchSpiders.ifeng.Ifeng object at 0x7fe063893370>, '头条': <monitor.searchSpiders.toutiao.Toutiao object at ...
                   └ <monitor.spiderManager.SearchSpidersManager object at 0x7fe0638938b0>

> File "/home/users/Scy/yuqing/spider/monitor/searchSpiders/tieba.py", line 22, in get_request_from_keyword
    response = requests.get(url, headers=headers, timeout=50)
               │        │   │            └ {'Connection': 'keep-alive', 'sec-ch-ua': "'Chromium';v='92',' Not A;Brand';v='99', 'Google Chrome';v='92'", 'sec-ch-ua-mobil...
               │        │   └ 'https://tieba.baidu.com/f/search/res?isnew=1&kw=&qw=维也纳联合国中文日活动拉开帷幕&rn=10&un=&only_thread=0&sm=1&sd=&ed=&pn=5'
               │        └ <function get at 0x7fe06b2724c0>
               └ <module 'requests' from '/home/chase/.local/lib/python3.8/site-packages/requests/__init__.py'>

  File "/home/chase/.local/lib/python3.8/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
           │              │           │         └ {'headers': {'Connection': 'keep-alive', 'sec-ch-ua': "'Chromium';v='92',' Not A;Brand';v='99', 'Google Chrome';v='92'", 'sec...
           │              │           └ None
           │              └ 'https://tieba.baidu.com/f/search/res?isnew=1&kw=&qw=维也纳联合国中文日活动拉开帷幕&rn=10&un=&only_thread=0&sm=1&sd=&ed=&pn=5'
           └ <function request at 0x7fe06b268310>
  File "/home/chase/.local/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
           │       │              │           │      └ {'params': None, 'headers': {'Connection': 'keep-alive', 'sec-ch-ua': "'Chromium';v='92',' Not A;Brand';v='99', 'Google Chrom...
           │       │              │           └ 'https://tieba.baidu.com/f/search/res?isnew=1&kw=&qw=维也纳联合国中文日活动拉开帷幕&rn=10&un=&only_thread=0&sm=1&sd=&ed=&pn=5'
           │       │              └ 'get'
           │       └ <function Session.request at 0x7fe06b27bc10>
           └ <requests.sessions.Session object at 0x7fdd1bdffd30>
  File "/home/chase/.local/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
           │    │    │       └ {'timeout': 50, 'allow_redirects': True, 'verify': True, 'proxies': OrderedDict(), 'stream': False, 'cert': None}
           │    │    └ <PreparedRequest [GET]>
           │    └ <function Session.send at 0x7fe06b2720d0>
           └ <requests.sessions.Session object at 0x7fdd1bdffd30>
  File "/home/chase/.local/lib/python3.8/site-packages/requests/sessions.py", line 677, in send
    history = [resp for resp in gen]
                                └ <generator object SessionRedirectMixin.resolve_redirects at 0x7fdd0faae820>
  File "/home/chase/.local/lib/python3.8/site-packages/requests/sessions.py", line 677, in <listcomp>
    history = [resp for resp in gen]
  File "/home/chase/.local/lib/python3.8/site-packages/requests/sessions.py", line 237, in resolve_redirects
    resp = self.send(
           │    └ <function Session.send at 0x7fe06b2720d0>
           └ <requests.sessions.Session object at 0x7fdd1bdffd30>
  File "/home/chase/.local/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
        │       │    │          └ {'stream': False, 'timeout': 50, 'verify': True, 'cert': None, 'proxies': OrderedDict()}
        │       │    └ <PreparedRequest [GET]>
        │       └ <function HTTPAdapter.send at 0x7fe06b27b550>
        └ <requests.adapters.HTTPAdapter object at 0x7fde3072cc40>
  File "/home/chase/.local/lib/python3.8/site-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
          │                   └ <PreparedRequest [GET]>
          └ <class 'requests.exceptions.SSLError'>

requests.exceptions.SSLError: HTTPSConnectionPool(host='wappass.baidu.com', port=443): Max retries exceeded with url: /static/captcha/tuxing.html?ak=2ef521ec36290baed33d66de9b16f625&backurl=http%3A%2F%2Ftieba.baidu.com%2Ff%2Fsearch%2Fres%3Fisnew%3D1%26kw%3D%26qw%3D%25E7%25BB%25B4%25E4%25B9%259F%25E7%25BA%25B3%25E8%2581%2594%25E5%2590%2588%25E5%259B%25BD%25E4%25B8%25AD%25E6%2596%2587%25E6%2597%25A5%25E6%25B4%25BB%25E5%258A%25A8%25E6%258B%2589%25E5%25BC%2580%25E5%25B8%25B7%25E5%25B9%2595%26rn%3D10%26un%3D%26only_thread%3D0%26sm%3D1%26sd%3D%26ed%3D%26pn%3D5&timestamp=1654683700&signature=b368cf39642b1445bd5ed5cd3c9a7e88 (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1131)')))
2022-06-08 18:26:50.146 | ERROR    | monitor.searchSpiders.tieba:get_request_from_keyword:34 - E 贴吧错误HTTPSConnectionPool(host='wappass.baidu.com', port=443): Max retries exceeded with url: /static/captcha/tuxing.html?ak=2ef521ec36290baed33d66de9b16f625&backurl=http%3A%2F%2Ftieba.baidu.com%2Ff%2Fsearch%2Fres%3Fisnew%3D1%26kw%3D%26qw%3D%25E5%25AE%2589%25E5%25BE%25BD%25E7%259C%2581%25E5%2586%259B%25E5%258C%25BA%25E5%258A%25A0%25E5%25BC%25BA%25E4%25BB%25A5%25E9%259D%2592%25E5%25B9%25B4%25E4%25B8%25BA%25E4%25B8%25BB%25E7%259A%2584%25E6%25B0%2591%25E5%2585%25B5%25E6%2596%25B0%25E8%25B4%25A8%25E5%258A%259B%25E9%2587%258F%25E5%25BB%25BA%25E8%25AE%25BE%26rn%3D10%26un%3D%26only_thread%3D0%26sm%3D1%26sd%3D%26ed%3D%26pn%3D8&timestamp=1654684010&signature=5d13ecfb2532f393068edc1316c46b6e (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1131)')))
Traceback (most recent call last):

  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
                       │    └ <function HTTPConnectionPool._make_request at 0x7fe06b3fed30>
                       └ <urllib3.connectionpool.HTTPSConnectionPool object at 0x7fdd49c24490>
  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
    │    │              └ <urllib3.connection.HTTPSConnection object at 0x7fde306be790>
    │    └ <function HTTPSConnectionPool._validate_conn at 0x7fe06b3ff280>
    └ <urllib3.connectionpool.HTTPSConnectionPool object at 0x7fdd49c24490>
  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
    │    └ <function HTTPSConnection.connect at 0x7fe06b46d940>
    └ <urllib3.connection.HTTPSConnection object at 0x7fde306be790>
  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/connection.py", line 416, in connect
    self.sock = ssl_wrap_socket(
    │    │      └ <function ssl_wrap_socket at 0x7fe06b468670>
    │    └ None
    └ <urllib3.connection.HTTPSConnection object at 0x7fde306be790>
  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
               └ <function _ssl_wrap_socket_impl at 0x7fe06b468820>
  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
           │           │           │                     └ 'wappass.baidu.com'
           │           │           └ <socket.socket [closed] fd=-1, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6>
           │           └ <function SSLContext.wrap_socket at 0x7fe08118de50>
           └ <ssl.SSLContext object at 0x7fdeb051de40>
  File "/usr/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
           │    │               └ <classmethod object at 0x7fe08c8cfaf0>
           │    └ <class 'ssl.SSLSocket'>
           └ <ssl.SSLContext object at 0x7fdeb051de40>
  File "/usr/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
    │    └ <function SSLSocket.do_handshake at 0x7fe08c8d2d30>
    └ <ssl.SSLSocket [closed] fd=-1, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6>
  File "/usr/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
    │    └ None
    └ <ssl.SSLSocket [closed] fd=-1, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6>

ssl.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1131)


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/home/chase/.local/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
           │    └ <function HTTPConnectionPool.urlopen at 0x7fe06b3fef70>
           └ <urllib3.connectionpool.HTTPSConnectionPool object at 0x7fdd49c24490>
  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
              │       └ <function Retry.increment at 0x7fe06b443280>
              └ Retry(total=0, connect=None, read=False, redirect=None, status=None)
  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
          │             │      │    │        │             └ 'unknown'
          │             │      │    │        └ <class 'urllib3.exceptions.ResponseError'>
          │             │      │    └ SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1131)'))
          │             │      └ '/static/captcha/tuxing.html?ak=2ef521ec36290baed33d66de9b16f625&backurl=http%3A%2F%2Ftieba.baidu.com%2Ff%2Fsearch%2Fres%3Fis...
          │             └ <urllib3.connectionpool.HTTPSConnectionPool object at 0x7fdd49c24490>
          └ <class 'urllib3.exceptions.MaxRetryError'>

urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='wappass.baidu.com', port=443): Max retries exceeded with url: /static/captcha/tuxing.html?ak=2ef521ec36290baed33d66de9b16f625&backurl=http%3A%2F%2Ftieba.baidu.com%2Ff%2Fsearch%2Fres%3Fisnew%3D1%26kw%3D%26qw%3D%25E5%25AE%2589%25E5%25BE%25BD%25E7%259C%2581%25E5%2586%259B%25E5%258C%25BA%25E5%258A%25A0%25E5%25BC%25BA%25E4%25BB%25A5%25E9%259D%2592%25E5%25B9%25B4%25E4%25B8%25BA%25E4%25B8%25BB%25E7%259A%2584%25E6%25B0%2591%25E5%2585%25B5%25E6%2596%25B0%25E8%25B4%25A8%25E5%258A%259B%25E9%2587%258F%25E5%25BB%25BA%25E8%25AE%25BE%26rn%3D10%26un%3D%26only_thread%3D0%26sm%3D1%26sd%3D%26ed%3D%26pn%3D8&timestamp=1654684010&signature=5d13ecfb2532f393068edc1316c46b6e (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1131)')))


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/usr/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7fe08f92ea60>
    └ <Thread(Thread-33274, started daemon 140588290074368)>
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7fe08f92e790>
    └ <Thread(Thread-33274, started daemon 140588290074368)>
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-33274, started daemon 140588290074368)>
    │    │        │    └ ('ProjectManager.run_func_by_thread',)
    │    │        └ <Thread(Thread-33274, started daemon 140588290074368)>
    │    └ <bound method ProjectManager.get_request_from_keywords_hot of <monitor.projectManager.ProjectManager object at 0x7fe063c65790>>
    └ <Thread(Thread-33274, started daemon 140588290074368)>

  File "/home/users/Scy/yuqing/spider/monitor/projectManager.py", line 833, in get_request_from_keywords_hot
    self.search_spider_manager.crawl_by_keyword(
    │    │                     └ <function SearchSpidersManager.crawl_by_keyword at 0x7fe063c71160>
    │    └ <monitor.spiderManager.SearchSpidersManager object at 0x7fe0638938b0>
    └ <monitor.projectManager.ProjectManager object at 0x7fe063c65790>

  File "/home/users/Scy/yuqing/spider/monitor/spiderManager.py", line 118, in crawl_by_keyword
    self.crawl_by_keyword_signal_platform(project_names, platform, keyword, crawl_time, project_times)
    │    │                                │              │         │        │           └ {'default': <monitor.TimeSection object at 0x7fe0639a2b80>}
    │    │                                │              │         │        └ <monitor.TimeSection object at 0x7fdf547339d0>
    │    │                                │              │         └ '安徽省军区加强以青年为主的民兵新质力量建设'
    │    │                                │              └ '贴吧'
    │    │                                └ ['default']
    │    └ <function SearchSpidersManager.crawl_by_keyword_signal_platform at 0x7fe063c71280>
    └ <monitor.spiderManager.SearchSpidersManager object at 0x7fe0638938b0>

  File "/home/users/Scy/yuqing/spider/monitor/spiderManager.py", line 150, in crawl_by_keyword_signal_platform
    requests = self.get_request_from_keyword(platform, keyword_only, **crawl_time.to_dict())
               │    │                        │         │               │          └ <function TimeSection.to_dict at 0x7fe06b8931f0>
               │    │                        │         │               └ <monitor.TimeSection object at 0x7fdf547339d0>
               │    │                        │         └ '安徽省军区加强以青年为主的民兵新质力量建设'
               │    │                        └ '贴吧'
               │    └ <function SearchSpidersManager.get_request_from_keyword at 0x7fe063c713a0>
               └ <monitor.spiderManager.SearchSpidersManager object at 0x7fe0638938b0>

  File "/home/users/Scy/yuqing/spider/monitor/spiderManager.py", line 214, in get_request_from_keyword
    for request in self.spiders[platform].get_request_from_keyword(headers, search_url, keyword, content_url,
                   │    │       │                                  │        │           │        └ None
                   │    │       │                                  │        │           └ '安徽省军区加强以青年为主的民兵新质力量建设'
                   │    │       │                                  │        └ <string.Template object at 0x7fdd0f15f3d0>
                   │    │       │                                  └ {'Connection': 'keep-alive', 'sec-ch-ua': "'Chromium';v='92',' Not A;Brand';v='99', 'Google Chrome';v='92'", 'sec-ch-ua-mobil...
                   │    │       └ '贴吧'
                   │    └ {'凤凰网': <monitor.searchSpiders.ifeng.Ifeng object at 0x7fe063893370>, '头条': <monitor.searchSpiders.toutiao.Toutiao object at ...
                   └ <monitor.spiderManager.SearchSpidersManager object at 0x7fe0638938b0>

> File "/home/users/Scy/yuqing/spider/monitor/searchSpiders/tieba.py", line 22, in get_request_from_keyword
    response = requests.get(url, headers=headers, timeout=50)
               │        │   │            └ {'Connection': 'keep-alive', 'sec-ch-ua': "'Chromium';v='92',' Not A;Brand';v='99', 'Google Chrome';v='92'", 'sec-ch-ua-mobil...
               │        │   └ 'https://tieba.baidu.com/f/search/res?isnew=1&kw=&qw=安徽省军区加强以青年为主的民兵新质力量建设&rn=10&un=&only_thread=0&sm=1&sd=&ed=&pn=8'
               │        └ <function get at 0x7fe06b2724c0>
               └ <module 'requests' from '/home/chase/.local/lib/python3.8/site-packages/requests/__init__.py'>

  File "/home/chase/.local/lib/python3.8/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
           │              │           │         └ {'headers': {'Connection': 'keep-alive', 'sec-ch-ua': "'Chromium';v='92',' Not A;Brand';v='99', 'Google Chrome';v='92'", 'sec...
           │              │           └ None
           │              └ 'https://tieba.baidu.com/f/search/res?isnew=1&kw=&qw=安徽省军区加强以青年为主的民兵新质力量建设&rn=10&un=&only_thread=0&sm=1&sd=&ed=&pn=8'
           └ <function request at 0x7fe06b268310>
  File "/home/chase/.local/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
           │       │              │           │      └ {'params': None, 'headers': {'Connection': 'keep-alive', 'sec-ch-ua': "'Chromium';v='92',' Not A;Brand';v='99', 'Google Chrom...
           │       │              │           └ 'https://tieba.baidu.com/f/search/res?isnew=1&kw=&qw=安徽省军区加强以青年为主的民兵新质力量建设&rn=10&un=&only_thread=0&sm=1&sd=&ed=&pn=8'
           │       │              └ 'get'
           │       └ <function Session.request at 0x7fe06b27bc10>
           └ <requests.sessions.Session object at 0x7fdda2680a00>
  File "/home/chase/.local/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
           │    │    │       └ {'timeout': 50, 'allow_redirects': True, 'verify': True, 'proxies': OrderedDict(), 'stream': False, 'cert': None}
           │    │    └ <PreparedRequest [GET]>
           │    └ <function Session.send at 0x7fe06b2720d0>
           └ <requests.sessions.Session object at 0x7fdda2680a00>
  File "/home/chase/.local/lib/python3.8/site-packages/requests/sessions.py", line 677, in send
    history = [resp for resp in gen]
                                └ <generator object SessionRedirectMixin.resolve_redirects at 0x7fdef03a4040>
  File "/home/chase/.local/lib/python3.8/site-packages/requests/sessions.py", line 677, in <listcomp>
    history = [resp for resp in gen]
  File "/home/chase/.local/lib/python3.8/site-packages/requests/sessions.py", line 237, in resolve_redirects
    resp = self.send(
           │    └ <function Session.send at 0x7fe06b2720d0>
           └ <requests.sessions.Session object at 0x7fdda2680a00>
  File "/home/chase/.local/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
        │       │    │          └ {'stream': False, 'timeout': 50, 'verify': True, 'cert': None, 'proxies': OrderedDict()}
        │       │    └ <PreparedRequest [GET]>
        │       └ <function HTTPAdapter.send at 0x7fe06b27b550>
        └ <requests.adapters.HTTPAdapter object at 0x7fddf05e30a0>
  File "/home/chase/.local/lib/python3.8/site-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
          │                   └ <PreparedRequest [GET]>
          └ <class 'requests.exceptions.SSLError'>

requests.exceptions.SSLError: HTTPSConnectionPool(host='wappass.baidu.com', port=443): Max retries exceeded with url: /static/captcha/tuxing.html?ak=2ef521ec36290baed33d66de9b16f625&backurl=http%3A%2F%2Ftieba.baidu.com%2Ff%2Fsearch%2Fres%3Fisnew%3D1%26kw%3D%26qw%3D%25E5%25AE%2589%25E5%25BE%25BD%25E7%259C%2581%25E5%2586%259B%25E5%258C%25BA%25E5%258A%25A0%25E5%25BC%25BA%25E4%25BB%25A5%25E9%259D%2592%25E5%25B9%25B4%25E4%25B8%25BA%25E4%25B8%25BB%25E7%259A%2584%25E6%25B0%2591%25E5%2585%25B5%25E6%2596%25B0%25E8%25B4%25A8%25E5%258A%259B%25E9%2587%258F%25E5%25BB%25BA%25E8%25AE%25BE%26rn%3D10%26un%3D%26only_thread%3D0%26sm%3D1%26sd%3D%26ed%3D%26pn%3D8&timestamp=1654684010&signature=5d13ecfb2532f393068edc1316c46b6e (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1131)')))
2022-06-08 18:29:10.227 | ERROR    | monitor.searchSpiders.tieba:get_request_from_keyword:34 - E 贴吧错误HTTPSConnectionPool(host='wappass.baidu.com', port=443): Max retries exceeded with url: /static/captcha/tuxing.html?ak=2ef521ec36290baed33d66de9b16f625&backurl=http%3A%2F%2Ftieba.baidu.com%2Ff%2Fsearch%2Fres%3Fisnew%3D1%26kw%3D%26qw%3D%25E7%258E%258B%25E6%25AF%2585%25E4%25BC%259A%25E8%25A7%2581%25E4%25B9%258C%25E5%2585%25B9%25E5%2588%25AB%25E5%2585%258B%25E6%2596%25AF%25E5%259D%25A6%25E4%25BB%25A3%25E5%25A4%2596%25E9%2595%25BF%25E8%25AF%25BA%25E7%25BD%2597%25E5%25A4%25AB%26rn%3D10%26un%3D%26only_thread%3D0%26sm%3D1%26sd%3D%26ed%3D%26pn%3D21&timestamp=1654684150&signature=02cfde31fcfdec1e250853044e1a542e (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1131)')))
Traceback (most recent call last):

  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
                       │    └ <function HTTPConnectionPool._make_request at 0x7fe06b3fed30>
                       └ <urllib3.connectionpool.HTTPSConnectionPool object at 0x7fdef02ab5b0>
  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
    │    │              └ <urllib3.connection.HTTPSConnection object at 0x7fdce24affd0>
    │    └ <function HTTPSConnectionPool._validate_conn at 0x7fe06b3ff280>
    └ <urllib3.connectionpool.HTTPSConnectionPool object at 0x7fdef02ab5b0>
  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
    │    └ <function HTTPSConnection.connect at 0x7fe06b46d940>
    └ <urllib3.connection.HTTPSConnection object at 0x7fdce24affd0>
  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/connection.py", line 416, in connect
    self.sock = ssl_wrap_socket(
    │    │      └ <function ssl_wrap_socket at 0x7fe06b468670>
    │    └ None
    └ <urllib3.connection.HTTPSConnection object at 0x7fdce24affd0>
  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
               └ <function _ssl_wrap_socket_impl at 0x7fe06b468820>
  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
           │           │           │                     └ 'wappass.baidu.com'
           │           │           └ <socket.socket [closed] fd=-1, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6>
           │           └ <function SSLContext.wrap_socket at 0x7fe08118de50>
           └ <ssl.SSLContext object at 0x7fde903ba240>
  File "/usr/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
           │    │               └ <classmethod object at 0x7fe08c8cfaf0>
           │    └ <class 'ssl.SSLSocket'>
           └ <ssl.SSLContext object at 0x7fde903ba240>
  File "/usr/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
    │    └ <function SSLSocket.do_handshake at 0x7fe08c8d2d30>
    └ <ssl.SSLSocket [closed] fd=-1, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6>
  File "/usr/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
    │    └ None
    └ <ssl.SSLSocket [closed] fd=-1, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6>

ssl.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1131)


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/home/chase/.local/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
           │    └ <function HTTPConnectionPool.urlopen at 0x7fe06b3fef70>
           └ <urllib3.connectionpool.HTTPSConnectionPool object at 0x7fdef02ab5b0>
  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
              │       └ <function Retry.increment at 0x7fe06b443280>
              └ Retry(total=0, connect=None, read=False, redirect=None, status=None)
  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
          │             │      │    │        │             └ 'unknown'
          │             │      │    │        └ <class 'urllib3.exceptions.ResponseError'>
          │             │      │    └ SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1131)'))
          │             │      └ '/static/captcha/tuxing.html?ak=2ef521ec36290baed33d66de9b16f625&backurl=http%3A%2F%2Ftieba.baidu.com%2Ff%2Fsearch%2Fres%3Fis...
          │             └ <urllib3.connectionpool.HTTPSConnectionPool object at 0x7fdef02ab5b0>
          └ <class 'urllib3.exceptions.MaxRetryError'>

urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='wappass.baidu.com', port=443): Max retries exceeded with url: /static/captcha/tuxing.html?ak=2ef521ec36290baed33d66de9b16f625&backurl=http%3A%2F%2Ftieba.baidu.com%2Ff%2Fsearch%2Fres%3Fisnew%3D1%26kw%3D%26qw%3D%25E7%258E%258B%25E6%25AF%2585%25E4%25BC%259A%25E8%25A7%2581%25E4%25B9%258C%25E5%2585%25B9%25E5%2588%25AB%25E5%2585%258B%25E6%2596%25AF%25E5%259D%25A6%25E4%25BB%25A3%25E5%25A4%2596%25E9%2595%25BF%25E8%25AF%25BA%25E7%25BD%2597%25E5%25A4%25AB%26rn%3D10%26un%3D%26only_thread%3D0%26sm%3D1%26sd%3D%26ed%3D%26pn%3D21&timestamp=1654684150&signature=02cfde31fcfdec1e250853044e1a542e (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1131)')))


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/usr/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7fe08f92ea60>
    └ <Thread(Thread-33048, started daemon 140593355265792)>
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7fe08f92e790>
    └ <Thread(Thread-33048, started daemon 140593355265792)>
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-33048, started daemon 140593355265792)>
    │    │        │    └ ('ProjectManager.run_func_by_thread',)
    │    │        └ <Thread(Thread-33048, started daemon 140593355265792)>
    │    └ <bound method ProjectManager.get_request_from_keywords_hot of <monitor.projectManager.ProjectManager object at 0x7fe063c65790>>
    └ <Thread(Thread-33048, started daemon 140593355265792)>

  File "/home/users/Scy/yuqing/spider/monitor/projectManager.py", line 833, in get_request_from_keywords_hot
    self.search_spider_manager.crawl_by_keyword(
    │    │                     └ <function SearchSpidersManager.crawl_by_keyword at 0x7fe063c71160>
    │    └ <monitor.spiderManager.SearchSpidersManager object at 0x7fe0638938b0>
    └ <monitor.projectManager.ProjectManager object at 0x7fe063c65790>

  File "/home/users/Scy/yuqing/spider/monitor/spiderManager.py", line 118, in crawl_by_keyword
    self.crawl_by_keyword_signal_platform(project_names, platform, keyword, crawl_time, project_times)
    │    │                                │              │         │        │           └ {'default': <monitor.TimeSection object at 0x7fe0639a2b80>}
    │    │                                │              │         │        └ <monitor.TimeSection object at 0x7fdcf7f53ca0>
    │    │                                │              │         └ '王毅会见乌兹别克斯坦代外长诺罗夫'
    │    │                                │              └ '贴吧'
    │    │                                └ ['default']
    │    └ <function SearchSpidersManager.crawl_by_keyword_signal_platform at 0x7fe063c71280>
    └ <monitor.spiderManager.SearchSpidersManager object at 0x7fe0638938b0>

  File "/home/users/Scy/yuqing/spider/monitor/spiderManager.py", line 150, in crawl_by_keyword_signal_platform
    requests = self.get_request_from_keyword(platform, keyword_only, **crawl_time.to_dict())
               │    │                        │         │               │          └ <function TimeSection.to_dict at 0x7fe06b8931f0>
               │    │                        │         │               └ <monitor.TimeSection object at 0x7fdcf7f53ca0>
               │    │                        │         └ '王毅会见乌兹别克斯坦代外长诺罗夫'
               │    │                        └ '贴吧'
               │    └ <function SearchSpidersManager.get_request_from_keyword at 0x7fe063c713a0>
               └ <monitor.spiderManager.SearchSpidersManager object at 0x7fe0638938b0>

  File "/home/users/Scy/yuqing/spider/monitor/spiderManager.py", line 214, in get_request_from_keyword
    for request in self.spiders[platform].get_request_from_keyword(headers, search_url, keyword, content_url,
                   │    │       │                                  │        │           │        └ None
                   │    │       │                                  │        │           └ '王毅会见乌兹别克斯坦代外长诺罗夫'
                   │    │       │                                  │        └ <string.Template object at 0x7fdeb05881c0>
                   │    │       │                                  └ {'Connection': 'keep-alive', 'sec-ch-ua': "'Chromium';v='92',' Not A;Brand';v='99', 'Google Chrome';v='92'", 'sec-ch-ua-mobil...
                   │    │       └ '贴吧'
                   │    └ {'凤凰网': <monitor.searchSpiders.ifeng.Ifeng object at 0x7fe063893370>, '头条': <monitor.searchSpiders.toutiao.Toutiao object at ...
                   └ <monitor.spiderManager.SearchSpidersManager object at 0x7fe0638938b0>

> File "/home/users/Scy/yuqing/spider/monitor/searchSpiders/tieba.py", line 22, in get_request_from_keyword
    response = requests.get(url, headers=headers, timeout=50)
               │        │   │            └ {'Connection': 'keep-alive', 'sec-ch-ua': "'Chromium';v='92',' Not A;Brand';v='99', 'Google Chrome';v='92'", 'sec-ch-ua-mobil...
               │        │   └ 'https://tieba.baidu.com/f/search/res?isnew=1&kw=&qw=王毅会见乌兹别克斯坦代外长诺罗夫&rn=10&un=&only_thread=0&sm=1&sd=&ed=&pn=21'
               │        └ <function get at 0x7fe06b2724c0>
               └ <module 'requests' from '/home/chase/.local/lib/python3.8/site-packages/requests/__init__.py'>

  File "/home/chase/.local/lib/python3.8/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
           │              │           │         └ {'headers': {'Connection': 'keep-alive', 'sec-ch-ua': "'Chromium';v='92',' Not A;Brand';v='99', 'Google Chrome';v='92'", 'sec...
           │              │           └ None
           │              └ 'https://tieba.baidu.com/f/search/res?isnew=1&kw=&qw=王毅会见乌兹别克斯坦代外长诺罗夫&rn=10&un=&only_thread=0&sm=1&sd=&ed=&pn=21'
           └ <function request at 0x7fe06b268310>
  File "/home/chase/.local/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
           │       │              │           │      └ {'params': None, 'headers': {'Connection': 'keep-alive', 'sec-ch-ua': "'Chromium';v='92',' Not A;Brand';v='99', 'Google Chrom...
           │       │              │           └ 'https://tieba.baidu.com/f/search/res?isnew=1&kw=&qw=王毅会见乌兹别克斯坦代外长诺罗夫&rn=10&un=&only_thread=0&sm=1&sd=&ed=&pn=21'
           │       │              └ 'get'
           │       └ <function Session.request at 0x7fe06b27bc10>
           └ <requests.sessions.Session object at 0x7fdef062fd00>
  File "/home/chase/.local/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
           │    │    │       └ {'timeout': 50, 'allow_redirects': True, 'verify': True, 'proxies': OrderedDict(), 'stream': False, 'cert': None}
           │    │    └ <PreparedRequest [GET]>
           │    └ <function Session.send at 0x7fe06b2720d0>
           └ <requests.sessions.Session object at 0x7fdef062fd00>
  File "/home/chase/.local/lib/python3.8/site-packages/requests/sessions.py", line 677, in send
    history = [resp for resp in gen]
                                └ <generator object SessionRedirectMixin.resolve_redirects at 0x7fdceff412e0>
  File "/home/chase/.local/lib/python3.8/site-packages/requests/sessions.py", line 677, in <listcomp>
    history = [resp for resp in gen]
  File "/home/chase/.local/lib/python3.8/site-packages/requests/sessions.py", line 237, in resolve_redirects
    resp = self.send(
           │    └ <function Session.send at 0x7fe06b2720d0>
           └ <requests.sessions.Session object at 0x7fdef062fd00>
  File "/home/chase/.local/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
        │       │    │          └ {'stream': False, 'timeout': 50, 'verify': True, 'cert': None, 'proxies': OrderedDict()}
        │       │    └ <PreparedRequest [GET]>
        │       └ <function HTTPAdapter.send at 0x7fe06b27b550>
        └ <requests.adapters.HTTPAdapter object at 0x7fde507c4400>
  File "/home/chase/.local/lib/python3.8/site-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
          │                   └ <PreparedRequest [GET]>
          └ <class 'requests.exceptions.SSLError'>

requests.exceptions.SSLError: HTTPSConnectionPool(host='wappass.baidu.com', port=443): Max retries exceeded with url: /static/captcha/tuxing.html?ak=2ef521ec36290baed33d66de9b16f625&backurl=http%3A%2F%2Ftieba.baidu.com%2Ff%2Fsearch%2Fres%3Fisnew%3D1%26kw%3D%26qw%3D%25E7%258E%258B%25E6%25AF%2585%25E4%25BC%259A%25E8%25A7%2581%25E4%25B9%258C%25E5%2585%25B9%25E5%2588%25AB%25E5%2585%258B%25E6%2596%25AF%25E5%259D%25A6%25E4%25BB%25A3%25E5%25A4%2596%25E9%2595%25BF%25E8%25AF%25BA%25E7%25BD%2597%25E5%25A4%25AB%26rn%3D10%26un%3D%26only_thread%3D0%26sm%3D1%26sd%3D%26ed%3D%26pn%3D21&timestamp=1654684150&signature=02cfde31fcfdec1e250853044e1a542e (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1131)')))
