2022-06-08 18:29:30.278 | ERROR    | monitor.searchSpiders.tieba:get_request_from_keyword:34 - E 贴吧错误HTTPSConnectionPool(host='wappass.baidu.com', port=443): Max retries exceeded with url: /static/captcha/tuxing.html?ak=2ef521ec36290baed33d66de9b16f625&backurl=http%3A%2F%2Ftieba.baidu.com%2Ff%2Fsearch%2Fres%3Fisnew%3D1%26kw%3D%26qw%3D%25E9%259D%259E%25E6%25B4%25B2%25E6%259E%2581%25E7%25AB%25AF%25E7%25BB%2584%25E7%25BB%2587%25E6%25AD%25A6%25E5%2599%25A8%25E6%259D%25A5%25E6%25BA%2590%25E5%25BC%2595%25E5%2585%25B3%25E6%25B3%25A8%26rn%3D10%26un%3D%26only_thread%3D0%26sm%3D1%26sd%3D%26ed%3D%26pn%3D20&timestamp=1654684170&signature=1b4a8469f670c0b809ea51f39036c0d0 (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1131)')))
Traceback (most recent call last):

  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
                       │    └ <function HTTPConnectionPool._make_request at 0x7fe06b3fed30>
                       └ <urllib3.connectionpool.HTTPSConnectionPool object at 0x7fdda2747340>
  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
    │    │              └ <urllib3.connection.HTTPSConnection object at 0x7fde703c3a30>
    │    └ <function HTTPSConnectionPool._validate_conn at 0x7fe06b3ff280>
    └ <urllib3.connectionpool.HTTPSConnectionPool object at 0x7fdda2747340>
  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
    │    └ <function HTTPSConnection.connect at 0x7fe06b46d940>
    └ <urllib3.connection.HTTPSConnection object at 0x7fde703c3a30>
  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/connection.py", line 416, in connect
    self.sock = ssl_wrap_socket(
    │    │      └ <function ssl_wrap_socket at 0x7fe06b468670>
    │    └ None
    └ <urllib3.connection.HTTPSConnection object at 0x7fde703c3a30>
  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
               └ <function _ssl_wrap_socket_impl at 0x7fe06b468820>
  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
           │           │           │                     └ 'wappass.baidu.com'
           │           │           └ <socket.socket [closed] fd=-1, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6>
           │           └ <function SSLContext.wrap_socket at 0x7fe08118de50>
           └ <ssl.SSLContext object at 0x7fde3068e1c0>
  File "/usr/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
           │    │               └ <classmethod object at 0x7fe08c8cfaf0>
           │    └ <class 'ssl.SSLSocket'>
           └ <ssl.SSLContext object at 0x7fde3068e1c0>
  File "/usr/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
    │    └ <function SSLSocket.do_handshake at 0x7fe08c8d2d30>
    └ <ssl.SSLSocket [closed] fd=-1, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6>
  File "/usr/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
    │    └ None
    └ <ssl.SSLSocket [closed] fd=-1, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6>

ssl.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1131)


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/home/chase/.local/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
           │    └ <function HTTPConnectionPool.urlopen at 0x7fe06b3fef70>
           └ <urllib3.connectionpool.HTTPSConnectionPool object at 0x7fdda2747340>
  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
              │       └ <function Retry.increment at 0x7fe06b443280>
              └ Retry(total=0, connect=None, read=False, redirect=None, status=None)
  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
          │             │      │    │        │             └ 'unknown'
          │             │      │    │        └ <class 'urllib3.exceptions.ResponseError'>
          │             │      │    └ SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1131)'))
          │             │      └ '/static/captcha/tuxing.html?ak=2ef521ec36290baed33d66de9b16f625&backurl=http%3A%2F%2Ftieba.baidu.com%2Ff%2Fsearch%2Fres%3Fis...
          │             └ <urllib3.connectionpool.HTTPSConnectionPool object at 0x7fdda2747340>
          └ <class 'urllib3.exceptions.MaxRetryError'>

urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='wappass.baidu.com', port=443): Max retries exceeded with url: /static/captcha/tuxing.html?ak=2ef521ec36290baed33d66de9b16f625&backurl=http%3A%2F%2Ftieba.baidu.com%2Ff%2Fsearch%2Fres%3Fisnew%3D1%26kw%3D%26qw%3D%25E9%259D%259E%25E6%25B4%25B2%25E6%259E%2581%25E7%25AB%25AF%25E7%25BB%2584%25E7%25BB%2587%25E6%25AD%25A6%25E5%2599%25A8%25E6%259D%25A5%25E6%25BA%2590%25E5%25BC%2595%25E5%2585%25B3%25E6%25B3%25A8%26rn%3D10%26un%3D%26only_thread%3D0%26sm%3D1%26sd%3D%26ed%3D%26pn%3D20&timestamp=1654684170&signature=1b4a8469f670c0b809ea51f39036c0d0 (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1131)')))


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/usr/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7fe08f92ea60>
    └ <Thread(Thread-31716, started daemon 140593405622016)>
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7fe08f92e790>
    └ <Thread(Thread-31716, started daemon 140593405622016)>
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-31716, started daemon 140593405622016)>
    │    │        │    └ ('ProjectManager.run_func_by_thread',)
    │    │        └ <Thread(Thread-31716, started daemon 140593405622016)>
    │    └ <bound method ProjectManager.get_request_from_keywords_hot of <monitor.projectManager.ProjectManager object at 0x7fe063c65790>>
    └ <Thread(Thread-31716, started daemon 140593405622016)>

  File "/home/users/Scy/yuqing/spider/monitor/projectManager.py", line 833, in get_request_from_keywords_hot
    self.search_spider_manager.crawl_by_keyword(
    │    │                     └ <function SearchSpidersManager.crawl_by_keyword at 0x7fe063c71160>
    │    └ <monitor.spiderManager.SearchSpidersManager object at 0x7fe0638938b0>
    └ <monitor.projectManager.ProjectManager object at 0x7fe063c65790>

  File "/home/users/Scy/yuqing/spider/monitor/spiderManager.py", line 118, in crawl_by_keyword
    self.crawl_by_keyword_signal_platform(project_names, platform, keyword, crawl_time, project_times)
    │    │                                │              │         │        │           └ {'default': <monitor.TimeSection object at 0x7fe0639a2b80>}
    │    │                                │              │         │        └ <monitor.TimeSection object at 0x7fded05c56a0>
    │    │                                │              │         └ '非洲极端组织武器来源引关注'
    │    │                                │              └ '贴吧'
    │    │                                └ ['default']
    │    └ <function SearchSpidersManager.crawl_by_keyword_signal_platform at 0x7fe063c71280>
    └ <monitor.spiderManager.SearchSpidersManager object at 0x7fe0638938b0>

  File "/home/users/Scy/yuqing/spider/monitor/spiderManager.py", line 150, in crawl_by_keyword_signal_platform
    requests = self.get_request_from_keyword(platform, keyword_only, **crawl_time.to_dict())
               │    │                        │         │               │          └ <function TimeSection.to_dict at 0x7fe06b8931f0>
               │    │                        │         │               └ <monitor.TimeSection object at 0x7fded05c56a0>
               │    │                        │         └ '非洲极端组织武器来源引关注'
               │    │                        └ '贴吧'
               │    └ <function SearchSpidersManager.get_request_from_keyword at 0x7fe063c713a0>
               └ <monitor.spiderManager.SearchSpidersManager object at 0x7fe0638938b0>

  File "/home/users/Scy/yuqing/spider/monitor/spiderManager.py", line 214, in get_request_from_keyword
    for request in self.spiders[platform].get_request_from_keyword(headers, search_url, keyword, content_url,
                   │    │       │                                  │        │           │        └ None
                   │    │       │                                  │        │           └ '非洲极端组织武器来源引关注'
                   │    │       │                                  │        └ <string.Template object at 0x7fde700394f0>
                   │    │       │                                  └ {'Connection': 'keep-alive', 'sec-ch-ua': "'Chromium';v='92',' Not A;Brand';v='99', 'Google Chrome';v='92'", 'sec-ch-ua-mobil...
                   │    │       └ '贴吧'
                   │    └ {'凤凰网': <monitor.searchSpiders.ifeng.Ifeng object at 0x7fe063893370>, '头条': <monitor.searchSpiders.toutiao.Toutiao object at ...
                   └ <monitor.spiderManager.SearchSpidersManager object at 0x7fe0638938b0>

> File "/home/users/Scy/yuqing/spider/monitor/searchSpiders/tieba.py", line 22, in get_request_from_keyword
    response = requests.get(url, headers=headers, timeout=50)
               │        │   │            └ {'Connection': 'keep-alive', 'sec-ch-ua': "'Chromium';v='92',' Not A;Brand';v='99', 'Google Chrome';v='92'", 'sec-ch-ua-mobil...
               │        │   └ 'https://tieba.baidu.com/f/search/res?isnew=1&kw=&qw=非洲极端组织武器来源引关注&rn=10&un=&only_thread=0&sm=1&sd=&ed=&pn=20'
               │        └ <function get at 0x7fe06b2724c0>
               └ <module 'requests' from '/home/chase/.local/lib/python3.8/site-packages/requests/__init__.py'>

  File "/home/chase/.local/lib/python3.8/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
           │              │           │         └ {'headers': {'Connection': 'keep-alive', 'sec-ch-ua': "'Chromium';v='92',' Not A;Brand';v='99', 'Google Chrome';v='92'", 'sec...
           │              │           └ None
           │              └ 'https://tieba.baidu.com/f/search/res?isnew=1&kw=&qw=非洲极端组织武器来源引关注&rn=10&un=&only_thread=0&sm=1&sd=&ed=&pn=20'
           └ <function request at 0x7fe06b268310>
  File "/home/chase/.local/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
           │       │              │           │      └ {'params': None, 'headers': {'Connection': 'keep-alive', 'sec-ch-ua': "'Chromium';v='92',' Not A;Brand';v='99', 'Google Chrom...
           │       │              │           └ 'https://tieba.baidu.com/f/search/res?isnew=1&kw=&qw=非洲极端组织武器来源引关注&rn=10&un=&only_thread=0&sm=1&sd=&ed=&pn=20'
           │       │              └ 'get'
           │       └ <function Session.request at 0x7fe06b27bc10>
           └ <requests.sessions.Session object at 0x7fde50299d90>
  File "/home/chase/.local/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
           │    │    │       └ {'timeout': 50, 'allow_redirects': True, 'verify': True, 'proxies': OrderedDict(), 'stream': False, 'cert': None}
           │    │    └ <PreparedRequest [GET]>
           │    └ <function Session.send at 0x7fe06b2720d0>
           └ <requests.sessions.Session object at 0x7fde50299d90>
  File "/home/chase/.local/lib/python3.8/site-packages/requests/sessions.py", line 677, in send
    history = [resp for resp in gen]
                                └ <generator object SessionRedirectMixin.resolve_redirects at 0x7fde902887b0>
  File "/home/chase/.local/lib/python3.8/site-packages/requests/sessions.py", line 677, in <listcomp>
    history = [resp for resp in gen]
  File "/home/chase/.local/lib/python3.8/site-packages/requests/sessions.py", line 237, in resolve_redirects
    resp = self.send(
           │    └ <function Session.send at 0x7fe06b2720d0>
           └ <requests.sessions.Session object at 0x7fde50299d90>
  File "/home/chase/.local/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
        │       │    │          └ {'stream': False, 'timeout': 50, 'verify': True, 'cert': None, 'proxies': OrderedDict()}
        │       │    └ <PreparedRequest [GET]>
        │       └ <function HTTPAdapter.send at 0x7fe06b27b550>
        └ <requests.adapters.HTTPAdapter object at 0x7fdcd323fa60>
  File "/home/chase/.local/lib/python3.8/site-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
          │                   └ <PreparedRequest [GET]>
          └ <class 'requests.exceptions.SSLError'>

requests.exceptions.SSLError: HTTPSConnectionPool(host='wappass.baidu.com', port=443): Max retries exceeded with url: /static/captcha/tuxing.html?ak=2ef521ec36290baed33d66de9b16f625&backurl=http%3A%2F%2Ftieba.baidu.com%2Ff%2Fsearch%2Fres%3Fisnew%3D1%26kw%3D%26qw%3D%25E9%259D%259E%25E6%25B4%25B2%25E6%259E%2581%25E7%25AB%25AF%25E7%25BB%2584%25E7%25BB%2587%25E6%25AD%25A6%25E5%2599%25A8%25E6%259D%25A5%25E6%25BA%2590%25E5%25BC%2595%25E5%2585%25B3%25E6%25B3%25A8%26rn%3D10%26un%3D%26only_thread%3D0%26sm%3D1%26sd%3D%26ed%3D%26pn%3D20&timestamp=1654684170&signature=1b4a8469f670c0b809ea51f39036c0d0 (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1131)')))
2022-06-08 18:34:10.559 | ERROR    | monitor.searchSpiders.tieba:get_request_from_keyword:34 - E 贴吧错误HTTPSConnectionPool(host='wappass.baidu.com', port=443): Max retries exceeded with url: /static/captcha/tuxing.html?ak=2ef521ec36290baed33d66de9b16f625&backurl=http%3A%2F%2Ftieba.baidu.com%2Ff%2Fsearch%2Fres%3Fisnew%3D1%26kw%3D%26qw%3D%25E9%259D%259E%25E6%25B4%25B2%25E6%259E%2581%25E7%25AB%25AF%25E7%25BB%2584%25E7%25BB%2587%25E6%25AD%25A6%25E5%2599%25A8%25E6%259D%25A5%25E6%25BA%2590%25E5%25BC%2595%25E5%2585%25B3%25E6%25B3%25A8%26rn%3D10%26un%3D%26only_thread%3D0%26sm%3D1%26sd%3D%26ed%3D%26pn%3D5&timestamp=1654684450&signature=4bd37f01bebd49e09f1e7205ea8e0d55 (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1131)')))
Traceback (most recent call last):

  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
                       │    └ <function HTTPConnectionPool._make_request at 0x7fe06b3fed30>
                       └ <urllib3.connectionpool.HTTPSConnectionPool object at 0x7fdd3a650340>
  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
    │    │              └ <urllib3.connection.HTTPSConnection object at 0x7fde90043c10>
    │    └ <function HTTPSConnectionPool._validate_conn at 0x7fe06b3ff280>
    └ <urllib3.connectionpool.HTTPSConnectionPool object at 0x7fdd3a650340>
  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
    │    └ <function HTTPSConnection.connect at 0x7fe06b46d940>
    └ <urllib3.connection.HTTPSConnection object at 0x7fde90043c10>
  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/connection.py", line 416, in connect
    self.sock = ssl_wrap_socket(
    │    │      └ <function ssl_wrap_socket at 0x7fe06b468670>
    │    └ None
    └ <urllib3.connection.HTTPSConnection object at 0x7fde90043c10>
  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
               └ <function _ssl_wrap_socket_impl at 0x7fe06b468820>
  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
           │           │           │                     └ 'wappass.baidu.com'
           │           │           └ <socket.socket [closed] fd=-1, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6>
           │           └ <function SSLContext.wrap_socket at 0x7fe08118de50>
           └ <ssl.SSLContext object at 0x7fdceae4f7c0>
  File "/usr/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
           │    │               └ <classmethod object at 0x7fe08c8cfaf0>
           │    └ <class 'ssl.SSLSocket'>
           └ <ssl.SSLContext object at 0x7fdceae4f7c0>
  File "/usr/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
    │    └ <function SSLSocket.do_handshake at 0x7fe08c8d2d30>
    └ <ssl.SSLSocket [closed] fd=-1, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6>
  File "/usr/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
    │    └ None
    └ <ssl.SSLSocket [closed] fd=-1, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6>

ssl.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1131)


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/home/chase/.local/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
           │    └ <function HTTPConnectionPool.urlopen at 0x7fe06b3fef70>
           └ <urllib3.connectionpool.HTTPSConnectionPool object at 0x7fdd3a650340>
  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
              │       └ <function Retry.increment at 0x7fe06b443280>
              └ Retry(total=0, connect=None, read=False, redirect=None, status=None)
  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
          │             │      │    │        │             └ 'unknown'
          │             │      │    │        └ <class 'urllib3.exceptions.ResponseError'>
          │             │      │    └ SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1131)'))
          │             │      └ '/static/captcha/tuxing.html?ak=2ef521ec36290baed33d66de9b16f625&backurl=http%3A%2F%2Ftieba.baidu.com%2Ff%2Fsearch%2Fres%3Fis...
          │             └ <urllib3.connectionpool.HTTPSConnectionPool object at 0x7fdd3a650340>
          └ <class 'urllib3.exceptions.MaxRetryError'>

urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='wappass.baidu.com', port=443): Max retries exceeded with url: /static/captcha/tuxing.html?ak=2ef521ec36290baed33d66de9b16f625&backurl=http%3A%2F%2Ftieba.baidu.com%2Ff%2Fsearch%2Fres%3Fisnew%3D1%26kw%3D%26qw%3D%25E9%259D%259E%25E6%25B4%25B2%25E6%259E%2581%25E7%25AB%25AF%25E7%25BB%2584%25E7%25BB%2587%25E6%25AD%25A6%25E5%2599%25A8%25E6%259D%25A5%25E6%25BA%2590%25E5%25BC%2595%25E5%2585%25B3%25E6%25B3%25A8%26rn%3D10%26un%3D%26only_thread%3D0%26sm%3D1%26sd%3D%26ed%3D%26pn%3D5&timestamp=1654684450&signature=4bd37f01bebd49e09f1e7205ea8e0d55 (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1131)')))


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/usr/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7fe08f92ea60>
    └ <Thread(Thread-31887, started daemon 140588639942400)>
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7fe08f92e790>
    └ <Thread(Thread-31887, started daemon 140588639942400)>
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-31887, started daemon 140588639942400)>
    │    │        │    └ ('ProjectManager.run_func_by_thread',)
    │    │        └ <Thread(Thread-31887, started daemon 140588639942400)>
    │    └ <bound method ProjectManager.get_request_from_keywords_hot of <monitor.projectManager.ProjectManager object at 0x7fe063c65790>>
    └ <Thread(Thread-31887, started daemon 140588639942400)>

  File "/home/users/Scy/yuqing/spider/monitor/projectManager.py", line 833, in get_request_from_keywords_hot
    self.search_spider_manager.crawl_by_keyword(
    │    │                     └ <function SearchSpidersManager.crawl_by_keyword at 0x7fe063c71160>
    │    └ <monitor.spiderManager.SearchSpidersManager object at 0x7fe0638938b0>
    └ <monitor.projectManager.ProjectManager object at 0x7fe063c65790>

  File "/home/users/Scy/yuqing/spider/monitor/spiderManager.py", line 118, in crawl_by_keyword
    self.crawl_by_keyword_signal_platform(project_names, platform, keyword, crawl_time, project_times)
    │    │                                │              │         │        │           └ {'default': <monitor.TimeSection object at 0x7fe0639a2b80>}
    │    │                                │              │         │        └ <monitor.TimeSection object at 0x7fdd06298250>
    │    │                                │              │         └ '非洲极端组织武器来源引关注'
    │    │                                │              └ '贴吧'
    │    │                                └ ['default']
    │    └ <function SearchSpidersManager.crawl_by_keyword_signal_platform at 0x7fe063c71280>
    └ <monitor.spiderManager.SearchSpidersManager object at 0x7fe0638938b0>

  File "/home/users/Scy/yuqing/spider/monitor/spiderManager.py", line 150, in crawl_by_keyword_signal_platform
    requests = self.get_request_from_keyword(platform, keyword_only, **crawl_time.to_dict())
               │    │                        │         │               │          └ <function TimeSection.to_dict at 0x7fe06b8931f0>
               │    │                        │         │               └ <monitor.TimeSection object at 0x7fdd06298250>
               │    │                        │         └ '非洲极端组织武器来源引关注'
               │    │                        └ '贴吧'
               │    └ <function SearchSpidersManager.get_request_from_keyword at 0x7fe063c713a0>
               └ <monitor.spiderManager.SearchSpidersManager object at 0x7fe0638938b0>

  File "/home/users/Scy/yuqing/spider/monitor/spiderManager.py", line 214, in get_request_from_keyword
    for request in self.spiders[platform].get_request_from_keyword(headers, search_url, keyword, content_url,
                   │    │       │                                  │        │           │        └ None
                   │    │       │                                  │        │           └ '非洲极端组织武器来源引关注'
                   │    │       │                                  │        └ <string.Template object at 0x7fdf103399d0>
                   │    │       │                                  └ {'Connection': 'keep-alive', 'sec-ch-ua': "'Chromium';v='92',' Not A;Brand';v='99', 'Google Chrome';v='92'", 'sec-ch-ua-mobil...
                   │    │       └ '贴吧'
                   │    └ {'凤凰网': <monitor.searchSpiders.ifeng.Ifeng object at 0x7fe063893370>, '头条': <monitor.searchSpiders.toutiao.Toutiao object at ...
                   └ <monitor.spiderManager.SearchSpidersManager object at 0x7fe0638938b0>

> File "/home/users/Scy/yuqing/spider/monitor/searchSpiders/tieba.py", line 22, in get_request_from_keyword
    response = requests.get(url, headers=headers, timeout=50)
               │        │   │            └ {'Connection': 'keep-alive', 'sec-ch-ua': "'Chromium';v='92',' Not A;Brand';v='99', 'Google Chrome';v='92'", 'sec-ch-ua-mobil...
               │        │   └ 'https://tieba.baidu.com/f/search/res?isnew=1&kw=&qw=非洲极端组织武器来源引关注&rn=10&un=&only_thread=0&sm=1&sd=&ed=&pn=5'
               │        └ <function get at 0x7fe06b2724c0>
               └ <module 'requests' from '/home/chase/.local/lib/python3.8/site-packages/requests/__init__.py'>

  File "/home/chase/.local/lib/python3.8/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
           │              │           │         └ {'headers': {'Connection': 'keep-alive', 'sec-ch-ua': "'Chromium';v='92',' Not A;Brand';v='99', 'Google Chrome';v='92'", 'sec...
           │              │           └ None
           │              └ 'https://tieba.baidu.com/f/search/res?isnew=1&kw=&qw=非洲极端组织武器来源引关注&rn=10&un=&only_thread=0&sm=1&sd=&ed=&pn=5'
           └ <function request at 0x7fe06b268310>
  File "/home/chase/.local/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
           │       │              │           │      └ {'params': None, 'headers': {'Connection': 'keep-alive', 'sec-ch-ua': "'Chromium';v='92',' Not A;Brand';v='99', 'Google Chrom...
           │       │              │           └ 'https://tieba.baidu.com/f/search/res?isnew=1&kw=&qw=非洲极端组织武器来源引关注&rn=10&un=&only_thread=0&sm=1&sd=&ed=&pn=5'
           │       │              └ 'get'
           │       └ <function Session.request at 0x7fe06b27bc10>
           └ <requests.sessions.Session object at 0x7fdd3d813b80>
  File "/home/chase/.local/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
           │    │    │       └ {'timeout': 50, 'allow_redirects': True, 'verify': True, 'proxies': OrderedDict(), 'stream': False, 'cert': None}
           │    │    └ <PreparedRequest [GET]>
           │    └ <function Session.send at 0x7fe06b2720d0>
           └ <requests.sessions.Session object at 0x7fdd3d813b80>
  File "/home/chase/.local/lib/python3.8/site-packages/requests/sessions.py", line 677, in send
    history = [resp for resp in gen]
                                └ <generator object SessionRedirectMixin.resolve_redirects at 0x7fdf1062f2e0>
  File "/home/chase/.local/lib/python3.8/site-packages/requests/sessions.py", line 677, in <listcomp>
    history = [resp for resp in gen]
  File "/home/chase/.local/lib/python3.8/site-packages/requests/sessions.py", line 237, in resolve_redirects
    resp = self.send(
           │    └ <function Session.send at 0x7fe06b2720d0>
           └ <requests.sessions.Session object at 0x7fdd3d813b80>
  File "/home/chase/.local/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
        │       │    │          └ {'stream': False, 'timeout': 50, 'verify': True, 'cert': None, 'proxies': OrderedDict()}
        │       │    └ <PreparedRequest [GET]>
        │       └ <function HTTPAdapter.send at 0x7fe06b27b550>
        └ <requests.adapters.HTTPAdapter object at 0x7fdcf08f0250>
  File "/home/chase/.local/lib/python3.8/site-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
          │                   └ <PreparedRequest [GET]>
          └ <class 'requests.exceptions.SSLError'>

requests.exceptions.SSLError: HTTPSConnectionPool(host='wappass.baidu.com', port=443): Max retries exceeded with url: /static/captcha/tuxing.html?ak=2ef521ec36290baed33d66de9b16f625&backurl=http%3A%2F%2Ftieba.baidu.com%2Ff%2Fsearch%2Fres%3Fisnew%3D1%26kw%3D%26qw%3D%25E9%259D%259E%25E6%25B4%25B2%25E6%259E%2581%25E7%25AB%25AF%25E7%25BB%2584%25E7%25BB%2587%25E6%25AD%25A6%25E5%2599%25A8%25E6%259D%25A5%25E6%25BA%2590%25E5%25BC%2595%25E5%2585%25B3%25E6%25B3%25A8%26rn%3D10%26un%3D%26only_thread%3D0%26sm%3D1%26sd%3D%26ed%3D%26pn%3D5&timestamp=1654684450&signature=4bd37f01bebd49e09f1e7205ea8e0d55 (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1131)')))
2022-06-08 18:35:01.409 | ERROR    | monitor.searchSpiders.tieba:get_request_from_keyword:34 - E 贴吧错误HTTPSConnectionPool(host='wappass.baidu.com', port=443): Max retries exceeded with url: /static/captcha/tuxing.html?ak=2ef521ec36290baed33d66de9b16f625&backurl=http%3A%2F%2Ftieba.baidu.com%2Ff%2Fsearch%2Fres%3Fisnew%3D1%26kw%3D%26qw%3D%25E5%25A4%2596%25E4%25BA%25A4%25E9%2583%25A8%25EF%25BC%259A%25E5%2588%25B6%25E8%25A3%2581%25E6%258D%25A2%25E4%25B8%258D%25E6%259D%25A5%25E5%2592%258C%25E5%25B9%25B3%25EF%25BC%258C%25E5%258F%25AA%25E8%2583%25BD%25E7%25BB%2599%25E4%25B8%2596%25E7%2595%258C%25E7%25BB%258F%25E6%25B5%258E%25E9%259B%25AA%25E4%25B8%258A%25E5%258A%25A0%25E9%259C%259C%26rn%3D10%26un%3D%26only_thread%3D0%26sm%3D1%26sd%3D%26ed%3D%26pn%3D24&timestamp=1654684501&signature=54d94ba76a04f593829846a139f7b7eb (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1131)')))
Traceback (most recent call last):

  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
                       │    └ <function HTTPConnectionPool._make_request at 0x7fe06b3fed30>
                       └ <urllib3.connectionpool.HTTPSConnectionPool object at 0x7fddd0353730>
  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
    │    │              └ <urllib3.connection.HTTPSConnection object at 0x7fdd0f070f10>
    │    └ <function HTTPSConnectionPool._validate_conn at 0x7fe06b3ff280>
    └ <urllib3.connectionpool.HTTPSConnectionPool object at 0x7fddd0353730>
  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
    │    └ <function HTTPSConnection.connect at 0x7fe06b46d940>
    └ <urllib3.connection.HTTPSConnection object at 0x7fdd0f070f10>
  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/connection.py", line 416, in connect
    self.sock = ssl_wrap_socket(
    │    │      └ <function ssl_wrap_socket at 0x7fe06b468670>
    │    └ None
    └ <urllib3.connection.HTTPSConnection object at 0x7fdd0f070f10>
  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
               └ <function _ssl_wrap_socket_impl at 0x7fe06b468820>
  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
           │           │           │                     └ 'wappass.baidu.com'
           │           │           └ <socket.socket [closed] fd=-1, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6>
           │           └ <function SSLContext.wrap_socket at 0x7fe08118de50>
           └ <ssl.SSLContext object at 0x7fde301c4a40>
  File "/usr/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
           │    │               └ <classmethod object at 0x7fe08c8cfaf0>
           │    └ <class 'ssl.SSLSocket'>
           └ <ssl.SSLContext object at 0x7fde301c4a40>
  File "/usr/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
    │    └ <function SSLSocket.do_handshake at 0x7fe08c8d2d30>
    └ <ssl.SSLSocket [closed] fd=-1, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6>
  File "/usr/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
    │    └ None
    └ <ssl.SSLSocket [closed] fd=-1, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6>

ssl.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1131)


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/home/chase/.local/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
           │    └ <function HTTPConnectionPool.urlopen at 0x7fe06b3fef70>
           └ <urllib3.connectionpool.HTTPSConnectionPool object at 0x7fddd0353730>
  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
              │       └ <function Retry.increment at 0x7fe06b443280>
              └ Retry(total=0, connect=None, read=False, redirect=None, status=None)
  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
          │             │      │    │        │             └ 'unknown'
          │             │      │    │        └ <class 'urllib3.exceptions.ResponseError'>
          │             │      │    └ SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1131)'))
          │             │      └ '/static/captcha/tuxing.html?ak=2ef521ec36290baed33d66de9b16f625&backurl=http%3A%2F%2Ftieba.baidu.com%2Ff%2Fsearch%2Fres%3Fis...
          │             └ <urllib3.connectionpool.HTTPSConnectionPool object at 0x7fddd0353730>
          └ <class 'urllib3.exceptions.MaxRetryError'>

urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='wappass.baidu.com', port=443): Max retries exceeded with url: /static/captcha/tuxing.html?ak=2ef521ec36290baed33d66de9b16f625&backurl=http%3A%2F%2Ftieba.baidu.com%2Ff%2Fsearch%2Fres%3Fisnew%3D1%26kw%3D%26qw%3D%25E5%25A4%2596%25E4%25BA%25A4%25E9%2583%25A8%25EF%25BC%259A%25E5%2588%25B6%25E8%25A3%2581%25E6%258D%25A2%25E4%25B8%258D%25E6%259D%25A5%25E5%2592%258C%25E5%25B9%25B3%25EF%25BC%258C%25E5%258F%25AA%25E8%2583%25BD%25E7%25BB%2599%25E4%25B8%2596%25E7%2595%258C%25E7%25BB%258F%25E6%25B5%258E%25E9%259B%25AA%25E4%25B8%258A%25E5%258A%25A0%25E9%259C%259C%26rn%3D10%26un%3D%26only_thread%3D0%26sm%3D1%26sd%3D%26ed%3D%26pn%3D24&timestamp=1654684501&signature=54d94ba76a04f593829846a139f7b7eb (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1131)')))


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/usr/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7fe08f92ea60>
    └ <Thread(Thread-30924, started daemon 140589277787904)>
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7fe08f92e790>
    └ <Thread(Thread-30924, started daemon 140589277787904)>
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-30924, started daemon 140589277787904)>
    │    │        │    └ ('ProjectManager.run_func_by_thread',)
    │    │        └ <Thread(Thread-30924, started daemon 140589277787904)>
    │    └ <bound method ProjectManager.get_request_from_keywords_hot of <monitor.projectManager.ProjectManager object at 0x7fe063c65790>>
    └ <Thread(Thread-30924, started daemon 140589277787904)>

  File "/home/users/Scy/yuqing/spider/monitor/projectManager.py", line 833, in get_request_from_keywords_hot
    self.search_spider_manager.crawl_by_keyword(
    │    │                     └ <function SearchSpidersManager.crawl_by_keyword at 0x7fe063c71160>
    │    └ <monitor.spiderManager.SearchSpidersManager object at 0x7fe0638938b0>
    └ <monitor.projectManager.ProjectManager object at 0x7fe063c65790>

  File "/home/users/Scy/yuqing/spider/monitor/spiderManager.py", line 118, in crawl_by_keyword
    self.crawl_by_keyword_signal_platform(project_names, platform, keyword, crawl_time, project_times)
    │    │                                │              │         │        │           └ {'default': <monitor.TimeSection object at 0x7fe0639a2b80>}
    │    │                                │              │         │        └ <monitor.TimeSection object at 0x7fde50f49070>
    │    │                                │              │         └ '外交部：制裁换不来和平，只能给世界经济雪上加霜'
    │    │                                │              └ '贴吧'
    │    │                                └ ['default']
    │    └ <function SearchSpidersManager.crawl_by_keyword_signal_platform at 0x7fe063c71280>
    └ <monitor.spiderManager.SearchSpidersManager object at 0x7fe0638938b0>

  File "/home/users/Scy/yuqing/spider/monitor/spiderManager.py", line 150, in crawl_by_keyword_signal_platform
    requests = self.get_request_from_keyword(platform, keyword_only, **crawl_time.to_dict())
               │    │                        │         │               │          └ <function TimeSection.to_dict at 0x7fe06b8931f0>
               │    │                        │         │               └ <monitor.TimeSection object at 0x7fde50f49070>
               │    │                        │         └ '外交部：制裁换不来和平，只能给世界经济雪上加霜'
               │    │                        └ '贴吧'
               │    └ <function SearchSpidersManager.get_request_from_keyword at 0x7fe063c713a0>
               └ <monitor.spiderManager.SearchSpidersManager object at 0x7fe0638938b0>

  File "/home/users/Scy/yuqing/spider/monitor/spiderManager.py", line 214, in get_request_from_keyword
    for request in self.spiders[platform].get_request_from_keyword(headers, search_url, keyword, content_url,
                   │    │       │                                  │        │           │        └ None
                   │    │       │                                  │        │           └ '外交部：制裁换不来和平，只能给世界经济雪上加霜'
                   │    │       │                                  │        └ <string.Template object at 0x7fde101bbb80>
                   │    │       │                                  └ {'Connection': 'keep-alive', 'sec-ch-ua': "'Chromium';v='92',' Not A;Brand';v='99', 'Google Chrome';v='92'", 'sec-ch-ua-mobil...
                   │    │       └ '贴吧'
                   │    └ {'凤凰网': <monitor.searchSpiders.ifeng.Ifeng object at 0x7fe063893370>, '头条': <monitor.searchSpiders.toutiao.Toutiao object at ...
                   └ <monitor.spiderManager.SearchSpidersManager object at 0x7fe0638938b0>

> File "/home/users/Scy/yuqing/spider/monitor/searchSpiders/tieba.py", line 22, in get_request_from_keyword
    response = requests.get(url, headers=headers, timeout=50)
               │        │   │            └ {'Connection': 'keep-alive', 'sec-ch-ua': "'Chromium';v='92',' Not A;Brand';v='99', 'Google Chrome';v='92'", 'sec-ch-ua-mobil...
               │        │   └ 'https://tieba.baidu.com/f/search/res?isnew=1&kw=&qw=外交部：制裁换不来和平，只能给世界经济雪上加霜&rn=10&un=&only_thread=0&sm=1&sd=&ed=&pn=24'
               │        └ <function get at 0x7fe06b2724c0>
               └ <module 'requests' from '/home/chase/.local/lib/python3.8/site-packages/requests/__init__.py'>

  File "/home/chase/.local/lib/python3.8/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
           │              │           │         └ {'headers': {'Connection': 'keep-alive', 'sec-ch-ua': "'Chromium';v='92',' Not A;Brand';v='99', 'Google Chrome';v='92'", 'sec...
           │              │           └ None
           │              └ 'https://tieba.baidu.com/f/search/res?isnew=1&kw=&qw=外交部：制裁换不来和平，只能给世界经济雪上加霜&rn=10&un=&only_thread=0&sm=1&sd=&ed=&pn=24'
           └ <function request at 0x7fe06b268310>
  File "/home/chase/.local/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
           │       │              │           │      └ {'params': None, 'headers': {'Connection': 'keep-alive', 'sec-ch-ua': "'Chromium';v='92',' Not A;Brand';v='99', 'Google Chrom...
           │       │              │           └ 'https://tieba.baidu.com/f/search/res?isnew=1&kw=&qw=外交部：制裁换不来和平，只能给世界经济雪上加霜&rn=10&un=&only_thread=0&sm=1&sd=&ed=&pn=24'
           │       │              └ 'get'
           │       └ <function Session.request at 0x7fe06b27bc10>
           └ <requests.sessions.Session object at 0x7fddd0526970>
  File "/home/chase/.local/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
           │    │    │       └ {'timeout': 50, 'allow_redirects': True, 'verify': True, 'proxies': OrderedDict(), 'stream': False, 'cert': None}
           │    │    └ <PreparedRequest [GET]>
           │    └ <function Session.send at 0x7fe06b2720d0>
           └ <requests.sessions.Session object at 0x7fddd0526970>
  File "/home/chase/.local/lib/python3.8/site-packages/requests/sessions.py", line 677, in send
    history = [resp for resp in gen]
                                └ <generator object SessionRedirectMixin.resolve_redirects at 0x7fded03097b0>
  File "/home/chase/.local/lib/python3.8/site-packages/requests/sessions.py", line 677, in <listcomp>
    history = [resp for resp in gen]
  File "/home/chase/.local/lib/python3.8/site-packages/requests/sessions.py", line 237, in resolve_redirects
    resp = self.send(
           │    └ <function Session.send at 0x7fe06b2720d0>
           └ <requests.sessions.Session object at 0x7fddd0526970>
  File "/home/chase/.local/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
        │       │    │          └ {'stream': False, 'timeout': 50, 'verify': True, 'cert': None, 'proxies': OrderedDict()}
        │       │    └ <PreparedRequest [GET]>
        │       └ <function HTTPAdapter.send at 0x7fe06b27b550>
        └ <requests.adapters.HTTPAdapter object at 0x7fdcd318e7c0>
  File "/home/chase/.local/lib/python3.8/site-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
          │                   └ <PreparedRequest [GET]>
          └ <class 'requests.exceptions.SSLError'>

requests.exceptions.SSLError: HTTPSConnectionPool(host='wappass.baidu.com', port=443): Max retries exceeded with url: /static/captcha/tuxing.html?ak=2ef521ec36290baed33d66de9b16f625&backurl=http%3A%2F%2Ftieba.baidu.com%2Ff%2Fsearch%2Fres%3Fisnew%3D1%26kw%3D%26qw%3D%25E5%25A4%2596%25E4%25BA%25A4%25E9%2583%25A8%25EF%25BC%259A%25E5%2588%25B6%25E8%25A3%2581%25E6%258D%25A2%25E4%25B8%258D%25E6%259D%25A5%25E5%2592%258C%25E5%25B9%25B3%25EF%25BC%258C%25E5%258F%25AA%25E8%2583%25BD%25E7%25BB%2599%25E4%25B8%2596%25E7%2595%258C%25E7%25BB%258F%25E6%25B5%258E%25E9%259B%25AA%25E4%25B8%258A%25E5%258A%25A0%25E9%259C%259C%26rn%3D10%26un%3D%26only_thread%3D0%26sm%3D1%26sd%3D%26ed%3D%26pn%3D24&timestamp=1654684501&signature=54d94ba76a04f593829846a139f7b7eb (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1131)')))
2022-06-08 18:41:50.124 | ERROR    | monitor.searchSpiders.tieba:get_request_from_keyword:34 - E 贴吧错误HTTPSConnectionPool(host='wappass.baidu.com', port=443): Max retries exceeded with url: /static/captcha/tuxing.html?ak=2ef521ec36290baed33d66de9b16f625&backurl=http%3A%2F%2Ftieba.baidu.com%2Ff%2Fsearch%2Fres%3Fisnew%3D1%26kw%3D%26qw%3D%25E6%2585%2595%25E5%25B0%25BC%25E9%25BB%2591%25E7%258E%25AF%25E5%258D%259A%25E4%25BC%259A%25E8%2581%259A%25E7%2584%25A6%25E7%258E%25AF%25E4%25BF%259D%25E6%2596%25B0%25E6%258A%2580%25E6%259C%25AF%26rn%3D10%26un%3D%26only_thread%3D0%26sm%3D1%26sd%3D%26ed%3D%26pn%3D26&timestamp=1654684910&signature=f42972a5235c0fca773d0b05132008ba (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1131)')))
Traceback (most recent call last):

  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
                       │    └ <function HTTPConnectionPool._make_request at 0x7fe06b3fed30>
                       └ <urllib3.connectionpool.HTTPSConnectionPool object at 0x7fde902cb670>
  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
    │    │              └ <urllib3.connection.HTTPSConnection object at 0x7fdcd1ec1040>
    │    └ <function HTTPSConnectionPool._validate_conn at 0x7fe06b3ff280>
    └ <urllib3.connectionpool.HTTPSConnectionPool object at 0x7fde902cb670>
  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
    │    └ <function HTTPSConnection.connect at 0x7fe06b46d940>
    └ <urllib3.connection.HTTPSConnection object at 0x7fdcd1ec1040>
  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/connection.py", line 416, in connect
    self.sock = ssl_wrap_socket(
    │    │      └ <function ssl_wrap_socket at 0x7fe06b468670>
    │    └ None
    └ <urllib3.connection.HTTPSConnection object at 0x7fdcd1ec1040>
  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
               └ <function _ssl_wrap_socket_impl at 0x7fe06b468820>
  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
           │           │           │                     └ 'wappass.baidu.com'
           │           │           └ <socket.socket [closed] fd=-1, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6>
           │           └ <function SSLContext.wrap_socket at 0x7fe08118de50>
           └ <ssl.SSLContext object at 0x7fded03e9740>
  File "/usr/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
           │    │               └ <classmethod object at 0x7fe08c8cfaf0>
           │    └ <class 'ssl.SSLSocket'>
           └ <ssl.SSLContext object at 0x7fded03e9740>
  File "/usr/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
    │    └ <function SSLSocket.do_handshake at 0x7fe08c8d2d30>
    └ <ssl.SSLSocket [closed] fd=-1, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6>
  File "/usr/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
    │    └ None
    └ <ssl.SSLSocket [closed] fd=-1, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6>

ssl.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1131)


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/home/chase/.local/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
           │    └ <function HTTPConnectionPool.urlopen at 0x7fe06b3fef70>
           └ <urllib3.connectionpool.HTTPSConnectionPool object at 0x7fde902cb670>
  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
              │       └ <function Retry.increment at 0x7fe06b443280>
              └ Retry(total=0, connect=None, read=False, redirect=None, status=None)
  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
          │             │      │    │        │             └ 'unknown'
          │             │      │    │        └ <class 'urllib3.exceptions.ResponseError'>
          │             │      │    └ SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1131)'))
          │             │      └ '/static/captcha/tuxing.html?ak=2ef521ec36290baed33d66de9b16f625&backurl=http%3A%2F%2Ftieba.baidu.com%2Ff%2Fsearch%2Fres%3Fis...
          │             └ <urllib3.connectionpool.HTTPSConnectionPool object at 0x7fde902cb670>
          └ <class 'urllib3.exceptions.MaxRetryError'>

urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='wappass.baidu.com', port=443): Max retries exceeded with url: /static/captcha/tuxing.html?ak=2ef521ec36290baed33d66de9b16f625&backurl=http%3A%2F%2Ftieba.baidu.com%2Ff%2Fsearch%2Fres%3Fisnew%3D1%26kw%3D%26qw%3D%25E6%2585%2595%25E5%25B0%25BC%25E9%25BB%2591%25E7%258E%25AF%25E5%258D%259A%25E4%25BC%259A%25E8%2581%259A%25E7%2584%25A6%25E7%258E%25AF%25E4%25BF%259D%25E6%2596%25B0%25E6%258A%2580%25E6%259C%25AF%26rn%3D10%26un%3D%26only_thread%3D0%26sm%3D1%26sd%3D%26ed%3D%26pn%3D26&timestamp=1654684910&signature=f42972a5235c0fca773d0b05132008ba (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1131)')))


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/usr/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7fe08f92ea60>
    └ <Thread(Thread-33685, started daemon 140587851564800)>
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7fe08f92e790>
    └ <Thread(Thread-33685, started daemon 140587851564800)>
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-33685, started daemon 140587851564800)>
    │    │        │    └ ('ProjectManager.run_func_by_thread',)
    │    │        └ <Thread(Thread-33685, started daemon 140587851564800)>
    │    └ <bound method ProjectManager.get_request_from_keywords_hot of <monitor.projectManager.ProjectManager object at 0x7fe063c65790>>
    └ <Thread(Thread-33685, started daemon 140587851564800)>

  File "/home/users/Scy/yuqing/spider/monitor/projectManager.py", line 833, in get_request_from_keywords_hot
    self.search_spider_manager.crawl_by_keyword(
    │    │                     └ <function SearchSpidersManager.crawl_by_keyword at 0x7fe063c71160>
    │    └ <monitor.spiderManager.SearchSpidersManager object at 0x7fe0638938b0>
    └ <monitor.projectManager.ProjectManager object at 0x7fe063c65790>

  File "/home/users/Scy/yuqing/spider/monitor/spiderManager.py", line 118, in crawl_by_keyword
    self.crawl_by_keyword_signal_platform(project_names, platform, keyword, crawl_time, project_times)
    │    │                                │              │         │        │           └ {'default': <monitor.TimeSection object at 0x7fe0639a2b80>}
    │    │                                │              │         │        └ <monitor.TimeSection object at 0x7fdeb009e9a0>
    │    │                                │              │         └ '慕尼黑环博会聚焦环保新技术'
    │    │                                │              └ '贴吧'
    │    │                                └ ['default']
    │    └ <function SearchSpidersManager.crawl_by_keyword_signal_platform at 0x7fe063c71280>
    └ <monitor.spiderManager.SearchSpidersManager object at 0x7fe0638938b0>

  File "/home/users/Scy/yuqing/spider/monitor/spiderManager.py", line 150, in crawl_by_keyword_signal_platform
    requests = self.get_request_from_keyword(platform, keyword_only, **crawl_time.to_dict())
               │    │                        │         │               │          └ <function TimeSection.to_dict at 0x7fe06b8931f0>
               │    │                        │         │               └ <monitor.TimeSection object at 0x7fdeb009e9a0>
               │    │                        │         └ '慕尼黑环博会聚焦环保新技术'
               │    │                        └ '贴吧'
               │    └ <function SearchSpidersManager.get_request_from_keyword at 0x7fe063c713a0>
               └ <monitor.spiderManager.SearchSpidersManager object at 0x7fe0638938b0>

  File "/home/users/Scy/yuqing/spider/monitor/spiderManager.py", line 214, in get_request_from_keyword
    for request in self.spiders[platform].get_request_from_keyword(headers, search_url, keyword, content_url,
                   │    │       │                                  │        │           │        └ None
                   │    │       │                                  │        │           └ '慕尼黑环博会聚焦环保新技术'
                   │    │       │                                  │        └ <string.Template object at 0x7fdef0137b80>
                   │    │       │                                  └ {'Connection': 'keep-alive', 'sec-ch-ua': "'Chromium';v='92',' Not A;Brand';v='99', 'Google Chrome';v='92'", 'sec-ch-ua-mobil...
                   │    │       └ '贴吧'
                   │    └ {'凤凰网': <monitor.searchSpiders.ifeng.Ifeng object at 0x7fe063893370>, '头条': <monitor.searchSpiders.toutiao.Toutiao object at ...
                   └ <monitor.spiderManager.SearchSpidersManager object at 0x7fe0638938b0>

> File "/home/users/Scy/yuqing/spider/monitor/searchSpiders/tieba.py", line 22, in get_request_from_keyword
    response = requests.get(url, headers=headers, timeout=50)
               │        │   │            └ {'Connection': 'keep-alive', 'sec-ch-ua': "'Chromium';v='92',' Not A;Brand';v='99', 'Google Chrome';v='92'", 'sec-ch-ua-mobil...
               │        │   └ 'https://tieba.baidu.com/f/search/res?isnew=1&kw=&qw=慕尼黑环博会聚焦环保新技术&rn=10&un=&only_thread=0&sm=1&sd=&ed=&pn=26'
               │        └ <function get at 0x7fe06b2724c0>
               └ <module 'requests' from '/home/chase/.local/lib/python3.8/site-packages/requests/__init__.py'>

  File "/home/chase/.local/lib/python3.8/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
           │              │           │         └ {'headers': {'Connection': 'keep-alive', 'sec-ch-ua': "'Chromium';v='92',' Not A;Brand';v='99', 'Google Chrome';v='92'", 'sec...
           │              │           └ None
           │              └ 'https://tieba.baidu.com/f/search/res?isnew=1&kw=&qw=慕尼黑环博会聚焦环保新技术&rn=10&un=&only_thread=0&sm=1&sd=&ed=&pn=26'
           └ <function request at 0x7fe06b268310>
  File "/home/chase/.local/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
           │       │              │           │      └ {'params': None, 'headers': {'Connection': 'keep-alive', 'sec-ch-ua': "'Chromium';v='92',' Not A;Brand';v='99', 'Google Chrom...
           │       │              │           └ 'https://tieba.baidu.com/f/search/res?isnew=1&kw=&qw=慕尼黑环博会聚焦环保新技术&rn=10&un=&only_thread=0&sm=1&sd=&ed=&pn=26'
           │       │              └ 'get'
           │       └ <function Session.request at 0x7fe06b27bc10>
           └ <requests.sessions.Session object at 0x7fdd3bb630a0>
  File "/home/chase/.local/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
           │    │    │       └ {'timeout': 50, 'allow_redirects': True, 'verify': True, 'proxies': OrderedDict(), 'stream': False, 'cert': None}
           │    │    └ <PreparedRequest [GET]>
           │    └ <function Session.send at 0x7fe06b2720d0>
           └ <requests.sessions.Session object at 0x7fdd3bb630a0>
  File "/home/chase/.local/lib/python3.8/site-packages/requests/sessions.py", line 677, in send
    history = [resp for resp in gen]
                                └ <generator object SessionRedirectMixin.resolve_redirects at 0x7fdd3bc7f430>
  File "/home/chase/.local/lib/python3.8/site-packages/requests/sessions.py", line 677, in <listcomp>
    history = [resp for resp in gen]
  File "/home/chase/.local/lib/python3.8/site-packages/requests/sessions.py", line 237, in resolve_redirects
    resp = self.send(
           │    └ <function Session.send at 0x7fe06b2720d0>
           └ <requests.sessions.Session object at 0x7fdd3bb630a0>
  File "/home/chase/.local/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
        │       │    │          └ {'stream': False, 'timeout': 50, 'verify': True, 'cert': None, 'proxies': OrderedDict()}
        │       │    └ <PreparedRequest [GET]>
        │       └ <function HTTPAdapter.send at 0x7fe06b27b550>
        └ <requests.adapters.HTTPAdapter object at 0x7fde30130c40>
  File "/home/chase/.local/lib/python3.8/site-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
          │                   └ <PreparedRequest [GET]>
          └ <class 'requests.exceptions.SSLError'>

requests.exceptions.SSLError: HTTPSConnectionPool(host='wappass.baidu.com', port=443): Max retries exceeded with url: /static/captcha/tuxing.html?ak=2ef521ec36290baed33d66de9b16f625&backurl=http%3A%2F%2Ftieba.baidu.com%2Ff%2Fsearch%2Fres%3Fisnew%3D1%26kw%3D%26qw%3D%25E6%2585%2595%25E5%25B0%25BC%25E9%25BB%2591%25E7%258E%25AF%25E5%258D%259A%25E4%25BC%259A%25E8%2581%259A%25E7%2584%25A6%25E7%258E%25AF%25E4%25BF%259D%25E6%2596%25B0%25E6%258A%2580%25E6%259C%25AF%26rn%3D10%26un%3D%26only_thread%3D0%26sm%3D1%26sd%3D%26ed%3D%26pn%3D26&timestamp=1654684910&signature=f42972a5235c0fca773d0b05132008ba (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1131)')))
2022-06-08 18:45:10.557 | ERROR    | monitor.searchSpiders.tieba:get_request_from_keyword:34 - E 贴吧错误HTTPSConnectionPool(host='wappass.baidu.com', port=443): Max retries exceeded with url: /static/captcha/tuxing.html?ak=2ef521ec36290baed33d66de9b16f625&backurl=http%3A%2F%2Ftieba.baidu.com%2Ff%2Fsearch%2Fres%3Fisnew%3D1%26kw%3D%26qw%3D%25E6%25B2%25B3%25E5%258D%2597%25E7%259C%2581%25E4%25BF%25A1%25E9%2598%25B3%25E5%25B8%2582%25E5%2580%259F%25E5%258A%25A9%25E7%25BA%25A2%25E8%2589%25B2%25E8%25B5%2584%25E6%25BA%2590%25E5%25BC%2580%25E5%25B1%2595%25E5%259F%258E%25E8%2588%25B0%25E5%2585%25B1%25E5%25BB%25BA%25E6%25B4%25BB%25E5%258A%25A8%26rn%3D10%26un%3D%26only_thread%3D0%26sm%3D1%26sd%3D%26ed%3D%26pn%3D24&timestamp=1654685110&signature=d7546a93731b3e364c3256e72577ea34 (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1131)')))
Traceback (most recent call last):

  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
                       │    └ <function HTTPConnectionPool._make_request at 0x7fe06b3fed30>
                       └ <urllib3.connectionpool.HTTPSConnectionPool object at 0x7fdf542cce50>
  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
    │    │              └ <urllib3.connection.HTTPSConnection object at 0x7fdce2402cd0>
    │    └ <function HTTPSConnectionPool._validate_conn at 0x7fe06b3ff280>
    └ <urllib3.connectionpool.HTTPSConnectionPool object at 0x7fdf542cce50>
  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
    │    └ <function HTTPSConnection.connect at 0x7fe06b46d940>
    └ <urllib3.connection.HTTPSConnection object at 0x7fdce2402cd0>
  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/connection.py", line 416, in connect
    self.sock = ssl_wrap_socket(
    │    │      └ <function ssl_wrap_socket at 0x7fe06b468670>
    │    └ None
    └ <urllib3.connection.HTTPSConnection object at 0x7fdce2402cd0>
  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
               └ <function _ssl_wrap_socket_impl at 0x7fe06b468820>
  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
           │           │           │                     └ 'wappass.baidu.com'
           │           │           └ <socket.socket [closed] fd=-1, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6>
           │           └ <function SSLContext.wrap_socket at 0x7fe08118de50>
           └ <ssl.SSLContext object at 0x7fdcf14091c0>
  File "/usr/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
           │    │               └ <classmethod object at 0x7fe08c8cfaf0>
           │    └ <class 'ssl.SSLSocket'>
           └ <ssl.SSLContext object at 0x7fdcf14091c0>
  File "/usr/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
    │    └ <function SSLSocket.do_handshake at 0x7fe08c8d2d30>
    └ <ssl.SSLSocket [closed] fd=-1, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6>
  File "/usr/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
    │    └ None
    └ <ssl.SSLSocket [closed] fd=-1, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6>

ssl.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1131)


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/home/chase/.local/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
           │    └ <function HTTPConnectionPool.urlopen at 0x7fe06b3fef70>
           └ <urllib3.connectionpool.HTTPSConnectionPool object at 0x7fdf542cce50>
  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
              │       └ <function Retry.increment at 0x7fe06b443280>
              └ Retry(total=0, connect=None, read=False, redirect=None, status=None)
  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
          │             │      │    │        │             └ 'unknown'
          │             │      │    │        └ <class 'urllib3.exceptions.ResponseError'>
          │             │      │    └ SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1131)'))
          │             │      └ '/static/captcha/tuxing.html?ak=2ef521ec36290baed33d66de9b16f625&backurl=http%3A%2F%2Ftieba.baidu.com%2Ff%2Fsearch%2Fres%3Fis...
          │             └ <urllib3.connectionpool.HTTPSConnectionPool object at 0x7fdf542cce50>
          └ <class 'urllib3.exceptions.MaxRetryError'>

urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='wappass.baidu.com', port=443): Max retries exceeded with url: /static/captcha/tuxing.html?ak=2ef521ec36290baed33d66de9b16f625&backurl=http%3A%2F%2Ftieba.baidu.com%2Ff%2Fsearch%2Fres%3Fisnew%3D1%26kw%3D%26qw%3D%25E6%25B2%25B3%25E5%258D%2597%25E7%259C%2581%25E4%25BF%25A1%25E9%2598%25B3%25E5%25B8%2582%25E5%2580%259F%25E5%258A%25A9%25E7%25BA%25A2%25E8%2589%25B2%25E8%25B5%2584%25E6%25BA%2590%25E5%25BC%2580%25E5%25B1%2595%25E5%259F%258E%25E8%2588%25B0%25E5%2585%25B1%25E5%25BB%25BA%25E6%25B4%25BB%25E5%258A%25A8%26rn%3D10%26un%3D%26only_thread%3D0%26sm%3D1%26sd%3D%26ed%3D%26pn%3D24&timestamp=1654685110&signature=d7546a93731b3e364c3256e72577ea34 (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1131)')))


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/usr/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7fe08f92ea60>
    └ <Thread(Thread-32997, started daemon 140590435456768)>
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7fe08f92e790>
    └ <Thread(Thread-32997, started daemon 140590435456768)>
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-32997, started daemon 140590435456768)>
    │    │        │    └ ('ProjectManager.run_func_by_thread',)
    │    │        └ <Thread(Thread-32997, started daemon 140590435456768)>
    │    └ <bound method ProjectManager.get_request_from_keywords_hot of <monitor.projectManager.ProjectManager object at 0x7fe063c65790>>
    └ <Thread(Thread-32997, started daemon 140590435456768)>

  File "/home/users/Scy/yuqing/spider/monitor/projectManager.py", line 833, in get_request_from_keywords_hot
    self.search_spider_manager.crawl_by_keyword(
    │    │                     └ <function SearchSpidersManager.crawl_by_keyword at 0x7fe063c71160>
    │    └ <monitor.spiderManager.SearchSpidersManager object at 0x7fe0638938b0>
    └ <monitor.projectManager.ProjectManager object at 0x7fe063c65790>

  File "/home/users/Scy/yuqing/spider/monitor/spiderManager.py", line 118, in crawl_by_keyword
    self.crawl_by_keyword_signal_platform(project_names, platform, keyword, crawl_time, project_times)
    │    │                                │              │         │        │           └ {'default': <monitor.TimeSection object at 0x7fe0639a2b80>}
    │    │                                │              │         │        └ <monitor.TimeSection object at 0x7fdd3a6faf10>
    │    │                                │              │         └ '河南省信阳市借助红色资源开展城舰共建活动'
    │    │                                │              └ '贴吧'
    │    │                                └ ['default']
    │    └ <function SearchSpidersManager.crawl_by_keyword_signal_platform at 0x7fe063c71280>
    └ <monitor.spiderManager.SearchSpidersManager object at 0x7fe0638938b0>

  File "/home/users/Scy/yuqing/spider/monitor/spiderManager.py", line 150, in crawl_by_keyword_signal_platform
    requests = self.get_request_from_keyword(platform, keyword_only, **crawl_time.to_dict())
               │    │                        │         │               │          └ <function TimeSection.to_dict at 0x7fe06b8931f0>
               │    │                        │         │               └ <monitor.TimeSection object at 0x7fdd3a6faf10>
               │    │                        │         └ '河南省信阳市借助红色资源开展城舰共建活动'
               │    │                        └ '贴吧'
               │    └ <function SearchSpidersManager.get_request_from_keyword at 0x7fe063c713a0>
               └ <monitor.spiderManager.SearchSpidersManager object at 0x7fe0638938b0>

  File "/home/users/Scy/yuqing/spider/monitor/spiderManager.py", line 214, in get_request_from_keyword
    for request in self.spiders[platform].get_request_from_keyword(headers, search_url, keyword, content_url,
                   │    │       │                                  │        │           │        └ None
                   │    │       │                                  │        │           └ '河南省信阳市借助红色资源开展城舰共建活动'
                   │    │       │                                  │        └ <string.Template object at 0x7fe0606e7910>
                   │    │       │                                  └ {'Connection': 'keep-alive', 'sec-ch-ua': "'Chromium';v='92',' Not A;Brand';v='99', 'Google Chrome';v='92'", 'sec-ch-ua-mobil...
                   │    │       └ '贴吧'
                   │    └ {'凤凰网': <monitor.searchSpiders.ifeng.Ifeng object at 0x7fe063893370>, '头条': <monitor.searchSpiders.toutiao.Toutiao object at ...
                   └ <monitor.spiderManager.SearchSpidersManager object at 0x7fe0638938b0>

> File "/home/users/Scy/yuqing/spider/monitor/searchSpiders/tieba.py", line 22, in get_request_from_keyword
    response = requests.get(url, headers=headers, timeout=50)
               │        │   │            └ {'Connection': 'keep-alive', 'sec-ch-ua': "'Chromium';v='92',' Not A;Brand';v='99', 'Google Chrome';v='92'", 'sec-ch-ua-mobil...
               │        │   └ 'https://tieba.baidu.com/f/search/res?isnew=1&kw=&qw=河南省信阳市借助红色资源开展城舰共建活动&rn=10&un=&only_thread=0&sm=1&sd=&ed=&pn=24'
               │        └ <function get at 0x7fe06b2724c0>
               └ <module 'requests' from '/home/chase/.local/lib/python3.8/site-packages/requests/__init__.py'>

  File "/home/chase/.local/lib/python3.8/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
           │              │           │         └ {'headers': {'Connection': 'keep-alive', 'sec-ch-ua': "'Chromium';v='92',' Not A;Brand';v='99', 'Google Chrome';v='92'", 'sec...
           │              │           └ None
           │              └ 'https://tieba.baidu.com/f/search/res?isnew=1&kw=&qw=河南省信阳市借助红色资源开展城舰共建活动&rn=10&un=&only_thread=0&sm=1&sd=&ed=&pn=24'
           └ <function request at 0x7fe06b268310>
  File "/home/chase/.local/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
           │       │              │           │      └ {'params': None, 'headers': {'Connection': 'keep-alive', 'sec-ch-ua': "'Chromium';v='92',' Not A;Brand';v='99', 'Google Chrom...
           │       │              │           └ 'https://tieba.baidu.com/f/search/res?isnew=1&kw=&qw=河南省信阳市借助红色资源开展城舰共建活动&rn=10&un=&only_thread=0&sm=1&sd=&ed=&pn=24'
           │       │              └ 'get'
           │       └ <function Session.request at 0x7fe06b27bc10>
           └ <requests.sessions.Session object at 0x7fdef0715c10>
  File "/home/chase/.local/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
           │    │    │       └ {'timeout': 50, 'allow_redirects': True, 'verify': True, 'proxies': OrderedDict(), 'stream': False, 'cert': None}
           │    │    └ <PreparedRequest [GET]>
           │    └ <function Session.send at 0x7fe06b2720d0>
           └ <requests.sessions.Session object at 0x7fdef0715c10>
  File "/home/chase/.local/lib/python3.8/site-packages/requests/sessions.py", line 677, in send
    history = [resp for resp in gen]
                                └ <generator object SessionRedirectMixin.resolve_redirects at 0x7fde106b2580>
  File "/home/chase/.local/lib/python3.8/site-packages/requests/sessions.py", line 677, in <listcomp>
    history = [resp for resp in gen]
  File "/home/chase/.local/lib/python3.8/site-packages/requests/sessions.py", line 237, in resolve_redirects
    resp = self.send(
           │    └ <function Session.send at 0x7fe06b2720d0>
           └ <requests.sessions.Session object at 0x7fdef0715c10>
  File "/home/chase/.local/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
        │       │    │          └ {'stream': False, 'timeout': 50, 'verify': True, 'cert': None, 'proxies': OrderedDict()}
        │       │    └ <PreparedRequest [GET]>
        │       └ <function HTTPAdapter.send at 0x7fe06b27b550>
        └ <requests.adapters.HTTPAdapter object at 0x7fddd03aa4c0>
  File "/home/chase/.local/lib/python3.8/site-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
          │                   └ <PreparedRequest [GET]>
          └ <class 'requests.exceptions.SSLError'>

requests.exceptions.SSLError: HTTPSConnectionPool(host='wappass.baidu.com', port=443): Max retries exceeded with url: /static/captcha/tuxing.html?ak=2ef521ec36290baed33d66de9b16f625&backurl=http%3A%2F%2Ftieba.baidu.com%2Ff%2Fsearch%2Fres%3Fisnew%3D1%26kw%3D%26qw%3D%25E6%25B2%25B3%25E5%258D%2597%25E7%259C%2581%25E4%25BF%25A1%25E9%2598%25B3%25E5%25B8%2582%25E5%2580%259F%25E5%258A%25A9%25E7%25BA%25A2%25E8%2589%25B2%25E8%25B5%2584%25E6%25BA%2590%25E5%25BC%2580%25E5%25B1%2595%25E5%259F%258E%25E8%2588%25B0%25E5%2585%25B1%25E5%25BB%25BA%25E6%25B4%25BB%25E5%258A%25A8%26rn%3D10%26un%3D%26only_thread%3D0%26sm%3D1%26sd%3D%26ed%3D%26pn%3D24&timestamp=1654685110&signature=d7546a93731b3e364c3256e72577ea34 (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1131)')))
2022-06-08 18:45:30.157 | ERROR    | monitor.searchSpiders.tieba:get_request_from_keyword:34 - E 贴吧错误HTTPSConnectionPool(host='wappass.baidu.com', port=443): Max retries exceeded with url: /static/captcha/tuxing.html?ak=2ef521ec36290baed33d66de9b16f625&backurl=http%3A%2F%2Ftieba.baidu.com%2Ff%2Fsearch%2Fres%3Fisnew%3D1%26kw%3D%26qw%3D%25E7%25BB%25B4%25E4%25B9%259F%25E7%25BA%25B3%25E8%2581%2594%25E5%2590%2588%25E5%259B%25BD%25E4%25B8%25AD%25E6%2596%2587%25E6%2597%25A5%25E6%25B4%25BB%25E5%258A%25A8%25E6%258B%2589%25E5%25BC%2580%25E5%25B8%25B7%25E5%25B9%2595%26rn%3D10%26un%3D%26only_thread%3D0%26sm%3D1%26sd%3D%26ed%3D%26pn%3D18&timestamp=1654685130&signature=57b84c6e238be76844f6c5caefd039c4 (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1131)')))
Traceback (most recent call last):

  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
                       │    └ <function HTTPConnectionPool._make_request at 0x7fe06b3fed30>
                       └ <urllib3.connectionpool.HTTPSConnectionPool object at 0x7fdf5476fc10>
  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
    │    │              └ <urllib3.connection.HTTPSConnection object at 0x7fded0599670>
    │    └ <function HTTPSConnectionPool._validate_conn at 0x7fe06b3ff280>
    └ <urllib3.connectionpool.HTTPSConnectionPool object at 0x7fdf5476fc10>
  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
    │    └ <function HTTPSConnection.connect at 0x7fe06b46d940>
    └ <urllib3.connection.HTTPSConnection object at 0x7fded0599670>
  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/connection.py", line 416, in connect
    self.sock = ssl_wrap_socket(
    │    │      └ <function ssl_wrap_socket at 0x7fe06b468670>
    │    └ None
    └ <urllib3.connection.HTTPSConnection object at 0x7fded0599670>
  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
               └ <function _ssl_wrap_socket_impl at 0x7fe06b468820>
  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
           │           │           │                     └ 'wappass.baidu.com'
           │           │           └ <socket.socket [closed] fd=-1, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6>
           │           └ <function SSLContext.wrap_socket at 0x7fe08118de50>
           └ <ssl.SSLContext object at 0x7fdf1050c6c0>
  File "/usr/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
           │    │               └ <classmethod object at 0x7fe08c8cfaf0>
           │    └ <class 'ssl.SSLSocket'>
           └ <ssl.SSLContext object at 0x7fdf1050c6c0>
  File "/usr/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
    │    └ <function SSLSocket.do_handshake at 0x7fe08c8d2d30>
    └ <ssl.SSLSocket [closed] fd=-1, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6>
  File "/usr/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
    │    └ None
    └ <ssl.SSLSocket [closed] fd=-1, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6>

ssl.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1131)


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/home/chase/.local/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
           │    └ <function HTTPConnectionPool.urlopen at 0x7fe06b3fef70>
           └ <urllib3.connectionpool.HTTPSConnectionPool object at 0x7fdf5476fc10>
  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
              │       └ <function Retry.increment at 0x7fe06b443280>
              └ Retry(total=0, connect=None, read=False, redirect=None, status=None)
  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
          │             │      │    │        │             └ 'unknown'
          │             │      │    │        └ <class 'urllib3.exceptions.ResponseError'>
          │             │      │    └ SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1131)'))
          │             │      └ '/static/captcha/tuxing.html?ak=2ef521ec36290baed33d66de9b16f625&backurl=http%3A%2F%2Ftieba.baidu.com%2Ff%2Fsearch%2Fres%3Fis...
          │             └ <urllib3.connectionpool.HTTPSConnectionPool object at 0x7fdf5476fc10>
          └ <class 'urllib3.exceptions.MaxRetryError'>

urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='wappass.baidu.com', port=443): Max retries exceeded with url: /static/captcha/tuxing.html?ak=2ef521ec36290baed33d66de9b16f625&backurl=http%3A%2F%2Ftieba.baidu.com%2Ff%2Fsearch%2Fres%3Fisnew%3D1%26kw%3D%26qw%3D%25E7%25BB%25B4%25E4%25B9%259F%25E7%25BA%25B3%25E8%2581%2594%25E5%2590%2588%25E5%259B%25BD%25E4%25B8%25AD%25E6%2596%2587%25E6%2597%25A5%25E6%25B4%25BB%25E5%258A%25A8%25E6%258B%2589%25E5%25BC%2580%25E5%25B8%25B7%25E5%25B9%2595%26rn%3D10%26un%3D%26only_thread%3D0%26sm%3D1%26sd%3D%26ed%3D%26pn%3D18&timestamp=1654685130&signature=57b84c6e238be76844f6c5caefd039c4 (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1131)')))


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/usr/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7fe08f92ea60>
    └ <Thread(Thread-31671, started daemon 140589621888768)>
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7fe08f92e790>
    └ <Thread(Thread-31671, started daemon 140589621888768)>
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-31671, started daemon 140589621888768)>
    │    │        │    └ ('ProjectManager.run_func_by_thread',)
    │    │        └ <Thread(Thread-31671, started daemon 140589621888768)>
    │    └ <bound method ProjectManager.get_request_from_keywords_hot of <monitor.projectManager.ProjectManager object at 0x7fe063c65790>>
    └ <Thread(Thread-31671, started daemon 140589621888768)>

  File "/home/users/Scy/yuqing/spider/monitor/projectManager.py", line 833, in get_request_from_keywords_hot
    self.search_spider_manager.crawl_by_keyword(
    │    │                     └ <function SearchSpidersManager.crawl_by_keyword at 0x7fe063c71160>
    │    └ <monitor.spiderManager.SearchSpidersManager object at 0x7fe0638938b0>
    └ <monitor.projectManager.ProjectManager object at 0x7fe063c65790>

  File "/home/users/Scy/yuqing/spider/monitor/spiderManager.py", line 118, in crawl_by_keyword
    self.crawl_by_keyword_signal_platform(project_names, platform, keyword, crawl_time, project_times)
    │    │                                │              │         │        │           └ {'default': <monitor.TimeSection object at 0x7fe0639a2b80>}
    │    │                                │              │         │        └ <monitor.TimeSection object at 0x7fdda2366490>
    │    │                                │              │         └ '维也纳联合国中文日活动拉开帷幕'
    │    │                                │              └ '贴吧'
    │    │                                └ ['default']
    │    └ <function SearchSpidersManager.crawl_by_keyword_signal_platform at 0x7fe063c71280>
    └ <monitor.spiderManager.SearchSpidersManager object at 0x7fe0638938b0>

  File "/home/users/Scy/yuqing/spider/monitor/spiderManager.py", line 150, in crawl_by_keyword_signal_platform
    requests = self.get_request_from_keyword(platform, keyword_only, **crawl_time.to_dict())
               │    │                        │         │               │          └ <function TimeSection.to_dict at 0x7fe06b8931f0>
               │    │                        │         │               └ <monitor.TimeSection object at 0x7fdda2366490>
               │    │                        │         └ '维也纳联合国中文日活动拉开帷幕'
               │    │                        └ '贴吧'
               │    └ <function SearchSpidersManager.get_request_from_keyword at 0x7fe063c713a0>
               └ <monitor.spiderManager.SearchSpidersManager object at 0x7fe0638938b0>

  File "/home/users/Scy/yuqing/spider/monitor/spiderManager.py", line 214, in get_request_from_keyword
    for request in self.spiders[platform].get_request_from_keyword(headers, search_url, keyword, content_url,
                   │    │       │                                  │        │           │        └ None
                   │    │       │                                  │        │           └ '维也纳联合国中文日活动拉开帷幕'
                   │    │       │                                  │        └ <string.Template object at 0x7fddd0301bb0>
                   │    │       │                                  └ {'Connection': 'keep-alive', 'sec-ch-ua': "'Chromium';v='92',' Not A;Brand';v='99', 'Google Chrome';v='92'", 'sec-ch-ua-mobil...
                   │    │       └ '贴吧'
                   │    └ {'凤凰网': <monitor.searchSpiders.ifeng.Ifeng object at 0x7fe063893370>, '头条': <monitor.searchSpiders.toutiao.Toutiao object at ...
                   └ <monitor.spiderManager.SearchSpidersManager object at 0x7fe0638938b0>

> File "/home/users/Scy/yuqing/spider/monitor/searchSpiders/tieba.py", line 22, in get_request_from_keyword
    response = requests.get(url, headers=headers, timeout=50)
               │        │   │            └ {'Connection': 'keep-alive', 'sec-ch-ua': "'Chromium';v='92',' Not A;Brand';v='99', 'Google Chrome';v='92'", 'sec-ch-ua-mobil...
               │        │   └ 'https://tieba.baidu.com/f/search/res?isnew=1&kw=&qw=维也纳联合国中文日活动拉开帷幕&rn=10&un=&only_thread=0&sm=1&sd=&ed=&pn=18'
               │        └ <function get at 0x7fe06b2724c0>
               └ <module 'requests' from '/home/chase/.local/lib/python3.8/site-packages/requests/__init__.py'>

  File "/home/chase/.local/lib/python3.8/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
           │              │           │         └ {'headers': {'Connection': 'keep-alive', 'sec-ch-ua': "'Chromium';v='92',' Not A;Brand';v='99', 'Google Chrome';v='92'", 'sec...
           │              │           └ None
           │              └ 'https://tieba.baidu.com/f/search/res?isnew=1&kw=&qw=维也纳联合国中文日活动拉开帷幕&rn=10&un=&only_thread=0&sm=1&sd=&ed=&pn=18'
           └ <function request at 0x7fe06b268310>
  File "/home/chase/.local/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
           │       │              │           │      └ {'params': None, 'headers': {'Connection': 'keep-alive', 'sec-ch-ua': "'Chromium';v='92',' Not A;Brand';v='99', 'Google Chrom...
           │       │              │           └ 'https://tieba.baidu.com/f/search/res?isnew=1&kw=&qw=维也纳联合国中文日活动拉开帷幕&rn=10&un=&only_thread=0&sm=1&sd=&ed=&pn=18'
           │       │              └ 'get'
           │       └ <function Session.request at 0x7fe06b27bc10>
           └ <requests.sessions.Session object at 0x7fdda24d65b0>
  File "/home/chase/.local/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
           │    │    │       └ {'timeout': 50, 'allow_redirects': True, 'verify': True, 'proxies': OrderedDict(), 'stream': False, 'cert': None}
           │    │    └ <PreparedRequest [GET]>
           │    └ <function Session.send at 0x7fe06b2720d0>
           └ <requests.sessions.Session object at 0x7fdda24d65b0>
  File "/home/chase/.local/lib/python3.8/site-packages/requests/sessions.py", line 677, in send
    history = [resp for resp in gen]
                                └ <generator object SessionRedirectMixin.resolve_redirects at 0x7fdef01449e0>
  File "/home/chase/.local/lib/python3.8/site-packages/requests/sessions.py", line 677, in <listcomp>
    history = [resp for resp in gen]
  File "/home/chase/.local/lib/python3.8/site-packages/requests/sessions.py", line 237, in resolve_redirects
    resp = self.send(
           │    └ <function Session.send at 0x7fe06b2720d0>
           └ <requests.sessions.Session object at 0x7fdda24d65b0>
  File "/home/chase/.local/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
        │       │    │          └ {'stream': False, 'timeout': 50, 'verify': True, 'cert': None, 'proxies': OrderedDict()}
        │       │    └ <PreparedRequest [GET]>
        │       └ <function HTTPAdapter.send at 0x7fe06b27b550>
        └ <requests.adapters.HTTPAdapter object at 0x7fddd066bb50>
  File "/home/chase/.local/lib/python3.8/site-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
          │                   └ <PreparedRequest [GET]>
          └ <class 'requests.exceptions.SSLError'>

requests.exceptions.SSLError: HTTPSConnectionPool(host='wappass.baidu.com', port=443): Max retries exceeded with url: /static/captcha/tuxing.html?ak=2ef521ec36290baed33d66de9b16f625&backurl=http%3A%2F%2Ftieba.baidu.com%2Ff%2Fsearch%2Fres%3Fisnew%3D1%26kw%3D%26qw%3D%25E7%25BB%25B4%25E4%25B9%259F%25E7%25BA%25B3%25E8%2581%2594%25E5%2590%2588%25E5%259B%25BD%25E4%25B8%25AD%25E6%2596%2587%25E6%2597%25A5%25E6%25B4%25BB%25E5%258A%25A8%25E6%258B%2589%25E5%25BC%2580%25E5%25B8%25B7%25E5%25B9%2595%26rn%3D10%26un%3D%26only_thread%3D0%26sm%3D1%26sd%3D%26ed%3D%26pn%3D18&timestamp=1654685130&signature=57b84c6e238be76844f6c5caefd039c4 (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1131)')))
2022-06-08 18:45:54.665 | ERROR    | monitor.searchSpiders.tieba:get_request_from_keyword:34 - E 贴吧错误HTTPSConnectionPool(host='wappass.baidu.com', port=443): Max retries exceeded with url: /static/captcha/tuxing.html?ak=2ef521ec36290baed33d66de9b16f625&backurl=http%3A%2F%2Ftieba.baidu.com%2Ff%2Fsearch%2Fres%3Fisnew%3D1%26kw%3D%26qw%3D%25E7%258E%258B%25E6%25AF%2585%25E4%25BC%259A%25E8%25A7%2581%25E4%25B9%258C%25E5%2585%25B9%25E5%2588%25AB%25E5%2585%258B%25E6%2596%25AF%25E5%259D%25A6%25E4%25BB%25A3%25E5%25A4%2596%25E9%2595%25BF%25E8%25AF%25BA%25E7%25BD%2597%25E5%25A4%25AB%26rn%3D10%26un%3D%26only_thread%3D0%26sm%3D1%26sd%3D%26ed%3D%26pn%3D1&timestamp=1654685154&signature=e146fdb443191f33f61682d6d34727b7 (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1131)')))
Traceback (most recent call last):

  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
                       │    └ <function HTTPConnectionPool._make_request at 0x7fe06b3fed30>
                       └ <urllib3.connectionpool.HTTPSConnectionPool object at 0x7fdef01c7e80>
  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
    │    │              └ <urllib3.connection.HTTPSConnection object at 0x7fded07564c0>
    │    └ <function HTTPSConnectionPool._validate_conn at 0x7fe06b3ff280>
    └ <urllib3.connectionpool.HTTPSConnectionPool object at 0x7fdef01c7e80>
  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
    │    └ <function HTTPSConnection.connect at 0x7fe06b46d940>
    └ <urllib3.connection.HTTPSConnection object at 0x7fded07564c0>
  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/connection.py", line 416, in connect
    self.sock = ssl_wrap_socket(
    │    │      └ <function ssl_wrap_socket at 0x7fe06b468670>
    │    └ None
    └ <urllib3.connection.HTTPSConnection object at 0x7fded07564c0>
  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
               └ <function _ssl_wrap_socket_impl at 0x7fe06b468820>
  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
           │           │           │                     └ 'wappass.baidu.com'
           │           │           └ <socket.socket [closed] fd=-1, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6>
           │           └ <function SSLContext.wrap_socket at 0x7fe08118de50>
           └ <ssl.SSLContext object at 0x7fddf078d9c0>
  File "/usr/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
           │    │               └ <classmethod object at 0x7fe08c8cfaf0>
           │    └ <class 'ssl.SSLSocket'>
           └ <ssl.SSLContext object at 0x7fddf078d9c0>
  File "/usr/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
    │    └ <function SSLSocket.do_handshake at 0x7fe08c8d2d30>
    └ <ssl.SSLSocket [closed] fd=-1, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6>
  File "/usr/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
    │    └ None
    └ <ssl.SSLSocket [closed] fd=-1, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6>

ssl.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1131)


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/home/chase/.local/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
           │    └ <function HTTPConnectionPool.urlopen at 0x7fe06b3fef70>
           └ <urllib3.connectionpool.HTTPSConnectionPool object at 0x7fdef01c7e80>
  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
              │       └ <function Retry.increment at 0x7fe06b443280>
              └ Retry(total=0, connect=None, read=False, redirect=None, status=None)
  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
          │             │      │    │        │             └ 'unknown'
          │             │      │    │        └ <class 'urllib3.exceptions.ResponseError'>
          │             │      │    └ SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1131)'))
          │             │      └ '/static/captcha/tuxing.html?ak=2ef521ec36290baed33d66de9b16f625&backurl=http%3A%2F%2Ftieba.baidu.com%2Ff%2Fsearch%2Fres%3Fis...
          │             └ <urllib3.connectionpool.HTTPSConnectionPool object at 0x7fdef01c7e80>
          └ <class 'urllib3.exceptions.MaxRetryError'>

urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='wappass.baidu.com', port=443): Max retries exceeded with url: /static/captcha/tuxing.html?ak=2ef521ec36290baed33d66de9b16f625&backurl=http%3A%2F%2Ftieba.baidu.com%2Ff%2Fsearch%2Fres%3Fisnew%3D1%26kw%3D%26qw%3D%25E7%258E%258B%25E6%25AF%2585%25E4%25BC%259A%25E8%25A7%2581%25E4%25B9%258C%25E5%2585%25B9%25E5%2588%25AB%25E5%2585%258B%25E6%2596%25AF%25E5%259D%25A6%25E4%25BB%25A3%25E5%25A4%2596%25E9%2595%25BF%25E8%25AF%25BA%25E7%25BD%2597%25E5%25A4%25AB%26rn%3D10%26un%3D%26only_thread%3D0%26sm%3D1%26sd%3D%26ed%3D%26pn%3D1&timestamp=1654685154&signature=e146fdb443191f33f61682d6d34727b7 (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1131)')))


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/usr/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7fe08f92ea60>
    └ <Thread(Thread-33328, started daemon 140586487506688)>
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7fe08f92e790>
    └ <Thread(Thread-33328, started daemon 140586487506688)>
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-33328, started daemon 140586487506688)>
    │    │        │    └ ('ProjectManager.run_func_by_thread',)
    │    │        └ <Thread(Thread-33328, started daemon 140586487506688)>
    │    └ <bound method ProjectManager.get_request_from_keywords_hot of <monitor.projectManager.ProjectManager object at 0x7fe063c65790>>
    └ <Thread(Thread-33328, started daemon 140586487506688)>

  File "/home/users/Scy/yuqing/spider/monitor/projectManager.py", line 833, in get_request_from_keywords_hot
    self.search_spider_manager.crawl_by_keyword(
    │    │                     └ <function SearchSpidersManager.crawl_by_keyword at 0x7fe063c71160>
    │    └ <monitor.spiderManager.SearchSpidersManager object at 0x7fe0638938b0>
    └ <monitor.projectManager.ProjectManager object at 0x7fe063c65790>

  File "/home/users/Scy/yuqing/spider/monitor/spiderManager.py", line 118, in crawl_by_keyword
    self.crawl_by_keyword_signal_platform(project_names, platform, keyword, crawl_time, project_times)
    │    │                                │              │         │        │           └ {'default': <monitor.TimeSection object at 0x7fe0639a2b80>}
    │    │                                │              │         │        └ <monitor.TimeSection object at 0x7fdda2056b50>
    │    │                                │              │         └ '王毅会见乌兹别克斯坦代外长诺罗夫'
    │    │                                │              └ '贴吧'
    │    │                                └ ['default']
    │    └ <function SearchSpidersManager.crawl_by_keyword_signal_platform at 0x7fe063c71280>
    └ <monitor.spiderManager.SearchSpidersManager object at 0x7fe0638938b0>

  File "/home/users/Scy/yuqing/spider/monitor/spiderManager.py", line 150, in crawl_by_keyword_signal_platform
    requests = self.get_request_from_keyword(platform, keyword_only, **crawl_time.to_dict())
               │    │                        │         │               │          └ <function TimeSection.to_dict at 0x7fe06b8931f0>
               │    │                        │         │               └ <monitor.TimeSection object at 0x7fdda2056b50>
               │    │                        │         └ '王毅会见乌兹别克斯坦代外长诺罗夫'
               │    │                        └ '贴吧'
               │    └ <function SearchSpidersManager.get_request_from_keyword at 0x7fe063c713a0>
               └ <monitor.spiderManager.SearchSpidersManager object at 0x7fe0638938b0>

  File "/home/users/Scy/yuqing/spider/monitor/spiderManager.py", line 214, in get_request_from_keyword
    for request in self.spiders[platform].get_request_from_keyword(headers, search_url, keyword, content_url,
                   │    │       │                                  │        │           │        └ None
                   │    │       │                                  │        │           └ '王毅会见乌兹别克斯坦代外长诺罗夫'
                   │    │       │                                  │        └ <string.Template object at 0x7fdf301c89d0>
                   │    │       │                                  └ {'Connection': 'keep-alive', 'sec-ch-ua': "'Chromium';v='92',' Not A;Brand';v='99', 'Google Chrome';v='92'", 'sec-ch-ua-mobil...
                   │    │       └ '贴吧'
                   │    └ {'凤凰网': <monitor.searchSpiders.ifeng.Ifeng object at 0x7fe063893370>, '头条': <monitor.searchSpiders.toutiao.Toutiao object at ...
                   └ <monitor.spiderManager.SearchSpidersManager object at 0x7fe0638938b0>

> File "/home/users/Scy/yuqing/spider/monitor/searchSpiders/tieba.py", line 22, in get_request_from_keyword
    response = requests.get(url, headers=headers, timeout=50)
               │        │   │            └ {'Connection': 'keep-alive', 'sec-ch-ua': "'Chromium';v='92',' Not A;Brand';v='99', 'Google Chrome';v='92'", 'sec-ch-ua-mobil...
               │        │   └ 'https://tieba.baidu.com/f/search/res?isnew=1&kw=&qw=王毅会见乌兹别克斯坦代外长诺罗夫&rn=10&un=&only_thread=0&sm=1&sd=&ed=&pn=1'
               │        └ <function get at 0x7fe06b2724c0>
               └ <module 'requests' from '/home/chase/.local/lib/python3.8/site-packages/requests/__init__.py'>

  File "/home/chase/.local/lib/python3.8/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
           │              │           │         └ {'headers': {'Connection': 'keep-alive', 'sec-ch-ua': "'Chromium';v='92',' Not A;Brand';v='99', 'Google Chrome';v='92'", 'sec...
           │              │           └ None
           │              └ 'https://tieba.baidu.com/f/search/res?isnew=1&kw=&qw=王毅会见乌兹别克斯坦代外长诺罗夫&rn=10&un=&only_thread=0&sm=1&sd=&ed=&pn=1'
           └ <function request at 0x7fe06b268310>
  File "/home/chase/.local/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
           │       │              │           │      └ {'params': None, 'headers': {'Connection': 'keep-alive', 'sec-ch-ua': "'Chromium';v='92',' Not A;Brand';v='99', 'Google Chrom...
           │       │              │           └ 'https://tieba.baidu.com/f/search/res?isnew=1&kw=&qw=王毅会见乌兹别克斯坦代外长诺罗夫&rn=10&un=&only_thread=0&sm=1&sd=&ed=&pn=1'
           │       │              └ 'get'
           │       └ <function Session.request at 0x7fe06b27bc10>
           └ <requests.sessions.Session object at 0x7fde102b1430>
  File "/home/chase/.local/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
           │    │    │       └ {'timeout': 50, 'allow_redirects': True, 'verify': True, 'proxies': OrderedDict(), 'stream': False, 'cert': None}
           │    │    └ <PreparedRequest [GET]>
           │    └ <function Session.send at 0x7fe06b2720d0>
           └ <requests.sessions.Session object at 0x7fde102b1430>
  File "/home/chase/.local/lib/python3.8/site-packages/requests/sessions.py", line 677, in send
    history = [resp for resp in gen]
                                └ <generator object SessionRedirectMixin.resolve_redirects at 0x7fdceae6ca50>
  File "/home/chase/.local/lib/python3.8/site-packages/requests/sessions.py", line 677, in <listcomp>
    history = [resp for resp in gen]
  File "/home/chase/.local/lib/python3.8/site-packages/requests/sessions.py", line 237, in resolve_redirects
    resp = self.send(
           │    └ <function Session.send at 0x7fe06b2720d0>
           └ <requests.sessions.Session object at 0x7fde102b1430>
  File "/home/chase/.local/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
        │       │    │          └ {'stream': False, 'timeout': 50, 'verify': True, 'cert': None, 'proxies': OrderedDict()}
        │       │    └ <PreparedRequest [GET]>
        │       └ <function HTTPAdapter.send at 0x7fe06b27b550>
        └ <requests.adapters.HTTPAdapter object at 0x7fde102a6250>
  File "/home/chase/.local/lib/python3.8/site-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
          │                   └ <PreparedRequest [GET]>
          └ <class 'requests.exceptions.SSLError'>

requests.exceptions.SSLError: HTTPSConnectionPool(host='wappass.baidu.com', port=443): Max retries exceeded with url: /static/captcha/tuxing.html?ak=2ef521ec36290baed33d66de9b16f625&backurl=http%3A%2F%2Ftieba.baidu.com%2Ff%2Fsearch%2Fres%3Fisnew%3D1%26kw%3D%26qw%3D%25E7%258E%258B%25E6%25AF%2585%25E4%25BC%259A%25E8%25A7%2581%25E4%25B9%258C%25E5%2585%25B9%25E5%2588%25AB%25E5%2585%258B%25E6%2596%25AF%25E5%259D%25A6%25E4%25BB%25A3%25E5%25A4%2596%25E9%2595%25BF%25E8%25AF%25BA%25E7%25BD%2597%25E5%25A4%25AB%26rn%3D10%26un%3D%26only_thread%3D0%26sm%3D1%26sd%3D%26ed%3D%26pn%3D1&timestamp=1654685154&signature=e146fdb443191f33f61682d6d34727b7 (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1131)')))
2022-06-08 18:52:30.116 | ERROR    | monitor.searchSpiders.tieba:get_request_from_keyword:34 - E 贴吧错误HTTPSConnectionPool(host='wappass.baidu.com', port=443): Max retries exceeded with url: /static/captcha/tuxing.html?ak=2ef521ec36290baed33d66de9b16f625&backurl=http%3A%2F%2Ftieba.baidu.com%2Ff%2Fsearch%2Fres%3Fisnew%3D1%26kw%3D%26qw%3D%25E4%25B8%2593%25E8%25AE%25BF%25EF%25BC%259A%25E7%25BE%258E%25E6%25BF%2580%25E8%25BF%259B%25E8%25B4%25A7%25E5%25B8%2581%25E6%2594%25BF%25E7%25AD%2596%25E5%25B0%2586%25E9%2598%25BB%25E7%25A2%258D%25E5%25A2%25A8%25E8%25A5%25BF%25E5%2593%25A5%25E7%25AD%2589%25E6%2596%25B0%25E5%2585%25B4%25E7%25BB%258F%25E6%25B5%258E%25E4%25BD%2593%25E5%25A4%258D%25E8%258B%258F%25E2%2580%2594%25E2%2580%2594%25E8%25AE%25BF%25E2%2580%25A6%26rn%3D10%26un%3D%26only_thread%3D0%26sm%3D1%26sd%3D%26ed%3D%26pn%3D5&timestamp=1654685550&signature=76ed1591b7a121710142281ecdbb97dd (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1131)')))
Traceback (most recent call last):

  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
                       │    └ <function HTTPConnectionPool._make_request at 0x7fe06b3fed30>
                       └ <urllib3.connectionpool.HTTPSConnectionPool object at 0x7fdd0c3d5e80>
  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
    │    │              └ <urllib3.connection.HTTPSConnection object at 0x7fde505a55e0>
    │    └ <function HTTPSConnectionPool._validate_conn at 0x7fe06b3ff280>
    └ <urllib3.connectionpool.HTTPSConnectionPool object at 0x7fdd0c3d5e80>
  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
    │    └ <function HTTPSConnection.connect at 0x7fe06b46d940>
    └ <urllib3.connection.HTTPSConnection object at 0x7fde505a55e0>
  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/connection.py", line 416, in connect
    self.sock = ssl_wrap_socket(
    │    │      └ <function ssl_wrap_socket at 0x7fe06b468670>
    │    └ None
    └ <urllib3.connection.HTTPSConnection object at 0x7fde505a55e0>
  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
               └ <function _ssl_wrap_socket_impl at 0x7fe06b468820>
  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
           │           │           │                     └ 'wappass.baidu.com'
           │           │           └ <socket.socket [closed] fd=-1, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6>
           │           └ <function SSLContext.wrap_socket at 0x7fe08118de50>
           └ <ssl.SSLContext object at 0x7fdcd3210e40>
  File "/usr/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
           │    │               └ <classmethod object at 0x7fe08c8cfaf0>
           │    └ <class 'ssl.SSLSocket'>
           └ <ssl.SSLContext object at 0x7fdcd3210e40>
  File "/usr/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
    │    └ <function SSLSocket.do_handshake at 0x7fe08c8d2d30>
    └ <ssl.SSLSocket [closed] fd=-1, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6>
  File "/usr/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
    │    └ None
    └ <ssl.SSLSocket [closed] fd=-1, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6>

ssl.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1131)


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/home/chase/.local/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
           │    └ <function HTTPConnectionPool.urlopen at 0x7fe06b3fef70>
           └ <urllib3.connectionpool.HTTPSConnectionPool object at 0x7fdd0c3d5e80>
  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
              │       └ <function Retry.increment at 0x7fe06b443280>
              └ Retry(total=0, connect=None, read=False, redirect=None, status=None)
  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
          │             │      │    │        │             └ 'unknown'
          │             │      │    │        └ <class 'urllib3.exceptions.ResponseError'>
          │             │      │    └ SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1131)'))
          │             │      └ '/static/captcha/tuxing.html?ak=2ef521ec36290baed33d66de9b16f625&backurl=http%3A%2F%2Ftieba.baidu.com%2Ff%2Fsearch%2Fres%3Fis...
          │             └ <urllib3.connectionpool.HTTPSConnectionPool object at 0x7fdd0c3d5e80>
          └ <class 'urllib3.exceptions.MaxRetryError'>

urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='wappass.baidu.com', port=443): Max retries exceeded with url: /static/captcha/tuxing.html?ak=2ef521ec36290baed33d66de9b16f625&backurl=http%3A%2F%2Ftieba.baidu.com%2Ff%2Fsearch%2Fres%3Fisnew%3D1%26kw%3D%26qw%3D%25E4%25B8%2593%25E8%25AE%25BF%25EF%25BC%259A%25E7%25BE%258E%25E6%25BF%2580%25E8%25BF%259B%25E8%25B4%25A7%25E5%25B8%2581%25E6%2594%25BF%25E7%25AD%2596%25E5%25B0%2586%25E9%2598%25BB%25E7%25A2%258D%25E5%25A2%25A8%25E8%25A5%25BF%25E5%2593%25A5%25E7%25AD%2589%25E6%2596%25B0%25E5%2585%25B4%25E7%25BB%258F%25E6%25B5%258E%25E4%25BD%2593%25E5%25A4%258D%25E8%258B%258F%25E2%2580%2594%25E2%2580%2594%25E8%25AE%25BF%25E2%2580%25A6%26rn%3D10%26un%3D%26only_thread%3D0%26sm%3D1%26sd%3D%26ed%3D%26pn%3D5&timestamp=1654685550&signature=76ed1591b7a121710142281ecdbb97dd (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1131)')))


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/usr/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7fe08f92ea60>
    └ <Thread(Thread-33988, started daemon 140601701918464)>
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7fe08f92e790>
    └ <Thread(Thread-33988, started daemon 140601701918464)>
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-33988, started daemon 140601701918464)>
    │    │        │    └ ('ProjectManager.run_func_by_thread',)
    │    │        └ <Thread(Thread-33988, started daemon 140601701918464)>
    │    └ <bound method ProjectManager.get_request_from_keywords_hot of <monitor.projectManager.ProjectManager object at 0x7fe063c65790>>
    └ <Thread(Thread-33988, started daemon 140601701918464)>

  File "/home/users/Scy/yuqing/spider/monitor/projectManager.py", line 833, in get_request_from_keywords_hot
    self.search_spider_manager.crawl_by_keyword(
    │    │                     └ <function SearchSpidersManager.crawl_by_keyword at 0x7fe063c71160>
    │    └ <monitor.spiderManager.SearchSpidersManager object at 0x7fe0638938b0>
    └ <monitor.projectManager.ProjectManager object at 0x7fe063c65790>

  File "/home/users/Scy/yuqing/spider/monitor/spiderManager.py", line 118, in crawl_by_keyword
    self.crawl_by_keyword_signal_platform(project_names, platform, keyword, crawl_time, project_times)
    │    │                                │              │         │        │           └ {'default': <monitor.TimeSection object at 0x7fe0639a2b80>}
    │    │                                │              │         │        └ <monitor.TimeSection object at 0x7fdeb009e2b0>
    │    │                                │              │         └ '专访：美激进货币政策将阻碍墨西哥等新兴经济体复苏——访…'
    │    │                                │              └ '贴吧'
    │    │                                └ ['default']
    │    └ <function SearchSpidersManager.crawl_by_keyword_signal_platform at 0x7fe063c71280>
    └ <monitor.spiderManager.SearchSpidersManager object at 0x7fe0638938b0>

  File "/home/users/Scy/yuqing/spider/monitor/spiderManager.py", line 150, in crawl_by_keyword_signal_platform
    requests = self.get_request_from_keyword(platform, keyword_only, **crawl_time.to_dict())
               │    │                        │         │               │          └ <function TimeSection.to_dict at 0x7fe06b8931f0>
               │    │                        │         │               └ <monitor.TimeSection object at 0x7fdeb009e2b0>
               │    │                        │         └ '专访：美激进货币政策将阻碍墨西哥等新兴经济体复苏——访…'
               │    │                        └ '贴吧'
               │    └ <function SearchSpidersManager.get_request_from_keyword at 0x7fe063c713a0>
               └ <monitor.spiderManager.SearchSpidersManager object at 0x7fe0638938b0>

  File "/home/users/Scy/yuqing/spider/monitor/spiderManager.py", line 214, in get_request_from_keyword
    for request in self.spiders[platform].get_request_from_keyword(headers, search_url, keyword, content_url,
                   │    │       │                                  │        │           │        └ None
                   │    │       │                                  │        │           └ '专访：美激进货币政策将阻碍墨西哥等新兴经济体复苏——访…'
                   │    │       │                                  │        └ <string.Template object at 0x7fded01e7790>
                   │    │       │                                  └ {'Connection': 'keep-alive', 'sec-ch-ua': "'Chromium';v='92',' Not A;Brand';v='99', 'Google Chrome';v='92'", 'sec-ch-ua-mobil...
                   │    │       └ '贴吧'
                   │    └ {'凤凰网': <monitor.searchSpiders.ifeng.Ifeng object at 0x7fe063893370>, '头条': <monitor.searchSpiders.toutiao.Toutiao object at ...
                   └ <monitor.spiderManager.SearchSpidersManager object at 0x7fe0638938b0>

> File "/home/users/Scy/yuqing/spider/monitor/searchSpiders/tieba.py", line 22, in get_request_from_keyword
    response = requests.get(url, headers=headers, timeout=50)
               │        │   │            └ {'Connection': 'keep-alive', 'sec-ch-ua': "'Chromium';v='92',' Not A;Brand';v='99', 'Google Chrome';v='92'", 'sec-ch-ua-mobil...
               │        │   └ 'https://tieba.baidu.com/f/search/res?isnew=1&kw=&qw=专访：美激进货币政策将阻碍墨西哥等新兴经济体复苏——访…&rn=10&un=&only_thread=0&sm=1&sd=&ed=&pn=5'
               │        └ <function get at 0x7fe06b2724c0>
               └ <module 'requests' from '/home/chase/.local/lib/python3.8/site-packages/requests/__init__.py'>

  File "/home/chase/.local/lib/python3.8/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
           │              │           │         └ {'headers': {'Connection': 'keep-alive', 'sec-ch-ua': "'Chromium';v='92',' Not A;Brand';v='99', 'Google Chrome';v='92'", 'sec...
           │              │           └ None
           │              └ 'https://tieba.baidu.com/f/search/res?isnew=1&kw=&qw=专访：美激进货币政策将阻碍墨西哥等新兴经济体复苏——访…&rn=10&un=&only_thread=0&sm=1&sd=&ed=&pn=5'
           └ <function request at 0x7fe06b268310>
  File "/home/chase/.local/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
           │       │              │           │      └ {'params': None, 'headers': {'Connection': 'keep-alive', 'sec-ch-ua': "'Chromium';v='92',' Not A;Brand';v='99', 'Google Chrom...
           │       │              │           └ 'https://tieba.baidu.com/f/search/res?isnew=1&kw=&qw=专访：美激进货币政策将阻碍墨西哥等新兴经济体复苏——访…&rn=10&un=&only_thread=0&sm=1&sd=&ed=&pn=5'
           │       │              └ 'get'
           │       └ <function Session.request at 0x7fe06b27bc10>
           └ <requests.sessions.Session object at 0x7fdda25bb2b0>
  File "/home/chase/.local/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
           │    │    │       └ {'timeout': 50, 'allow_redirects': True, 'verify': True, 'proxies': OrderedDict(), 'stream': False, 'cert': None}
           │    │    └ <PreparedRequest [GET]>
           │    └ <function Session.send at 0x7fe06b2720d0>
           └ <requests.sessions.Session object at 0x7fdda25bb2b0>
  File "/home/chase/.local/lib/python3.8/site-packages/requests/sessions.py", line 677, in send
    history = [resp for resp in gen]
                                └ <generator object SessionRedirectMixin.resolve_redirects at 0x7fdf30190ac0>
  File "/home/chase/.local/lib/python3.8/site-packages/requests/sessions.py", line 677, in <listcomp>
    history = [resp for resp in gen]
  File "/home/chase/.local/lib/python3.8/site-packages/requests/sessions.py", line 237, in resolve_redirects
    resp = self.send(
           │    └ <function Session.send at 0x7fe06b2720d0>
           └ <requests.sessions.Session object at 0x7fdda25bb2b0>
  File "/home/chase/.local/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
        │       │    │          └ {'stream': False, 'timeout': 50, 'verify': True, 'cert': None, 'proxies': OrderedDict()}
        │       │    └ <PreparedRequest [GET]>
        │       └ <function HTTPAdapter.send at 0x7fe06b27b550>
        └ <requests.adapters.HTTPAdapter object at 0x7fde70525580>
  File "/home/chase/.local/lib/python3.8/site-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
          │                   └ <PreparedRequest [GET]>
          └ <class 'requests.exceptions.SSLError'>

requests.exceptions.SSLError: HTTPSConnectionPool(host='wappass.baidu.com', port=443): Max retries exceeded with url: /static/captcha/tuxing.html?ak=2ef521ec36290baed33d66de9b16f625&backurl=http%3A%2F%2Ftieba.baidu.com%2Ff%2Fsearch%2Fres%3Fisnew%3D1%26kw%3D%26qw%3D%25E4%25B8%2593%25E8%25AE%25BF%25EF%25BC%259A%25E7%25BE%258E%25E6%25BF%2580%25E8%25BF%259B%25E8%25B4%25A7%25E5%25B8%2581%25E6%2594%25BF%25E7%25AD%2596%25E5%25B0%2586%25E9%2598%25BB%25E7%25A2%258D%25E5%25A2%25A8%25E8%25A5%25BF%25E5%2593%25A5%25E7%25AD%2589%25E6%2596%25B0%25E5%2585%25B4%25E7%25BB%258F%25E6%25B5%258E%25E4%25BD%2593%25E5%25A4%258D%25E8%258B%258F%25E2%2580%2594%25E2%2580%2594%25E8%25AE%25BF%25E2%2580%25A6%26rn%3D10%26un%3D%26only_thread%3D0%26sm%3D1%26sd%3D%26ed%3D%26pn%3D5&timestamp=1654685550&signature=76ed1591b7a121710142281ecdbb97dd (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1131)')))
2022-06-08 19:00:00.769 | ERROR    | monitor.searchSpiders.tieba:get_request_from_keyword:34 - E 贴吧错误HTTPSConnectionPool(host='wappass.baidu.com', port=443): Max retries exceeded with url: /static/captcha/tuxing.html?ak=2ef521ec36290baed33d66de9b16f625&backurl=http%3A%2F%2Ftieba.baidu.com%2Ff%2Fsearch%2Fres%3Fisnew%3D1%26kw%3D%26qw%3D%25E6%25B2%25B3%25E5%258D%2597%25E7%259C%2581%25E4%25BF%25A1%25E9%2598%25B3%25E5%25B8%2582%25E5%2580%259F%25E5%258A%25A9%25E7%25BA%25A2%25E8%2589%25B2%25E8%25B5%2584%25E6%25BA%2590%25E5%25BC%2580%25E5%25B1%2595%25E5%259F%258E%25E8%2588%25B0%25E5%2585%25B1%25E5%25BB%25BA%25E6%25B4%25BB%25E5%258A%25A8%26rn%3D10%26un%3D%26only_thread%3D0%26sm%3D1%26sd%3D%26ed%3D%26pn%3D19&timestamp=1654686000&signature=728a100e1d3cd223dca1a15b39050cee (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1131)')))
Traceback (most recent call last):

  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
                       │    └ <function HTTPConnectionPool._make_request at 0x7fe06b3fed30>
                       └ <urllib3.connectionpool.HTTPSConnectionPool object at 0x7fded026d520>
  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
    │    │              └ <urllib3.connection.HTTPSConnection object at 0x7fdda2479370>
    │    └ <function HTTPSConnectionPool._validate_conn at 0x7fe06b3ff280>
    └ <urllib3.connectionpool.HTTPSConnectionPool object at 0x7fded026d520>
  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
    │    └ <function HTTPSConnection.connect at 0x7fe06b46d940>
    └ <urllib3.connection.HTTPSConnection object at 0x7fdda2479370>
  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/connection.py", line 416, in connect
    self.sock = ssl_wrap_socket(
    │    │      └ <function ssl_wrap_socket at 0x7fe06b468670>
    │    └ None
    └ <urllib3.connection.HTTPSConnection object at 0x7fdda2479370>
  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
               └ <function _ssl_wrap_socket_impl at 0x7fe06b468820>
  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
           │           │           │                     └ 'wappass.baidu.com'
           │           │           └ <socket.socket [closed] fd=-1, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6>
           │           └ <function SSLContext.wrap_socket at 0x7fe08118de50>
           └ <ssl.SSLContext object at 0x7fde700954c0>
  File "/usr/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
           │    │               └ <classmethod object at 0x7fe08c8cfaf0>
           │    └ <class 'ssl.SSLSocket'>
           └ <ssl.SSLContext object at 0x7fde700954c0>
  File "/usr/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
    │    └ <function SSLSocket.do_handshake at 0x7fe08c8d2d30>
    └ <ssl.SSLSocket [closed] fd=-1, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6>
  File "/usr/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
    │    └ None
    └ <ssl.SSLSocket [closed] fd=-1, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6>

ssl.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1131)


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/home/chase/.local/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
           │    └ <function HTTPConnectionPool.urlopen at 0x7fe06b3fef70>
           └ <urllib3.connectionpool.HTTPSConnectionPool object at 0x7fded026d520>
  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
              │       └ <function Retry.increment at 0x7fe06b443280>
              └ Retry(total=0, connect=None, read=False, redirect=None, status=None)
  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
          │             │      │    │        │             └ 'unknown'
          │             │      │    │        └ <class 'urllib3.exceptions.ResponseError'>
          │             │      │    └ SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1131)'))
          │             │      └ '/static/captcha/tuxing.html?ak=2ef521ec36290baed33d66de9b16f625&backurl=http%3A%2F%2Ftieba.baidu.com%2Ff%2Fsearch%2Fres%3Fis...
          │             └ <urllib3.connectionpool.HTTPSConnectionPool object at 0x7fded026d520>
          └ <class 'urllib3.exceptions.MaxRetryError'>

urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='wappass.baidu.com', port=443): Max retries exceeded with url: /static/captcha/tuxing.html?ak=2ef521ec36290baed33d66de9b16f625&backurl=http%3A%2F%2Ftieba.baidu.com%2Ff%2Fsearch%2Fres%3Fisnew%3D1%26kw%3D%26qw%3D%25E6%25B2%25B3%25E5%258D%2597%25E7%259C%2581%25E4%25BF%25A1%25E9%2598%25B3%25E5%25B8%2582%25E5%2580%259F%25E5%258A%25A9%25E7%25BA%25A2%25E8%2589%25B2%25E8%25B5%2584%25E6%25BA%2590%25E5%25BC%2580%25E5%25B1%2595%25E5%259F%258E%25E8%2588%25B0%25E5%2585%25B1%25E5%25BB%25BA%25E6%25B4%25BB%25E5%258A%25A8%26rn%3D10%26un%3D%26only_thread%3D0%26sm%3D1%26sd%3D%26ed%3D%26pn%3D19&timestamp=1654686000&signature=728a100e1d3cd223dca1a15b39050cee (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1131)')))


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/usr/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7fe08f92ea60>
    └ <Thread(Thread-33277, started daemon 140586683422464)>
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7fe08f92e790>
    └ <Thread(Thread-33277, started daemon 140586683422464)>
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-33277, started daemon 140586683422464)>
    │    │        │    └ ('ProjectManager.run_func_by_thread',)
    │    │        └ <Thread(Thread-33277, started daemon 140586683422464)>
    │    └ <bound method ProjectManager.get_request_from_keywords_hot of <monitor.projectManager.ProjectManager object at 0x7fe063c65790>>
    └ <Thread(Thread-33277, started daemon 140586683422464)>

  File "/home/users/Scy/yuqing/spider/monitor/projectManager.py", line 833, in get_request_from_keywords_hot
    self.search_spider_manager.crawl_by_keyword(
    │    │                     └ <function SearchSpidersManager.crawl_by_keyword at 0x7fe063c71160>
    │    └ <monitor.spiderManager.SearchSpidersManager object at 0x7fe0638938b0>
    └ <monitor.projectManager.ProjectManager object at 0x7fe063c65790>

  File "/home/users/Scy/yuqing/spider/monitor/spiderManager.py", line 118, in crawl_by_keyword
    self.crawl_by_keyword_signal_platform(project_names, platform, keyword, crawl_time, project_times)
    │    │                                │              │         │        │           └ {'default': <monitor.TimeSection object at 0x7fe0639a2b80>}
    │    │                                │              │         │        └ <monitor.TimeSection object at 0x7fde50e629d0>
    │    │                                │              │         └ '河南省信阳市借助红色资源开展城舰共建活动'
    │    │                                │              └ '贴吧'
    │    │                                └ ['default']
    │    └ <function SearchSpidersManager.crawl_by_keyword_signal_platform at 0x7fe063c71280>
    └ <monitor.spiderManager.SearchSpidersManager object at 0x7fe0638938b0>

  File "/home/users/Scy/yuqing/spider/monitor/spiderManager.py", line 150, in crawl_by_keyword_signal_platform
    requests = self.get_request_from_keyword(platform, keyword_only, **crawl_time.to_dict())
               │    │                        │         │               │          └ <function TimeSection.to_dict at 0x7fe06b8931f0>
               │    │                        │         │               └ <monitor.TimeSection object at 0x7fde50e629d0>
               │    │                        │         └ '河南省信阳市借助红色资源开展城舰共建活动'
               │    │                        └ '贴吧'
               │    └ <function SearchSpidersManager.get_request_from_keyword at 0x7fe063c713a0>
               └ <monitor.spiderManager.SearchSpidersManager object at 0x7fe0638938b0>

  File "/home/users/Scy/yuqing/spider/monitor/spiderManager.py", line 214, in get_request_from_keyword
    for request in self.spiders[platform].get_request_from_keyword(headers, search_url, keyword, content_url,
                   │    │       │                                  │        │           │        └ None
                   │    │       │                                  │        │           └ '河南省信阳市借助红色资源开展城舰共建活动'
                   │    │       │                                  │        └ <string.Template object at 0x7fdd0f16a820>
                   │    │       │                                  └ {'Connection': 'keep-alive', 'sec-ch-ua': "'Chromium';v='92',' Not A;Brand';v='99', 'Google Chrome';v='92'", 'sec-ch-ua-mobil...
                   │    │       └ '贴吧'
                   │    └ {'凤凰网': <monitor.searchSpiders.ifeng.Ifeng object at 0x7fe063893370>, '头条': <monitor.searchSpiders.toutiao.Toutiao object at ...
                   └ <monitor.spiderManager.SearchSpidersManager object at 0x7fe0638938b0>

> File "/home/users/Scy/yuqing/spider/monitor/searchSpiders/tieba.py", line 22, in get_request_from_keyword
    response = requests.get(url, headers=headers, timeout=50)
               │        │   │            └ {'Connection': 'keep-alive', 'sec-ch-ua': "'Chromium';v='92',' Not A;Brand';v='99', 'Google Chrome';v='92'", 'sec-ch-ua-mobil...
               │        │   └ 'https://tieba.baidu.com/f/search/res?isnew=1&kw=&qw=河南省信阳市借助红色资源开展城舰共建活动&rn=10&un=&only_thread=0&sm=1&sd=&ed=&pn=19'
               │        └ <function get at 0x7fe06b2724c0>
               └ <module 'requests' from '/home/chase/.local/lib/python3.8/site-packages/requests/__init__.py'>

  File "/home/chase/.local/lib/python3.8/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
           │              │           │         └ {'headers': {'Connection': 'keep-alive', 'sec-ch-ua': "'Chromium';v='92',' Not A;Brand';v='99', 'Google Chrome';v='92'", 'sec...
           │              │           └ None
           │              └ 'https://tieba.baidu.com/f/search/res?isnew=1&kw=&qw=河南省信阳市借助红色资源开展城舰共建活动&rn=10&un=&only_thread=0&sm=1&sd=&ed=&pn=19'
           └ <function request at 0x7fe06b268310>
  File "/home/chase/.local/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
           │       │              │           │      └ {'params': None, 'headers': {'Connection': 'keep-alive', 'sec-ch-ua': "'Chromium';v='92',' Not A;Brand';v='99', 'Google Chrom...
           │       │              │           └ 'https://tieba.baidu.com/f/search/res?isnew=1&kw=&qw=河南省信阳市借助红色资源开展城舰共建活动&rn=10&un=&only_thread=0&sm=1&sd=&ed=&pn=19'
           │       │              └ 'get'
           │       └ <function Session.request at 0x7fe06b27bc10>
           └ <requests.sessions.Session object at 0x7fddd05565b0>
  File "/home/chase/.local/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
           │    │    │       └ {'timeout': 50, 'allow_redirects': True, 'verify': True, 'proxies': OrderedDict(), 'stream': False, 'cert': None}
           │    │    └ <PreparedRequest [GET]>
           │    └ <function Session.send at 0x7fe06b2720d0>
           └ <requests.sessions.Session object at 0x7fddd05565b0>
  File "/home/chase/.local/lib/python3.8/site-packages/requests/sessions.py", line 677, in send
    history = [resp for resp in gen]
                                └ <generator object SessionRedirectMixin.resolve_redirects at 0x7fde105c05f0>
  File "/home/chase/.local/lib/python3.8/site-packages/requests/sessions.py", line 677, in <listcomp>
    history = [resp for resp in gen]
  File "/home/chase/.local/lib/python3.8/site-packages/requests/sessions.py", line 237, in resolve_redirects
    resp = self.send(
           │    └ <function Session.send at 0x7fe06b2720d0>
           └ <requests.sessions.Session object at 0x7fddd05565b0>
  File "/home/chase/.local/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
        │       │    │          └ {'stream': False, 'timeout': 50, 'verify': True, 'cert': None, 'proxies': OrderedDict()}
        │       │    └ <PreparedRequest [GET]>
        │       └ <function HTTPAdapter.send at 0x7fe06b27b550>
        └ <requests.adapters.HTTPAdapter object at 0x7fde300f2490>
  File "/home/chase/.local/lib/python3.8/site-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
          │                   └ <PreparedRequest [GET]>
          └ <class 'requests.exceptions.SSLError'>

requests.exceptions.SSLError: HTTPSConnectionPool(host='wappass.baidu.com', port=443): Max retries exceeded with url: /static/captcha/tuxing.html?ak=2ef521ec36290baed33d66de9b16f625&backurl=http%3A%2F%2Ftieba.baidu.com%2Ff%2Fsearch%2Fres%3Fisnew%3D1%26kw%3D%26qw%3D%25E6%25B2%25B3%25E5%258D%2597%25E7%259C%2581%25E4%25BF%25A1%25E9%2598%25B3%25E5%25B8%2582%25E5%2580%259F%25E5%258A%25A9%25E7%25BA%25A2%25E8%2589%25B2%25E8%25B5%2584%25E6%25BA%2590%25E5%25BC%2580%25E5%25B1%2595%25E5%259F%258E%25E8%2588%25B0%25E5%2585%25B1%25E5%25BB%25BA%25E6%25B4%25BB%25E5%258A%25A8%26rn%3D10%26un%3D%26only_thread%3D0%26sm%3D1%26sd%3D%26ed%3D%26pn%3D19&timestamp=1654686000&signature=728a100e1d3cd223dca1a15b39050cee (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1131)')))
2022-06-08 19:01:20.107 | ERROR    | monitor.searchSpiders.tieba:get_request_from_keyword:34 - E 贴吧错误HTTPSConnectionPool(host='wappass.baidu.com', port=443): Max retries exceeded with url: /static/captcha/tuxing.html?ak=2ef521ec36290baed33d66de9b16f625&backurl=http%3A%2F%2Ftieba.baidu.com%2Ff%2Fsearch%2Fres%3Fisnew%3D1%26kw%3D%26qw%3D%25E5%25AE%2589%25E5%25BE%25BD%25E7%259C%2581%25E5%2586%259B%25E5%258C%25BA%25E5%258A%25A0%25E5%25BC%25BA%25E4%25BB%25A5%25E9%259D%2592%25E5%25B9%25B4%25E4%25B8%25BA%25E4%25B8%25BB%25E7%259A%2584%25E6%25B0%2591%25E5%2585%25B5%25E6%2596%25B0%25E8%25B4%25A8%25E5%258A%259B%25E9%2587%258F%25E5%25BB%25BA%25E8%25AE%25BE%26rn%3D10%26un%3D%26only_thread%3D0%26sm%3D1%26sd%3D%26ed%3D%26pn%3D3&timestamp=1654686080&signature=55de0b95b6d44ef664f6477d722eb1e7 (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1131)')))
Traceback (most recent call last):

  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
                       │    └ <function HTTPConnectionPool._make_request at 0x7fe06b3fed30>
                       └ <urllib3.connectionpool.HTTPSConnectionPool object at 0x7fdcd203eaf0>
  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
    │    │              └ <urllib3.connection.HTTPSConnection object at 0x7fe0605550a0>
    │    └ <function HTTPSConnectionPool._validate_conn at 0x7fe06b3ff280>
    └ <urllib3.connectionpool.HTTPSConnectionPool object at 0x7fdcd203eaf0>
  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
    │    └ <function HTTPSConnection.connect at 0x7fe06b46d940>
    └ <urllib3.connection.HTTPSConnection object at 0x7fe0605550a0>
  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/connection.py", line 416, in connect
    self.sock = ssl_wrap_socket(
    │    │      └ <function ssl_wrap_socket at 0x7fe06b468670>
    │    └ None
    └ <urllib3.connection.HTTPSConnection object at 0x7fe0605550a0>
  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
               └ <function _ssl_wrap_socket_impl at 0x7fe06b468820>
  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
           │           │           │                     └ 'wappass.baidu.com'
           │           │           └ <socket.socket [closed] fd=-1, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6>
           │           └ <function SSLContext.wrap_socket at 0x7fe08118de50>
           └ <ssl.SSLContext object at 0x7fdd2b036640>
  File "/usr/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
           │    │               └ <classmethod object at 0x7fe08c8cfaf0>
           │    └ <class 'ssl.SSLSocket'>
           └ <ssl.SSLContext object at 0x7fdd2b036640>
  File "/usr/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
    │    └ <function SSLSocket.do_handshake at 0x7fe08c8d2d30>
    └ <ssl.SSLSocket [closed] fd=-1, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6>
  File "/usr/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
    │    └ None
    └ <ssl.SSLSocket [closed] fd=-1, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6>

ssl.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1131)


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/home/chase/.local/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
           │    └ <function HTTPConnectionPool.urlopen at 0x7fe06b3fef70>
           └ <urllib3.connectionpool.HTTPSConnectionPool object at 0x7fdcd203eaf0>
  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
              │       └ <function Retry.increment at 0x7fe06b443280>
              └ Retry(total=0, connect=None, read=False, redirect=None, status=None)
  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
          │             │      │    │        │             └ 'unknown'
          │             │      │    │        └ <class 'urllib3.exceptions.ResponseError'>
          │             │      │    └ SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1131)'))
          │             │      └ '/static/captcha/tuxing.html?ak=2ef521ec36290baed33d66de9b16f625&backurl=http%3A%2F%2Ftieba.baidu.com%2Ff%2Fsearch%2Fres%3Fis...
          │             └ <urllib3.connectionpool.HTTPSConnectionPool object at 0x7fdcd203eaf0>
          └ <class 'urllib3.exceptions.MaxRetryError'>

urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='wappass.baidu.com', port=443): Max retries exceeded with url: /static/captcha/tuxing.html?ak=2ef521ec36290baed33d66de9b16f625&backurl=http%3A%2F%2Ftieba.baidu.com%2Ff%2Fsearch%2Fres%3Fisnew%3D1%26kw%3D%26qw%3D%25E5%25AE%2589%25E5%25BE%25BD%25E7%259C%2581%25E5%2586%259B%25E5%258C%25BA%25E5%258A%25A0%25E5%25BC%25BA%25E4%25BB%25A5%25E9%259D%2592%25E5%25B9%25B4%25E4%25B8%25BA%25E4%25B8%25BB%25E7%259A%2584%25E6%25B0%2591%25E5%2585%25B5%25E6%2596%25B0%25E8%25B4%25A8%25E5%258A%259B%25E9%2587%258F%25E5%25BB%25BA%25E8%25AE%25BE%26rn%3D10%26un%3D%26only_thread%3D0%26sm%3D1%26sd%3D%26ed%3D%26pn%3D3&timestamp=1654686080&signature=55de0b95b6d44ef664f6477d722eb1e7 (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1131)')))


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/usr/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7fe08f92ea60>
    └ <Thread(Thread-33853, started daemon 140591761438464)>
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7fe08f92e790>
    └ <Thread(Thread-33853, started daemon 140591761438464)>
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-33853, started daemon 140591761438464)>
    │    │        │    └ ('ProjectManager.run_func_by_thread',)
    │    │        └ <Thread(Thread-33853, started daemon 140591761438464)>
    │    └ <bound method ProjectManager.get_request_from_keywords_hot of <monitor.projectManager.ProjectManager object at 0x7fe063c65790>>
    └ <Thread(Thread-33853, started daemon 140591761438464)>

  File "/home/users/Scy/yuqing/spider/monitor/projectManager.py", line 833, in get_request_from_keywords_hot
    self.search_spider_manager.crawl_by_keyword(
    │    │                     └ <function SearchSpidersManager.crawl_by_keyword at 0x7fe063c71160>
    │    └ <monitor.spiderManager.SearchSpidersManager object at 0x7fe0638938b0>
    └ <monitor.projectManager.ProjectManager object at 0x7fe063c65790>

  File "/home/users/Scy/yuqing/spider/monitor/spiderManager.py", line 118, in crawl_by_keyword
    self.crawl_by_keyword_signal_platform(project_names, platform, keyword, crawl_time, project_times)
    │    │                                │              │         │        │           └ {'default': <monitor.TimeSection object at 0x7fe0639a2b80>}
    │    │                                │              │         │        └ <monitor.TimeSection object at 0x7fdd1e9b2430>
    │    │                                │              │         └ '安徽省军区加强以青年为主的民兵新质力量建设'
    │    │                                │              └ '贴吧'
    │    │                                └ ['default']
    │    └ <function SearchSpidersManager.crawl_by_keyword_signal_platform at 0x7fe063c71280>
    └ <monitor.spiderManager.SearchSpidersManager object at 0x7fe0638938b0>

  File "/home/users/Scy/yuqing/spider/monitor/spiderManager.py", line 150, in crawl_by_keyword_signal_platform
    requests = self.get_request_from_keyword(platform, keyword_only, **crawl_time.to_dict())
               │    │                        │         │               │          └ <function TimeSection.to_dict at 0x7fe06b8931f0>
               │    │                        │         │               └ <monitor.TimeSection object at 0x7fdd1e9b2430>
               │    │                        │         └ '安徽省军区加强以青年为主的民兵新质力量建设'
               │    │                        └ '贴吧'
               │    └ <function SearchSpidersManager.get_request_from_keyword at 0x7fe063c713a0>
               └ <monitor.spiderManager.SearchSpidersManager object at 0x7fe0638938b0>

  File "/home/users/Scy/yuqing/spider/monitor/spiderManager.py", line 214, in get_request_from_keyword
    for request in self.spiders[platform].get_request_from_keyword(headers, search_url, keyword, content_url,
                   │    │       │                                  │        │           │        └ None
                   │    │       │                                  │        │           └ '安徽省军区加强以青年为主的民兵新质力量建设'
                   │    │       │                                  │        └ <string.Template object at 0x7fdeb0049dc0>
                   │    │       │                                  └ {'Connection': 'keep-alive', 'sec-ch-ua': "'Chromium';v='92',' Not A;Brand';v='99', 'Google Chrome';v='92'", 'sec-ch-ua-mobil...
                   │    │       └ '贴吧'
                   │    └ {'凤凰网': <monitor.searchSpiders.ifeng.Ifeng object at 0x7fe063893370>, '头条': <monitor.searchSpiders.toutiao.Toutiao object at ...
                   └ <monitor.spiderManager.SearchSpidersManager object at 0x7fe0638938b0>

> File "/home/users/Scy/yuqing/spider/monitor/searchSpiders/tieba.py", line 22, in get_request_from_keyword
    response = requests.get(url, headers=headers, timeout=50)
               │        │   │            └ {'Connection': 'keep-alive', 'sec-ch-ua': "'Chromium';v='92',' Not A;Brand';v='99', 'Google Chrome';v='92'", 'sec-ch-ua-mobil...
               │        │   └ 'https://tieba.baidu.com/f/search/res?isnew=1&kw=&qw=安徽省军区加强以青年为主的民兵新质力量建设&rn=10&un=&only_thread=0&sm=1&sd=&ed=&pn=3'
               │        └ <function get at 0x7fe06b2724c0>
               └ <module 'requests' from '/home/chase/.local/lib/python3.8/site-packages/requests/__init__.py'>

  File "/home/chase/.local/lib/python3.8/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
           │              │           │         └ {'headers': {'Connection': 'keep-alive', 'sec-ch-ua': "'Chromium';v='92',' Not A;Brand';v='99', 'Google Chrome';v='92'", 'sec...
           │              │           └ None
           │              └ 'https://tieba.baidu.com/f/search/res?isnew=1&kw=&qw=安徽省军区加强以青年为主的民兵新质力量建设&rn=10&un=&only_thread=0&sm=1&sd=&ed=&pn=3'
           └ <function request at 0x7fe06b268310>
  File "/home/chase/.local/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
           │       │              │           │      └ {'params': None, 'headers': {'Connection': 'keep-alive', 'sec-ch-ua': "'Chromium';v='92',' Not A;Brand';v='99', 'Google Chrom...
           │       │              │           └ 'https://tieba.baidu.com/f/search/res?isnew=1&kw=&qw=安徽省军区加强以青年为主的民兵新质力量建设&rn=10&un=&only_thread=0&sm=1&sd=&ed=&pn=3'
           │       │              └ 'get'
           │       └ <function Session.request at 0x7fe06b27bc10>
           └ <requests.sessions.Session object at 0x7fdf300d3a00>
  File "/home/chase/.local/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
           │    │    │       └ {'timeout': 50, 'allow_redirects': True, 'verify': True, 'proxies': OrderedDict(), 'stream': False, 'cert': None}
           │    │    └ <PreparedRequest [GET]>
           │    └ <function Session.send at 0x7fe06b2720d0>
           └ <requests.sessions.Session object at 0x7fdf300d3a00>
  File "/home/chase/.local/lib/python3.8/site-packages/requests/sessions.py", line 677, in send
    history = [resp for resp in gen]
                                └ <generator object SessionRedirectMixin.resolve_redirects at 0x7fdd02a456d0>
  File "/home/chase/.local/lib/python3.8/site-packages/requests/sessions.py", line 677, in <listcomp>
    history = [resp for resp in gen]
  File "/home/chase/.local/lib/python3.8/site-packages/requests/sessions.py", line 237, in resolve_redirects
    resp = self.send(
           │    └ <function Session.send at 0x7fe06b2720d0>
           └ <requests.sessions.Session object at 0x7fdf300d3a00>
  File "/home/chase/.local/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
        │       │    │          └ {'stream': False, 'timeout': 50, 'verify': True, 'cert': None, 'proxies': OrderedDict()}
        │       │    └ <PreparedRequest [GET]>
        │       └ <function HTTPAdapter.send at 0x7fe06b27b550>
        └ <requests.adapters.HTTPAdapter object at 0x7fde300f52b0>
  File "/home/chase/.local/lib/python3.8/site-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
          │                   └ <PreparedRequest [GET]>
          └ <class 'requests.exceptions.SSLError'>

requests.exceptions.SSLError: HTTPSConnectionPool(host='wappass.baidu.com', port=443): Max retries exceeded with url: /static/captcha/tuxing.html?ak=2ef521ec36290baed33d66de9b16f625&backurl=http%3A%2F%2Ftieba.baidu.com%2Ff%2Fsearch%2Fres%3Fisnew%3D1%26kw%3D%26qw%3D%25E5%25AE%2589%25E5%25BE%25BD%25E7%259C%2581%25E5%2586%259B%25E5%258C%25BA%25E5%258A%25A0%25E5%25BC%25BA%25E4%25BB%25A5%25E9%259D%2592%25E5%25B9%25B4%25E4%25B8%25BA%25E4%25B8%25BB%25E7%259A%2584%25E6%25B0%2591%25E5%2585%25B5%25E6%2596%25B0%25E8%25B4%25A8%25E5%258A%259B%25E9%2587%258F%25E5%25BB%25BA%25E8%25AE%25BE%26rn%3D10%26un%3D%26only_thread%3D0%26sm%3D1%26sd%3D%26ed%3D%26pn%3D3&timestamp=1654686080&signature=55de0b95b6d44ef664f6477d722eb1e7 (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1131)')))
2022-06-08 19:05:10.496 | ERROR    | monitor.searchSpiders.tieba:get_request_from_keyword:34 - E 贴吧错误HTTPSConnectionPool(host='wappass.baidu.com', port=443): Max retries exceeded with url: /static/captcha/tuxing.html?ak=2ef521ec36290baed33d66de9b16f625&backurl=http%3A%2F%2Ftieba.baidu.com%2Ff%2Fsearch%2Fres%3Fisnew%3D1%26kw%3D%26qw%3D%25E6%2585%2595%25E5%25B0%25BC%25E9%25BB%2591%25E7%258E%25AF%25E5%258D%259A%25E4%25BC%259A%25E8%2581%259A%25E7%2584%25A6%25E7%258E%25AF%25E4%25BF%259D%25E6%2596%25B0%25E6%258A%2580%25E6%259C%25AF%26rn%3D10%26un%3D%26only_thread%3D0%26sm%3D1%26sd%3D%26ed%3D%26pn%3D17&timestamp=1654686310&signature=9aa4dcb81afac210a2e5add10cbd42d1 (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1131)')))
Traceback (most recent call last):

  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
                       │    └ <function HTTPConnectionPool._make_request at 0x7fe06b3fed30>
                       └ <urllib3.connectionpool.HTTPSConnectionPool object at 0x7fdd49bb7640>
  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
    │    │              └ <urllib3.connection.HTTPSConnection object at 0x7fdd3d7145e0>
    │    └ <function HTTPSConnectionPool._validate_conn at 0x7fe06b3ff280>
    └ <urllib3.connectionpool.HTTPSConnectionPool object at 0x7fdd49bb7640>
  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
    │    └ <function HTTPSConnection.connect at 0x7fe06b46d940>
    └ <urllib3.connection.HTTPSConnection object at 0x7fdd3d7145e0>
  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/connection.py", line 416, in connect
    self.sock = ssl_wrap_socket(
    │    │      └ <function ssl_wrap_socket at 0x7fe06b468670>
    │    └ None
    └ <urllib3.connection.HTTPSConnection object at 0x7fdd3d7145e0>
  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
               └ <function _ssl_wrap_socket_impl at 0x7fe06b468820>
  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
           │           │           │                     └ 'wappass.baidu.com'
           │           │           └ <socket.socket [closed] fd=-1, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6>
           │           └ <function SSLContext.wrap_socket at 0x7fe08118de50>
           └ <ssl.SSLContext object at 0x7fded06b6ac0>
  File "/usr/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
           │    │               └ <classmethod object at 0x7fe08c8cfaf0>
           │    └ <class 'ssl.SSLSocket'>
           └ <ssl.SSLContext object at 0x7fded06b6ac0>
  File "/usr/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
    │    └ <function SSLSocket.do_handshake at 0x7fe08c8d2d30>
    └ <ssl.SSLSocket [closed] fd=-1, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6>
  File "/usr/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
    │    └ None
    └ <ssl.SSLSocket [closed] fd=-1, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6>

ssl.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1131)


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/home/chase/.local/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
           │    └ <function HTTPConnectionPool.urlopen at 0x7fe06b3fef70>
           └ <urllib3.connectionpool.HTTPSConnectionPool object at 0x7fdd49bb7640>
  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
              │       └ <function Retry.increment at 0x7fe06b443280>
              └ Retry(total=0, connect=None, read=False, redirect=None, status=None)
  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
          │             │      │    │        │             └ 'unknown'
          │             │      │    │        └ <class 'urllib3.exceptions.ResponseError'>
          │             │      │    └ SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1131)'))
          │             │      └ '/static/captcha/tuxing.html?ak=2ef521ec36290baed33d66de9b16f625&backurl=http%3A%2F%2Ftieba.baidu.com%2Ff%2Fsearch%2Fres%3Fis...
          │             └ <urllib3.connectionpool.HTTPSConnectionPool object at 0x7fdd49bb7640>
          └ <class 'urllib3.exceptions.MaxRetryError'>

urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='wappass.baidu.com', port=443): Max retries exceeded with url: /static/captcha/tuxing.html?ak=2ef521ec36290baed33d66de9b16f625&backurl=http%3A%2F%2Ftieba.baidu.com%2Ff%2Fsearch%2Fres%3Fisnew%3D1%26kw%3D%26qw%3D%25E6%2585%2595%25E5%25B0%25BC%25E9%25BB%2591%25E7%258E%25AF%25E5%258D%259A%25E4%25BC%259A%25E8%2581%259A%25E7%2584%25A6%25E7%258E%25AF%25E4%25BF%259D%25E6%2596%25B0%25E6%258A%2580%25E6%259C%25AF%26rn%3D10%26un%3D%26only_thread%3D0%26sm%3D1%26sd%3D%26ed%3D%26pn%3D17&timestamp=1654686310&signature=9aa4dcb81afac210a2e5add10cbd42d1 (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1131)')))


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/usr/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7fe08f92ea60>
    └ <Thread(Thread-34027, started daemon 140587344340736)>
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7fe08f92e790>
    └ <Thread(Thread-34027, started daemon 140587344340736)>
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-34027, started daemon 140587344340736)>
    │    │        │    └ ('ProjectManager.run_func_by_thread',)
    │    │        └ <Thread(Thread-34027, started daemon 140587344340736)>
    │    └ <bound method ProjectManager.get_request_from_keywords_hot of <monitor.projectManager.ProjectManager object at 0x7fe063c65790>>
    └ <Thread(Thread-34027, started daemon 140587344340736)>

  File "/home/users/Scy/yuqing/spider/monitor/projectManager.py", line 833, in get_request_from_keywords_hot
    self.search_spider_manager.crawl_by_keyword(
    │    │                     └ <function SearchSpidersManager.crawl_by_keyword at 0x7fe063c71160>
    │    └ <monitor.spiderManager.SearchSpidersManager object at 0x7fe0638938b0>
    └ <monitor.projectManager.ProjectManager object at 0x7fe063c65790>

  File "/home/users/Scy/yuqing/spider/monitor/spiderManager.py", line 118, in crawl_by_keyword
    self.crawl_by_keyword_signal_platform(project_names, platform, keyword, crawl_time, project_times)
    │    │                                │              │         │        │           └ {'default': <monitor.TimeSection object at 0x7fe0639a2b80>}
    │    │                                │              │         │        └ <monitor.TimeSection object at 0x7fdcf0a7a2e0>
    │    │                                │              │         └ '慕尼黑环博会聚焦环保新技术'
    │    │                                │              └ '贴吧'
    │    │                                └ ['default']
    │    └ <function SearchSpidersManager.crawl_by_keyword_signal_platform at 0x7fe063c71280>
    └ <monitor.spiderManager.SearchSpidersManager object at 0x7fe0638938b0>

  File "/home/users/Scy/yuqing/spider/monitor/spiderManager.py", line 150, in crawl_by_keyword_signal_platform
    requests = self.get_request_from_keyword(platform, keyword_only, **crawl_time.to_dict())
               │    │                        │         │               │          └ <function TimeSection.to_dict at 0x7fe06b8931f0>
               │    │                        │         │               └ <monitor.TimeSection object at 0x7fdcf0a7a2e0>
               │    │                        │         └ '慕尼黑环博会聚焦环保新技术'
               │    │                        └ '贴吧'
               │    └ <function SearchSpidersManager.get_request_from_keyword at 0x7fe063c713a0>
               └ <monitor.spiderManager.SearchSpidersManager object at 0x7fe0638938b0>

  File "/home/users/Scy/yuqing/spider/monitor/spiderManager.py", line 214, in get_request_from_keyword
    for request in self.spiders[platform].get_request_from_keyword(headers, search_url, keyword, content_url,
                   │    │       │                                  │        │           │        └ None
                   │    │       │                                  │        │           └ '慕尼黑环博会聚焦环保新技术'
                   │    │       │                                  │        └ <string.Template object at 0x7fdf3048cd00>
                   │    │       │                                  └ {'Connection': 'keep-alive', 'sec-ch-ua': "'Chromium';v='92',' Not A;Brand';v='99', 'Google Chrome';v='92'", 'sec-ch-ua-mobil...
                   │    │       └ '贴吧'
                   │    └ {'凤凰网': <monitor.searchSpiders.ifeng.Ifeng object at 0x7fe063893370>, '头条': <monitor.searchSpiders.toutiao.Toutiao object at ...
                   └ <monitor.spiderManager.SearchSpidersManager object at 0x7fe0638938b0>

> File "/home/users/Scy/yuqing/spider/monitor/searchSpiders/tieba.py", line 22, in get_request_from_keyword
    response = requests.get(url, headers=headers, timeout=50)
               │        │   │            └ {'Connection': 'keep-alive', 'sec-ch-ua': "'Chromium';v='92',' Not A;Brand';v='99', 'Google Chrome';v='92'", 'sec-ch-ua-mobil...
               │        │   └ 'https://tieba.baidu.com/f/search/res?isnew=1&kw=&qw=慕尼黑环博会聚焦环保新技术&rn=10&un=&only_thread=0&sm=1&sd=&ed=&pn=17'
               │        └ <function get at 0x7fe06b2724c0>
               └ <module 'requests' from '/home/chase/.local/lib/python3.8/site-packages/requests/__init__.py'>

  File "/home/chase/.local/lib/python3.8/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
           │              │           │         └ {'headers': {'Connection': 'keep-alive', 'sec-ch-ua': "'Chromium';v='92',' Not A;Brand';v='99', 'Google Chrome';v='92'", 'sec...
           │              │           └ None
           │              └ 'https://tieba.baidu.com/f/search/res?isnew=1&kw=&qw=慕尼黑环博会聚焦环保新技术&rn=10&un=&only_thread=0&sm=1&sd=&ed=&pn=17'
           └ <function request at 0x7fe06b268310>
  File "/home/chase/.local/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
           │       │              │           │      └ {'params': None, 'headers': {'Connection': 'keep-alive', 'sec-ch-ua': "'Chromium';v='92',' Not A;Brand';v='99', 'Google Chrom...
           │       │              │           └ 'https://tieba.baidu.com/f/search/res?isnew=1&kw=&qw=慕尼黑环博会聚焦环保新技术&rn=10&un=&only_thread=0&sm=1&sd=&ed=&pn=17'
           │       │              └ 'get'
           │       └ <function Session.request at 0x7fe06b27bc10>
           └ <requests.sessions.Session object at 0x7fded037baf0>
  File "/home/chase/.local/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
           │    │    │       └ {'timeout': 50, 'allow_redirects': True, 'verify': True, 'proxies': OrderedDict(), 'stream': False, 'cert': None}
           │    │    └ <PreparedRequest [GET]>
           │    └ <function Session.send at 0x7fe06b2720d0>
           └ <requests.sessions.Session object at 0x7fded037baf0>
  File "/home/chase/.local/lib/python3.8/site-packages/requests/sessions.py", line 677, in send
    history = [resp for resp in gen]
                                └ <generator object SessionRedirectMixin.resolve_redirects at 0x7fdef024d970>
  File "/home/chase/.local/lib/python3.8/site-packages/requests/sessions.py", line 677, in <listcomp>
    history = [resp for resp in gen]
  File "/home/chase/.local/lib/python3.8/site-packages/requests/sessions.py", line 237, in resolve_redirects
    resp = self.send(
           │    └ <function Session.send at 0x7fe06b2720d0>
           └ <requests.sessions.Session object at 0x7fded037baf0>
  File "/home/chase/.local/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
        │       │    │          └ {'stream': False, 'timeout': 50, 'verify': True, 'cert': None, 'proxies': OrderedDict()}
        │       │    └ <PreparedRequest [GET]>
        │       └ <function HTTPAdapter.send at 0x7fe06b27b550>
        └ <requests.adapters.HTTPAdapter object at 0x7fdcf12f8f10>
  File "/home/chase/.local/lib/python3.8/site-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
          │                   └ <PreparedRequest [GET]>
          └ <class 'requests.exceptions.SSLError'>

requests.exceptions.SSLError: HTTPSConnectionPool(host='wappass.baidu.com', port=443): Max retries exceeded with url: /static/captcha/tuxing.html?ak=2ef521ec36290baed33d66de9b16f625&backurl=http%3A%2F%2Ftieba.baidu.com%2Ff%2Fsearch%2Fres%3Fisnew%3D1%26kw%3D%26qw%3D%25E6%2585%2595%25E5%25B0%25BC%25E9%25BB%2591%25E7%258E%25AF%25E5%258D%259A%25E4%25BC%259A%25E8%2581%259A%25E7%2584%25A6%25E7%258E%25AF%25E4%25BF%259D%25E6%2596%25B0%25E6%258A%2580%25E6%259C%25AF%26rn%3D10%26un%3D%26only_thread%3D0%26sm%3D1%26sd%3D%26ed%3D%26pn%3D17&timestamp=1654686310&signature=9aa4dcb81afac210a2e5add10cbd42d1 (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1131)')))
2022-06-08 19:09:00.441 | ERROR    | monitor.searchSpiders.tieba:get_request_from_keyword:34 - E 贴吧错误HTTPSConnectionPool(host='wappass.baidu.com', port=443): Max retries exceeded with url: /static/captcha/tuxing.html?ak=2ef521ec36290baed33d66de9b16f625&backurl=http%3A%2F%2Ftieba.baidu.com%2Ff%2Fsearch%2Fres%3Fisnew%3D1%26kw%3D%26qw%3D%25E4%25B8%2593%25E8%25AE%25BF%25EF%25BC%259A%25E7%25BE%258E%25E6%25BF%2580%25E8%25BF%259B%25E8%25B4%25A7%25E5%25B8%2581%25E6%2594%25BF%25E7%25AD%2596%25E5%25B0%2586%25E9%2598%25BB%25E7%25A2%258D%25E5%25A2%25A8%25E8%25A5%25BF%25E5%2593%25A5%25E7%25AD%2589%25E6%2596%25B0%25E5%2585%25B4%25E7%25BB%258F%25E6%25B5%258E%25E4%25BD%2593%25E5%25A4%258D%25E8%258B%258F%25E2%2580%2594%25E2%2580%2594%25E8%25AE%25BF%25E2%2580%25A6%26rn%3D10%26un%3D%26only_thread%3D0%26sm%3D1%26sd%3D%26ed%3D%26pn%3D2&timestamp=1654686540&signature=a1c27192b97a1184d4acc751cbb56786 (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1131)')))
Traceback (most recent call last):

  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
                       │    └ <function HTTPConnectionPool._make_request at 0x7fe06b3fed30>
                       └ <urllib3.connectionpool.HTTPSConnectionPool object at 0x7fe0605c24c0>
  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
    │    │              └ <urllib3.connection.HTTPSConnection object at 0x7fdd3d7e1b80>
    │    └ <function HTTPSConnectionPool._validate_conn at 0x7fe06b3ff280>
    └ <urllib3.connectionpool.HTTPSConnectionPool object at 0x7fe0605c24c0>
  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
    │    └ <function HTTPSConnection.connect at 0x7fe06b46d940>
    └ <urllib3.connection.HTTPSConnection object at 0x7fdd3d7e1b80>
  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/connection.py", line 416, in connect
    self.sock = ssl_wrap_socket(
    │    │      └ <function ssl_wrap_socket at 0x7fe06b468670>
    │    └ None
    └ <urllib3.connection.HTTPSConnection object at 0x7fdd3d7e1b80>
  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
               └ <function _ssl_wrap_socket_impl at 0x7fe06b468820>
  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
           │           │           │                     └ 'wappass.baidu.com'
           │           │           └ <socket.socket [closed] fd=-1, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6>
           │           └ <function SSLContext.wrap_socket at 0x7fe08118de50>
           └ <ssl.SSLContext object at 0x7fdda202b540>
  File "/usr/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
           │    │               └ <classmethod object at 0x7fe08c8cfaf0>
           │    └ <class 'ssl.SSLSocket'>
           └ <ssl.SSLContext object at 0x7fdda202b540>
  File "/usr/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
    │    └ <function SSLSocket.do_handshake at 0x7fe08c8d2d30>
    └ <ssl.SSLSocket [closed] fd=-1, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6>
  File "/usr/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
    │    └ None
    └ <ssl.SSLSocket [closed] fd=-1, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6>

ssl.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1131)


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/home/chase/.local/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
           │    └ <function HTTPConnectionPool.urlopen at 0x7fe06b3fef70>
           └ <urllib3.connectionpool.HTTPSConnectionPool object at 0x7fe0605c24c0>
  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
              │       └ <function Retry.increment at 0x7fe06b443280>
              └ Retry(total=0, connect=None, read=False, redirect=None, status=None)
  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
          │             │      │    │        │             └ 'unknown'
          │             │      │    │        └ <class 'urllib3.exceptions.ResponseError'>
          │             │      │    └ SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1131)'))
          │             │      └ '/static/captcha/tuxing.html?ak=2ef521ec36290baed33d66de9b16f625&backurl=http%3A%2F%2Ftieba.baidu.com%2Ff%2Fsearch%2Fres%3Fis...
          │             └ <urllib3.connectionpool.HTTPSConnectionPool object at 0x7fe0605c24c0>
          └ <class 'urllib3.exceptions.MaxRetryError'>

urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='wappass.baidu.com', port=443): Max retries exceeded with url: /static/captcha/tuxing.html?ak=2ef521ec36290baed33d66de9b16f625&backurl=http%3A%2F%2Ftieba.baidu.com%2Ff%2Fsearch%2Fres%3Fisnew%3D1%26kw%3D%26qw%3D%25E4%25B8%2593%25E8%25AE%25BF%25EF%25BC%259A%25E7%25BE%258E%25E6%25BF%2580%25E8%25BF%259B%25E8%25B4%25A7%25E5%25B8%2581%25E6%2594%25BF%25E7%25AD%2596%25E5%25B0%2586%25E9%2598%25BB%25E7%25A2%258D%25E5%25A2%25A8%25E8%25A5%25BF%25E5%2593%25A5%25E7%25AD%2589%25E6%2596%25B0%25E5%2585%25B4%25E7%25BB%258F%25E6%25B5%258E%25E4%25BD%2593%25E5%25A4%258D%25E8%258B%258F%25E2%2580%2594%25E2%2580%2594%25E8%25AE%25BF%25E2%2580%25A6%26rn%3D10%26un%3D%26only_thread%3D0%26sm%3D1%26sd%3D%26ed%3D%26pn%3D2&timestamp=1654686540&signature=a1c27192b97a1184d4acc751cbb56786 (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1131)')))


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/usr/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7fe08f92ea60>
    └ <Thread(Thread-34270, started daemon 140588116981504)>
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7fe08f92e790>
    └ <Thread(Thread-34270, started daemon 140588116981504)>
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-34270, started daemon 140588116981504)>
    │    │        │    └ ('ProjectManager.run_func_by_thread',)
    │    │        └ <Thread(Thread-34270, started daemon 140588116981504)>
    │    └ <bound method ProjectManager.get_request_from_keywords_hot of <monitor.projectManager.ProjectManager object at 0x7fe063c65790>>
    └ <Thread(Thread-34270, started daemon 140588116981504)>

  File "/home/users/Scy/yuqing/spider/monitor/projectManager.py", line 833, in get_request_from_keywords_hot
    self.search_spider_manager.crawl_by_keyword(
    │    │                     └ <function SearchSpidersManager.crawl_by_keyword at 0x7fe063c71160>
    │    └ <monitor.spiderManager.SearchSpidersManager object at 0x7fe0638938b0>
    └ <monitor.projectManager.ProjectManager object at 0x7fe063c65790>

  File "/home/users/Scy/yuqing/spider/monitor/spiderManager.py", line 118, in crawl_by_keyword
    self.crawl_by_keyword_signal_platform(project_names, platform, keyword, crawl_time, project_times)
    │    │                                │              │         │        │           └ {'default': <monitor.TimeSection object at 0x7fe0639a2b80>}
    │    │                                │              │         │        └ <monitor.TimeSection object at 0x7fdf305fab80>
    │    │                                │              │         └ '专访：美激进货币政策将阻碍墨西哥等新兴经济体复苏——访…'
    │    │                                │              └ '贴吧'
    │    │                                └ ['default']
    │    └ <function SearchSpidersManager.crawl_by_keyword_signal_platform at 0x7fe063c71280>
    └ <monitor.spiderManager.SearchSpidersManager object at 0x7fe0638938b0>

  File "/home/users/Scy/yuqing/spider/monitor/spiderManager.py", line 150, in crawl_by_keyword_signal_platform
    requests = self.get_request_from_keyword(platform, keyword_only, **crawl_time.to_dict())
               │    │                        │         │               │          └ <function TimeSection.to_dict at 0x7fe06b8931f0>
               │    │                        │         │               └ <monitor.TimeSection object at 0x7fdf305fab80>
               │    │                        │         └ '专访：美激进货币政策将阻碍墨西哥等新兴经济体复苏——访…'
               │    │                        └ '贴吧'
               │    └ <function SearchSpidersManager.get_request_from_keyword at 0x7fe063c713a0>
               └ <monitor.spiderManager.SearchSpidersManager object at 0x7fe0638938b0>

  File "/home/users/Scy/yuqing/spider/monitor/spiderManager.py", line 214, in get_request_from_keyword
    for request in self.spiders[platform].get_request_from_keyword(headers, search_url, keyword, content_url,
                   │    │       │                                  │        │           │        └ None
                   │    │       │                                  │        │           └ '专访：美激进货币政策将阻碍墨西哥等新兴经济体复苏——访…'
                   │    │       │                                  │        └ <string.Template object at 0x7fdef06523a0>
                   │    │       │                                  └ {'Connection': 'keep-alive', 'sec-ch-ua': "'Chromium';v='92',' Not A;Brand';v='99', 'Google Chrome';v='92'", 'sec-ch-ua-mobil...
                   │    │       └ '贴吧'
                   │    └ {'凤凰网': <monitor.searchSpiders.ifeng.Ifeng object at 0x7fe063893370>, '头条': <monitor.searchSpiders.toutiao.Toutiao object at ...
                   └ <monitor.spiderManager.SearchSpidersManager object at 0x7fe0638938b0>

> File "/home/users/Scy/yuqing/spider/monitor/searchSpiders/tieba.py", line 22, in get_request_from_keyword
    response = requests.get(url, headers=headers, timeout=50)
               │        │   │            └ {'Connection': 'keep-alive', 'sec-ch-ua': "'Chromium';v='92',' Not A;Brand';v='99', 'Google Chrome';v='92'", 'sec-ch-ua-mobil...
               │        │   └ 'https://tieba.baidu.com/f/search/res?isnew=1&kw=&qw=专访：美激进货币政策将阻碍墨西哥等新兴经济体复苏——访…&rn=10&un=&only_thread=0&sm=1&sd=&ed=&pn=2'
               │        └ <function get at 0x7fe06b2724c0>
               └ <module 'requests' from '/home/chase/.local/lib/python3.8/site-packages/requests/__init__.py'>

  File "/home/chase/.local/lib/python3.8/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
           │              │           │         └ {'headers': {'Connection': 'keep-alive', 'sec-ch-ua': "'Chromium';v='92',' Not A;Brand';v='99', 'Google Chrome';v='92'", 'sec...
           │              │           └ None
           │              └ 'https://tieba.baidu.com/f/search/res?isnew=1&kw=&qw=专访：美激进货币政策将阻碍墨西哥等新兴经济体复苏——访…&rn=10&un=&only_thread=0&sm=1&sd=&ed=&pn=2'
           └ <function request at 0x7fe06b268310>
  File "/home/chase/.local/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
           │       │              │           │      └ {'params': None, 'headers': {'Connection': 'keep-alive', 'sec-ch-ua': "'Chromium';v='92',' Not A;Brand';v='99', 'Google Chrom...
           │       │              │           └ 'https://tieba.baidu.com/f/search/res?isnew=1&kw=&qw=专访：美激进货币政策将阻碍墨西哥等新兴经济体复苏——访…&rn=10&un=&only_thread=0&sm=1&sd=&ed=&pn=2'
           │       │              └ 'get'
           │       └ <function Session.request at 0x7fe06b27bc10>
           └ <requests.sessions.Session object at 0x7fde703a6d60>
  File "/home/chase/.local/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
           │    │    │       └ {'timeout': 50, 'allow_redirects': True, 'verify': True, 'proxies': OrderedDict(), 'stream': False, 'cert': None}
           │    │    └ <PreparedRequest [GET]>
           │    └ <function Session.send at 0x7fe06b2720d0>
           └ <requests.sessions.Session object at 0x7fde703a6d60>
  File "/home/chase/.local/lib/python3.8/site-packages/requests/sessions.py", line 677, in send
    history = [resp for resp in gen]
                                └ <generator object SessionRedirectMixin.resolve_redirects at 0x7fde7068a4a0>
  File "/home/chase/.local/lib/python3.8/site-packages/requests/sessions.py", line 677, in <listcomp>
    history = [resp for resp in gen]
  File "/home/chase/.local/lib/python3.8/site-packages/requests/sessions.py", line 237, in resolve_redirects
    resp = self.send(
           │    └ <function Session.send at 0x7fe06b2720d0>
           └ <requests.sessions.Session object at 0x7fde703a6d60>
  File "/home/chase/.local/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
        │       │    │          └ {'stream': False, 'timeout': 50, 'verify': True, 'cert': None, 'proxies': OrderedDict()}
        │       │    └ <PreparedRequest [GET]>
        │       └ <function HTTPAdapter.send at 0x7fe06b27b550>
        └ <requests.adapters.HTTPAdapter object at 0x7fdd3d813eb0>
  File "/home/chase/.local/lib/python3.8/site-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
          │                   └ <PreparedRequest [GET]>
          └ <class 'requests.exceptions.SSLError'>

requests.exceptions.SSLError: HTTPSConnectionPool(host='wappass.baidu.com', port=443): Max retries exceeded with url: /static/captcha/tuxing.html?ak=2ef521ec36290baed33d66de9b16f625&backurl=http%3A%2F%2Ftieba.baidu.com%2Ff%2Fsearch%2Fres%3Fisnew%3D1%26kw%3D%26qw%3D%25E4%25B8%2593%25E8%25AE%25BF%25EF%25BC%259A%25E7%25BE%258E%25E6%25BF%2580%25E8%25BF%259B%25E8%25B4%25A7%25E5%25B8%2581%25E6%2594%25BF%25E7%25AD%2596%25E5%25B0%2586%25E9%2598%25BB%25E7%25A2%258D%25E5%25A2%25A8%25E8%25A5%25BF%25E5%2593%25A5%25E7%25AD%2589%25E6%2596%25B0%25E5%2585%25B4%25E7%25BB%258F%25E6%25B5%258E%25E4%25BD%2593%25E5%25A4%258D%25E8%258B%258F%25E2%2580%2594%25E2%2580%2594%25E8%25AE%25BF%25E2%2580%25A6%26rn%3D10%26un%3D%26only_thread%3D0%26sm%3D1%26sd%3D%26ed%3D%26pn%3D2&timestamp=1654686540&signature=a1c27192b97a1184d4acc751cbb56786 (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1131)')))
2022-06-08 19:10:00.827 | ERROR    | monitor.searchSpiders.tieba:get_request_from_keyword:34 - E 贴吧错误HTTPSConnectionPool(host='wappass.baidu.com', port=443): Max retries exceeded with url: /static/captcha/tuxing.html?ak=2ef521ec36290baed33d66de9b16f625&backurl=http%3A%2F%2Ftieba.baidu.com%2Ff%2Fsearch%2Fres%3Fisnew%3D1%26kw%3D%26qw%3D%25E6%2597%25A5%25E6%259C%25AC%25E7%25A0%2594%25E7%25A9%25B6%25E5%258F%2591%25E7%258E%25B0%25E5%25B0%258F%25E8%25A1%258C%25E6%2598%259F%25E6%25A0%25B7%25E6%259C%25AC%25E4%25B8%25AD%25E5%25AD%2598%25E5%259C%25A8%25E5%25A4%259A%25E7%25A7%258D%25E6%25B0%25A8%25E5%259F%25BA%25E9%2585%25B8%26rn%3D10%26un%3D%26only_thread%3D0%26sm%3D1%26sd%3D%26ed%3D%26pn%3D22&timestamp=1654686600&signature=2f87df31e662b303fd65054b60a57877 (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1131)')))
Traceback (most recent call last):

  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
                       │    └ <function HTTPConnectionPool._make_request at 0x7fe06b3fed30>
                       └ <urllib3.connectionpool.HTTPSConnectionPool object at 0x7fde500844f0>
  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
    │    │              └ <urllib3.connection.HTTPSConnection object at 0x7fdf30612520>
    │    └ <function HTTPSConnectionPool._validate_conn at 0x7fe06b3ff280>
    └ <urllib3.connectionpool.HTTPSConnectionPool object at 0x7fde500844f0>
  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
    │    └ <function HTTPSConnection.connect at 0x7fe06b46d940>
    └ <urllib3.connection.HTTPSConnection object at 0x7fdf30612520>
  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/connection.py", line 416, in connect
    self.sock = ssl_wrap_socket(
    │    │      └ <function ssl_wrap_socket at 0x7fe06b468670>
    │    └ None
    └ <urllib3.connection.HTTPSConnection object at 0x7fdf30612520>
  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
               └ <function _ssl_wrap_socket_impl at 0x7fe06b468820>
  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
           │           │           │                     └ 'wappass.baidu.com'
           │           │           └ <socket.socket [closed] fd=-1, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6>
           │           └ <function SSLContext.wrap_socket at 0x7fe08118de50>
           └ <ssl.SSLContext object at 0x7fded04eb8c0>
  File "/usr/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
           │    │               └ <classmethod object at 0x7fe08c8cfaf0>
           │    └ <class 'ssl.SSLSocket'>
           └ <ssl.SSLContext object at 0x7fded04eb8c0>
  File "/usr/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
    │    └ <function SSLSocket.do_handshake at 0x7fe08c8d2d30>
    └ <ssl.SSLSocket [closed] fd=-1, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6>
  File "/usr/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
    │    └ None
    └ <ssl.SSLSocket [closed] fd=-1, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6>

ssl.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1131)


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/home/chase/.local/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
           │    └ <function HTTPConnectionPool.urlopen at 0x7fe06b3fef70>
           └ <urllib3.connectionpool.HTTPSConnectionPool object at 0x7fde500844f0>
  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
              │       └ <function Retry.increment at 0x7fe06b443280>
              └ Retry(total=0, connect=None, read=False, redirect=None, status=None)
  File "/home/chase/.local/lib/python3.8/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
          │             │      │    │        │             └ 'unknown'
          │             │      │    │        └ <class 'urllib3.exceptions.ResponseError'>
          │             │      │    └ SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1131)'))
          │             │      └ '/static/captcha/tuxing.html?ak=2ef521ec36290baed33d66de9b16f625&backurl=http%3A%2F%2Ftieba.baidu.com%2Ff%2Fsearch%2Fres%3Fis...
          │             └ <urllib3.connectionpool.HTTPSConnectionPool object at 0x7fde500844f0>
          └ <class 'urllib3.exceptions.MaxRetryError'>

urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='wappass.baidu.com', port=443): Max retries exceeded with url: /static/captcha/tuxing.html?ak=2ef521ec36290baed33d66de9b16f625&backurl=http%3A%2F%2Ftieba.baidu.com%2Ff%2Fsearch%2Fres%3Fisnew%3D1%26kw%3D%26qw%3D%25E6%2597%25A5%25E6%259C%25AC%25E7%25A0%2594%25E7%25A9%25B6%25E5%258F%2591%25E7%258E%25B0%25E5%25B0%258F%25E8%25A1%258C%25E6%2598%259F%25E6%25A0%25B7%25E6%259C%25AC%25E4%25B8%25AD%25E5%25AD%2598%25E5%259C%25A8%25E5%25A4%259A%25E7%25A7%258D%25E6%25B0%25A8%25E5%259F%25BA%25E9%2585%25B8%26rn%3D10%26un%3D%26only_thread%3D0%26sm%3D1%26sd%3D%26ed%3D%26pn%3D22&timestamp=1654686600&signature=2f87df31e662b303fd65054b60a57877 (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1131)')))


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/usr/lib/python3.8/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
    │    └ <function Thread._bootstrap_inner at 0x7fe08f92ea60>
    └ <Thread(Thread-32844, started daemon 140590217770752)>
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
    │    └ <function Thread.run at 0x7fe08f92e790>
    └ <Thread(Thread-32844, started daemon 140590217770752)>
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
    │    │        │    │        │    └ {}
    │    │        │    │        └ <Thread(Thread-32844, started daemon 140590217770752)>
    │    │        │    └ ('ProjectManager.run_func_by_thread',)
    │    │        └ <Thread(Thread-32844, started daemon 140590217770752)>
    │    └ <bound method ProjectManager.get_request_from_keywords_hot of <monitor.projectManager.ProjectManager object at 0x7fe063c65790>>
    └ <Thread(Thread-32844, started daemon 140590217770752)>

  File "/home/users/Scy/yuqing/spider/monitor/projectManager.py", line 833, in get_request_from_keywords_hot
    self.search_spider_manager.crawl_by_keyword(
    │    │                     └ <function SearchSpidersManager.crawl_by_keyword at 0x7fe063c71160>
    │    └ <monitor.spiderManager.SearchSpidersManager object at 0x7fe0638938b0>
    └ <monitor.projectManager.ProjectManager object at 0x7fe063c65790>

  File "/home/users/Scy/yuqing/spider/monitor/spiderManager.py", line 118, in crawl_by_keyword
    self.crawl_by_keyword_signal_platform(project_names, platform, keyword, crawl_time, project_times)
    │    │                                │              │         │        │           └ {'default': <monitor.TimeSection object at 0x7fe0639a2b80>}
    │    │                                │              │         │        └ <monitor.TimeSection object at 0x7fdd3d7dd130>
    │    │                                │              │         └ '日本研究发现小行星样本中存在多种氨基酸'
    │    │                                │              └ '贴吧'
    │    │                                └ ['default']
    │    └ <function SearchSpidersManager.crawl_by_keyword_signal_platform at 0x7fe063c71280>
    └ <monitor.spiderManager.SearchSpidersManager object at 0x7fe0638938b0>

  File "/home/users/Scy/yuqing/spider/monitor/spiderManager.py", line 150, in crawl_by_keyword_signal_platform
    requests = self.get_request_from_keyword(platform, keyword_only, **crawl_time.to_dict())
               │    │                        │         │               │          └ <function TimeSection.to_dict at 0x7fe06b8931f0>
               │    │                        │         │               └ <monitor.TimeSection object at 0x7fdd3d7dd130>
               │    │                        │         └ '日本研究发现小行星样本中存在多种氨基酸'
               │    │                        └ '贴吧'
               │    └ <function SearchSpidersManager.get_request_from_keyword at 0x7fe063c713a0>
               └ <monitor.spiderManager.SearchSpidersManager object at 0x7fe0638938b0>

  File "/home/users/Scy/yuqing/spider/monitor/spiderManager.py", line 214, in get_request_from_keyword
    for request in self.spiders[platform].get_request_from_keyword(headers, search_url, keyword, content_url,
                   │    │       │                                  │        │           │        └ None
                   │    │       │                                  │        │           └ '日本研究发现小行星样本中存在多种氨基酸'
                   │    │       │                                  │        └ <string.Template object at 0x7fdd3ccd1ac0>
                   │    │       │                                  └ {'Connection': 'keep-alive', 'sec-ch-ua': "'Chromium';v='92',' Not A;Brand';v='99', 'Google Chrome';v='92'", 'sec-ch-ua-mobil...
                   │    │       └ '贴吧'
                   │    └ {'凤凰网': <monitor.searchSpiders.ifeng.Ifeng object at 0x7fe063893370>, '头条': <monitor.searchSpiders.toutiao.Toutiao object at ...
                   └ <monitor.spiderManager.SearchSpidersManager object at 0x7fe0638938b0>

> File "/home/users/Scy/yuqing/spider/monitor/searchSpiders/tieba.py", line 22, in get_request_from_keyword
    response = requests.get(url, headers=headers, timeout=50)
               │        │   │            └ {'Connection': 'keep-alive', 'sec-ch-ua': "'Chromium';v='92',' Not A;Brand';v='99', 'Google Chrome';v='92'", 'sec-ch-ua-mobil...
               │        │   └ 'https://tieba.baidu.com/f/search/res?isnew=1&kw=&qw=日本研究发现小行星样本中存在多种氨基酸&rn=10&un=&only_thread=0&sm=1&sd=&ed=&pn=22'
               │        └ <function get at 0x7fe06b2724c0>
               └ <module 'requests' from '/home/chase/.local/lib/python3.8/site-packages/requests/__init__.py'>

  File "/home/chase/.local/lib/python3.8/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
           │              │           │         └ {'headers': {'Connection': 'keep-alive', 'sec-ch-ua': "'Chromium';v='92',' Not A;Brand';v='99', 'Google Chrome';v='92'", 'sec...
           │              │           └ None
           │              └ 'https://tieba.baidu.com/f/search/res?isnew=1&kw=&qw=日本研究发现小行星样本中存在多种氨基酸&rn=10&un=&only_thread=0&sm=1&sd=&ed=&pn=22'
           └ <function request at 0x7fe06b268310>
  File "/home/chase/.local/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
           │       │              │           │      └ {'params': None, 'headers': {'Connection': 'keep-alive', 'sec-ch-ua': "'Chromium';v='92',' Not A;Brand';v='99', 'Google Chrom...
           │       │              │           └ 'https://tieba.baidu.com/f/search/res?isnew=1&kw=&qw=日本研究发现小行星样本中存在多种氨基酸&rn=10&un=&only_thread=0&sm=1&sd=&ed=&pn=22'
           │       │              └ 'get'
           │       └ <function Session.request at 0x7fe06b27bc10>
           └ <requests.sessions.Session object at 0x7fdeb029a610>
  File "/home/chase/.local/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
           │    │    │       └ {'timeout': 50, 'allow_redirects': True, 'verify': True, 'proxies': OrderedDict(), 'stream': False, 'cert': None}
           │    │    └ <PreparedRequest [GET]>
           │    └ <function Session.send at 0x7fe06b2720d0>
           └ <requests.sessions.Session object at 0x7fdeb029a610>
  File "/home/chase/.local/lib/python3.8/site-packages/requests/sessions.py", line 677, in send
    history = [resp for resp in gen]
                                └ <generator object SessionRedirectMixin.resolve_redirects at 0x7fde90541120>
  File "/home/chase/.local/lib/python3.8/site-packages/requests/sessions.py", line 677, in <listcomp>
    history = [resp for resp in gen]
  File "/home/chase/.local/lib/python3.8/site-packages/requests/sessions.py", line 237, in resolve_redirects
    resp = self.send(
           │    └ <function Session.send at 0x7fe06b2720d0>
           └ <requests.sessions.Session object at 0x7fdeb029a610>
  File "/home/chase/.local/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
        │       │    │          └ {'stream': False, 'timeout': 50, 'verify': True, 'cert': None, 'proxies': OrderedDict()}
        │       │    └ <PreparedRequest [GET]>
        │       └ <function HTTPAdapter.send at 0x7fe06b27b550>
        └ <requests.adapters.HTTPAdapter object at 0x7fdd21d3a7c0>
  File "/home/chase/.local/lib/python3.8/site-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
          │                   └ <PreparedRequest [GET]>
          └ <class 'requests.exceptions.SSLError'>

requests.exceptions.SSLError: HTTPSConnectionPool(host='wappass.baidu.com', port=443): Max retries exceeded with url: /static/captcha/tuxing.html?ak=2ef521ec36290baed33d66de9b16f625&backurl=http%3A%2F%2Ftieba.baidu.com%2Ff%2Fsearch%2Fres%3Fisnew%3D1%26kw%3D%26qw%3D%25E6%2597%25A5%25E6%259C%25AC%25E7%25A0%2594%25E7%25A9%25B6%25E5%258F%2591%25E7%258E%25B0%25E5%25B0%258F%25E8%25A1%258C%25E6%2598%259F%25E6%25A0%25B7%25E6%259C%25AC%25E4%25B8%25AD%25E5%25AD%2598%25E5%259C%25A8%25E5%25A4%259A%25E7%25A7%258D%25E6%25B0%25A8%25E5%259F%25BA%25E9%2585%25B8%26rn%3D10%26un%3D%26only_thread%3D0%26sm%3D1%26sd%3D%26ed%3D%26pn%3D22&timestamp=1654686600&signature=2f87df31e662b303fd65054b60a57877 (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1131)')))
